/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMOptimalBrowser)
+ (id)optimalBrowserSliderButtonImageForContentIcon:(id)fp8;
+ (id)optimalBrowserSliderTrackImageWithContentIcon:(id)fp8 trackSize:(struct CGSize)fp12;
+ (id)optimalBrowserEtchedContentIconWithName:(id)fp8 fillColor:(id)fp12;
+ (id)optimalBrowserColoredContentIconWithName:(id)fp8 fillColor:(id)fp12;
+ (id)optimalBrowserSettingsIcon;
@end

