/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMGif)
+ (id)jm_decodeGIFAtFilePath:(id)fp8 onProgress:(id)fp(null) shouldStopWhen:(void)fp12;
+ (BOOL)jm_gifUnderMemoryPressure;
+ (void)jm_gifDidReceiveMemoryWarning;
+ (void)jm_gifRegisterForMemoryWarnings;
+ (void)jm_remoteAnimatedGIFWithURL:(id)fp8 onProgress:(id)fp(null) onRetrieveComplete:(void)fp12 onFailure:(id)fp(null) caller:(void)fp16;
+ (unsigned int)jm_maximumGIFFileSizeBytes;
@end

