/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMHierarchy)
+ (void)jm_createOpaqueImageRepresentationOfView:(id)fp8 onComplete:(id)fp(null);
- (void)jm_removeGestureRecognizersInSubviews;
- (void)jm_removeGestureRecognizers;
- (BOOL)jm_isOnscreen;
- (struct CGRect)jm_globalFrame;
- (void)jm_removeAllSubviews;
- (void)jm_stopAnimating;
- (id)jm_imageViewRepresentation;
- (id)jm_opaqueImageRepresentation;
- (id)jm_imageRepresentation;
- (id)jm_firstSubviewOfClass:(Class)fp8;
- (id)jm_subviewsOfClass:(Class)fp8;
- (id)jm_subviewsMatchingValidation:(id)fp(null);
- (id)jm_findFirstResponder;
- (id)jm_firstParentViewMatchingValidation:(id)fp(null);
- (id)jm_firstParentOfClass:(Class)fp8;
@end

