/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (UIView_Additions)
+ (void)jm_animateSlow:(id)fp(null) completion:(void)fp8 animated:(id)fp(null);
+ (void)jm_animateFast:(id)fp(null) completion:(void)fp8 animated:(id)fp(null);
+ (void)jm_animateWithDuration:(double)fp8 animations:(id)fp(null) completion:(void)fp16 animated:(id)fp(null);
+ (void)drawVerticalText:(id)fp8 context:(struct CGContext *)fp12 point:(struct CGPoint)fp16 font:(id)fp24;
+ (void)drawGradientBackgroundInRect:(struct CGRect)fp8;
+ (void)drawGradientInRect:(struct CGRect)fp8 minHeight:(float)fp24 startColor:(id)fp28 endColor:(id)fp32;
+ (void)addRoundedRectToPathForContext:(struct CGContext *)fp8 rect:(struct CGRect)fp12 ovalWidth:(float)fp28 ovalHeight:(float)fp32;
+ (void)startEtchedInnerShadowDrawWithColor:(id)fp8;
+ (void)endEtchedDropShadowDraw;
+ (void)startEtchedDropShadowDraw;
+ (void)endEtchedInnerShadowDraw;
+ (void)startEtchedInnerShadowDraw;
+ (void)endEtchedDraw;
+ (void)startEtchedDraw;
+ (void)endShadowedDraw;
+ (void)startShadowedDraw;
+ (void)startShadowedDrawWithOpacity:(float)fp8;
+ (void)startShadowedDrawWithShadowColor:(id)fp8;
- (id)firstSubviewOfClass:(Class)fp8;
- (id)subviewsOfClass:(Class)fp8;
- (id)subviewsMatchingValidation:(id)fp(null);
- (id)imageViewRepresentation;
- (id)imageRepresentation;
- (id)findFirstResponder;
- (id)colorOfPoint:(struct CGPoint)fp8;
- (void)drawInnerShadowInRect:(struct CGRect)fp8 fillColor:(id)fp24;
- (void)clearSubviews;
- (void)drawTapGlowAtPoint:(struct CGPoint)fp8;
- (void)drawNoise;
- (void)drawRectangleWithRect:(struct CGRect)fp8 withColor:(id)fp24;
@end

