/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Gestures)
- (void)onDoubleTap:(id)fp(null) touches:(void)fp8;
- (void)onTap:(id)fp(null) touches:(void)fp8;
- (void)onTaps:(unsigned int)fp8 touches:(unsigned int)fp12 action:(id)fp(null);
- (void)onDoubleTap:(id)fp(null);
- (void)onTap:(id)fp(null);
@end

