/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (BKAssociatedObjects)
+ (void)removeAllAssociatedObjects;
+ (id)associatedValueForKey:(const void *)fp8;
+ (void)weaklyAssociateValue:(id)fp8 withKey:(const void *)fp12;
+ (void)associateCopyOfValue:(id)fp8 withKey:(const void *)fp12;
+ (void)associateValue:(id)fp8 withKey:(const void *)fp12;
- (void)removeAllAssociatedObjects;
- (id)associatedValueForKey:(const void *)fp8;
- (void)weaklyAssociateValue:(id)fp8 withKey:(const void *)fp12;
- (void)associateCopyOfValue:(id)fp8 withKey:(const void *)fp12;
- (void)associateValue:(id)fp8 withKey:(const void *)fp12;
@end

