/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMRAdditions)
- (BOOL)jmr_containsString:(id)fp8;
- (int)jmr_numberOfOccurrencesOfString:(id)fp8;
- (BOOL)jmr_equalsString:(id)fp8;
- (BOOL)jmr_matchesRegExPattern:(id)fp8;
- (id)jmr_stringByReplacingRegExPattern:(id)fp8 withString:(id)fp12;
- (id)jmr_stringMatchingRegExPattern:(id)fp8;
- (BOOL)jmr_stringMatchesRegularExpression:(id)fp8;
@end

