/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMJSBridge)
- (void)jm_bridgeAttachSynchronousHandlerForTarget:(id)fp8 handler:(SEL)fp12;
- (void)jm_bridgeCallJavascriptMethod:(id)fp8 withData:(id)fp12 onResponseReceive:(id)fp(null);
- (void)i_activateBridge;
- (void)jm_destroyBridge;
- (void)setExposedJSMethodNames:(id)fp8;
- (id)exposedJSMethodNames;
- (void)setBridge:(id)fp8;
- (id)bridge;
@end

