/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMStyle)
- (id)jm_font;
- (float)jm_lineSpacing;
- (float)jm_kerning;
- (void)jm_setKerning:(float)fp8;
- (void)jm_setLineSpacing:(float)fp8;
- (void)jm_setFont:(id)fp8;
- (void)setI_font:(id)fp8;
- (id)i_font;
- (void)setI_lineSpacing:(float)fp8;
- (float)i_lineSpacing;
- (void)setI_kerning:(float)fp8;
- (float)i_kerning;
@end

