/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMPerformance)
+ (id)jm_deviceSummary;
+ (BOOL)jm_isLowMemoryDevice;
+ (BOOL)jm_isSlowDevice;
+ (unsigned int)jm_numberOfCores;
+ (unsigned int)jm_ramSizeInGigabytes;
@end

