/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Alpha)
- (struct CGImage *)th_newBorderMask:(unsigned int)fp8 size:(struct CGSize)fp12;
- (id)transparentBorderImage:(unsigned int)fp8;
- (id)imageWithAlpha;
- (BOOL)hasAlpha;
@end

