/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Shapes)
+ (id)bezierPathWithTriangleCenter:(struct CGPoint)fp8 sideLength:(float)fp16 angle:(float)fp20;
@end

