/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JSONKitSerializingBlockAdditions)
- (id)JSONStringWithOptions:(unsigned int)fp8 serializeUnsupportedClassesUsingBlock:(id)fp(null) error:(void)fp12;
- (id)JSONDataWithOptions:(unsigned int)fp8 serializeUnsupportedClassesUsingBlock:(id)fp(null) error:(void)fp12;
@end

