/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMAdditions)
- (void)jm_usePreIOS7ScrollBehavior;
- (void)jm_dismiss;
- (void)jm_dimissModally;
- (void)jm_dismissFromInsideNavigationController;
@end

