/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Skin)
+ (id)skinBarItemWithIcon:(id)fp8 target:(id)fp12 action:(SEL)fp16;
+ (id)skinBarItemWithTitle:(id)fp8 target:(id)fp12 action:(SEL)fp16;
+ (id)skinBarItemWithTitle:(id)fp8 textColor:(id)fp12 target:(id)fp16 action:(SEL)fp20;
+ (id)skinBarItemWithTitle:(id)fp8 textColor:(id)fp12 fillColor:(id)fp16 positionOffset:(struct CGSize)fp20 target:(id)fp28 action:(SEL)fp32;
+ (id)skinBarItemWithIcon:(id)fp8 fillColor:(id)fp12 target:(id)fp16 action:(SEL)fp20;
+ (id)skinBarItemWithIcon:(id)fp8 fillColor:(id)fp12 positionOffset:(struct CGSize)fp16 target:(id)fp24 action:(SEL)fp28;
- (id)generateNavbarButtonIcon;
- (id)generateButtonWithTitleForSize:(struct CGSize)fp8;
- (void)applyThemeSettings;
- (void)setJmPositionOffset:(struct CGSize)fp8;
- (struct CGSize)jmPositionOffset;
- (void)setJmSkinTitleColor:(id)fp8;
- (id)jmSkinTitleColor;
- (void)setJmForceFillColor:(id)fp8;
- (id)jmForceFillColor;
- (void)setJmSkinTitle:(id)fp8;
- (id)jmSkinTitle;
- (void)setJmSkinIconName:(id)fp8;
- (id)jmSkinIconName;
@end

