/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMCache)
+ (id)jm_cachedImageForKey:(id)fp8;
+ (void)jm_cacheImage:(id)fp8 key:(id)fp12;
+ (void)jm_clearCachedImages;
+ (id)cache;
@end

