/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (OAParameterAdditions)
- (void)attachFileWithParameterName:(id)fp8 filename:(id)fp12 contentType:(id)fp16 data:(id)fp20;
- (void)setParameters:(id)fp8;
- (id)parameters;
@end

