/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (RoundedCorner)
- (void)th_addRoundedRectToPath:(struct CGRect)fp8 context:(struct CGContext *)fp24 ovalWidth:(float)fp28 ovalHeight:(float)fp32;
- (id)roundedCornerImage:(int)fp8 borderSize:(int)fp12;
@end

