/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Decorators)
- (void)drawDecoratorsWithDirtyRect:(struct CGRect)fp8;
- (void)setDecorators:(id)fp(null);
- (void)setDecorator:(id)fp(null);
- (id)decorator;
- (BOOL)hasDecorator;
@end

