/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (JMRemote)
- (void)jm_cancelRemoteImageLoading;
- (void)jm_setEtchedAndShadowedRemotedImageWithURL:(id)fp8 placeholder:(id)fp12;
- (void)jm_didFinishImageRetrieveWithImage:(id)fp8 onComplete:(id)fp(null);
- (void)jm_attachViewHierarchyObservers;
- (void)jm_setRemoteImageWithURL:(id)fp8 placeholder:(id)fp12 decorator:(id)fp16 onProgress:(id)fp(null) onComplete:(void)fp20 onFailure:(id)fp(null);
- (void)setI_windowObserverToken:(id)fp8;
- (id)i_windowObserverToken;
- (void)setI_superviewObserverToken:(id)fp8;
- (id)i_superviewObserverToken;
- (void)setI_decoratorKey:(id)fp8;
- (id)i_decoratorKey;
- (void)setHierarchyObserversAttached:(BOOL)fp8;
- (BOOL)hierarchyObserversAttached;
- (void)setHasFinishedLoading:(BOOL)fp8;
- (BOOL)hasFinishedLoading;
- (void)setJm_remoteImageURL:(id)fp8;
- (id)jm_remoteImageURL;
@end

