/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Blocks)
+ (void)jdExecuteSimpleBlock:(id)fp8;
+ (id)timerWithTimeInterval:(double)fp8 block:(id)fp(null) repeats:(void)fp16;
+ (id)scheduledTimerWithTimeInterval:(double)fp8 block:(id)fp(null) repeats:(void)fp16;
@end

