/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMethodSignature, NSMutableArray, NSMutableSet;

@interface A2BlockInvocation : _AVAudioSessionCategoryPlayback
{
    BOOL _argumentsRetained;
    BOOL _validReturn;
    void **_argumentFrame;
    void *_returnValue;
    unsigned long _returnLength;
    void *_block;
    NSMethodSignature *_methodSignature;
    NSMethodSignature *_blockSignature;
    NSMutableArray *_allocations;
    NSMutableSet *_retainedArguments;
    CDAnonymousStruct2 _interface;
}

- (void)setInterface:(CDAnonymousStruct2)fp8;
- (CDAnonymousStruct2)interface;
- (void)setRetainedArguments:(id)fp8;
- (id)retainedArguments;
- (void)setAllocations:(id)fp8;
- (id)allocations;
- (void)a2_setBlockSignature:(id)fp8;
- (id)blockSignature;
- (void)a2_setMethodSignature:(id)fp8;
- (id)methodSignature;
- (void).cxx_destruct;
- (void)invokeUsingInvocation:(id)fp8;
- (void)invoke;
- (void)setArgument:(void *)fp8 atIndex:(int)fp12;
- (void)getArgument:(void *)fp8 atIndex:(int)fp12;
- (void)setReturnValue:(void *)fp8;
- (void)getReturnValue:(void *)fp8;
- (BOOL)argumentsRetained;
- (void)retainArguments;
- (void)dealloc;
- (void)clearArguments;
- (id)block;
- (id)initWithBlock:(id)fp8 methodSignature:(id)fp12;

@end

