/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CustomNavigationBar.h"

@class UIImageView;

@interface ABNavigationBar : CustomNavigationBar
{
    BOOL forceDark_;
    UIImageView *_jm_shadowView;
}

+ (id)barButtonItemTextAttributes;
+ (void)setupGlobalAppearanceCustomisations;
+ (id)ab_barBackButtonItemBackgroundImage;
+ (id)ab_barButtonItemBackgroundImage;
+ (void)initialize;
- (void)setJm_shadowView:(id)fp8;
- (id)jm_shadowView;
- (void)setForceDark:(BOOL)fp8;
- (BOOL)forceDark;
- (void).cxx_destruct;
- (void)setItems:(id)fp8 animated:(BOOL)fp12;
- (void)layoutSubviews;
- (void)setNeedsLayout;
- (void)replaceNativeButtonViewWithCustomVersion:(id)fp8;
- (void)didTapCustomBack;
- (void)setFrame:(struct CGRect)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)makeDark;
- (void)setBarStyle:(int)fp8;
- (void)nightSwitch;
- (void)defaultsChanged:(id)fp8;
- (void)customizeAppearanceOfBarButtonItems;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)initializeView;

@end

