/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDate;

@interface ABNotificationManager : _AVAudioSessionCategoryPlayback
{
    NSDate *_lastMessageCheckDate;
}

+ (id)manager;
- (void)setLastMessageCheckDate:(id)fp8;
- (id)lastMessageCheckDate;
- (void).cxx_destruct;
- (BOOL)handleLocalNotification:(id)fp8;
- (void)applicationWillResignActive;
- (void)applicationDidEnterBackground;
- (void)applicationDidBecomeActive;
- (void)handleRedditNotificationsOnComplete:(id)fp(null);
- (void)scheduleNotificationsFromMessages:(id)fp8;
- (id)filterMessagesThatRequireNotification:(id)fp8;
- (void)retrieveAllUnreadMessagesOnComplete:(id)fp(null);
- (id)sortMessagesByOldestFirst:(id)fp8;
- (void)retrieveUnreadMessagesAtBaseUrl:(id)fp8 skipWhen:(BOOL)fp12 onComplete:(id)fp(null);
- (void)checkIfUserHasMailOnComplete:(id)fp(null);
- (BOOL)shouldCheckInbox;

@end

