/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface ABTableView : _AVAudioSessionCategoryPlayback
{
}

- (void)reloadRowsAtIndexPaths:(id)fp8 withRowAnimation:(int)fp12;
- (id)initWithCoder:(id)fp8;

@end

