/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ItemSelectorViewController.h"

@interface AccountSelectorViewController : ItemSelectorViewController
{
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)loadView;
- (id)initWithDelegate:(id)fp8;
- (void)prepareOptions;

@end

