/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface ActionWrapper : _AVAudioSessionCategoryPlayback
{
    id action_;
}

+ (id)instanceWithAction:(id)fp(null);
- (void)setAction:(id)fp(null);
- (id)action;
- (void).cxx_destruct;
- (void)invokeAction:(id)fp8;

@end

