/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSOperationQueue, NSURL, NSURLCredential;

@interface AFHTTPClient : _AVAudioSessionCategoryPlayback <NSCoding, NSCopying>
{
    NSURL *_baseURL;
    unsigned int _stringEncoding;
    int _parameterEncoding;
    NSMutableArray *_registeredHTTPOperationClassNames;
    NSMutableDictionary *_defaultHeaders;
    NSURLCredential *_defaultCredential;
    NSOperationQueue *_operationQueue;
    struct __SCNetworkReachability *_networkReachability;
    int _networkReachabilityStatus;
    id _networkReachabilityStatusBlock;
}

+ (id)clientWithBaseURL:(id)fp8;
- (void)setNetworkReachabilityStatusBlock:(id)fp(null);
- (id)networkReachabilityStatusBlock;
- (void)setNetworkReachabilityStatus:(int)fp8;
- (int)networkReachabilityStatus;
- (void)setNetworkReachability:(struct __SCNetworkReachability *)fp8;
- (struct __SCNetworkReachability *)networkReachability;
- (void)setOperationQueue:(id)fp8;
- (id)operationQueue;
- (void)setDefaultCredential:(id)fp8;
- (id)defaultCredential;
- (void)setDefaultHeaders:(id)fp8;
- (id)defaultHeaders;
- (void)setRegisteredHTTPOperationClassNames:(id)fp8;
- (id)registeredHTTPOperationClassNames;
- (void)setParameterEncoding:(int)fp8;
- (int)parameterEncoding;
- (void)setStringEncoding:(unsigned int)fp8;
- (unsigned int)stringEncoding;
- (void)setBaseURL:(id)fp8;
- (id)baseURL;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)patchPath:(id)fp8 parameters:(id)fp12 success:(id)fp(null) failure:(void)fp16;
- (void)deletePath:(id)fp8 parameters:(id)fp12 success:(id)fp(null) failure:(void)fp16;
- (void)putPath:(id)fp8 parameters:(id)fp12 success:(id)fp(null) failure:(void)fp16;
- (void)postPath:(id)fp8 parameters:(id)fp12 success:(id)fp(null) failure:(void)fp16;
- (void)getPath:(id)fp8 parameters:(id)fp12 success:(id)fp(null) failure:(void)fp16;
- (void)enqueueBatchOfHTTPRequestOperations:(id)fp8 progressBlock:(id)fp(null) completionBlock:(void)fp12;
- (void)enqueueBatchOfHTTPRequestOperationsWithRequests:(id)fp8 progressBlock:(id)fp(null) completionBlock:(void)fp12;
- (void)cancelAllHTTPOperationsWithMethod:(id)fp8 path:(id)fp12;
- (void)enqueueHTTPRequestOperation:(id)fp8;
- (id)HTTPRequestOperationWithRequest:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (id)multipartFormRequestWithMethod:(id)fp8 path:(id)fp12 parameters:(id)fp16 constructingBodyWithBlock:(id)fp(null);
- (id)requestWithMethod:(id)fp8 path:(id)fp12 parameters:(id)fp16;
- (void)clearAuthorizationHeader;
- (void)setAuthorizationHeaderWithToken:(id)fp8;
- (void)setAuthorizationHeaderWithUsername:(id)fp8 password:(id)fp12;
- (void)setDefaultHeader:(id)fp8 value:(id)fp12;
- (id)defaultValueForHeader:(id)fp8;
- (void)unregisterHTTPOperationClass:(Class)fp8;
- (BOOL)registerHTTPOperationClass:(Class)fp8;
- (void)setReachabilityStatusChangeBlock:(id)fp(null);
- (void)stopMonitoringNetworkReachability;
- (void)startMonitoringNetworkReachability;
- (id)description;
- (void)dealloc;
- (id)initWithBaseURL:(id)fp8;

@end

