/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPRequestOperation.h"

@class UIImage;

@interface AFImageRequestOperation : AFHTTPRequestOperation
{
    UIImage *_responseImage;
    float _imageScale;
}

+ (BOOL)canProcessRequest:(id)fp8;
+ (id)acceptableContentTypes;
+ (id)imageRequestOperationWithRequest:(id)fp8 imageProcessingBlock:(id)fp(null) success:(void)fp12 failure:(id)fp(null);
+ (id)imageRequestOperationWithRequest:(id)fp8 success:(id)fp(null);
- (float)imageScale;
- (void)setResponseImage:(id)fp8;
- (void).cxx_destruct;
- (void)setCompletionBlockWithSuccess:(id)fp(null) failure:(void)fp8;
- (void)setImageScale:(float)fp8;
- (id)responseImage;
- (id)initWithRequest:(id)fp8;

@end

