/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPRequestOperation.h"

@class NSError;

@interface AFJSONRequestOperation : AFHTTPRequestOperation
{
    id _responseJSON;
    unsigned int _JSONReadingOptions;
    NSError *_JSONError;
}

+ (BOOL)canProcessRequest:(id)fp8;
+ (id)acceptableContentTypes;
+ (id)JSONRequestOperationWithRequest:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (void)setJSONError:(id)fp8;
- (id)JSONError;
- (void)setJSONReadingOptions:(unsigned int)fp8;
- (unsigned int)JSONReadingOptions;
- (void)setResponseJSON:(id)fp8;
- (void).cxx_destruct;
- (void)setCompletionBlockWithSuccess:(id)fp(null) failure:(void)fp8;
- (id)error;
- (id)responseJSON;

@end

