/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"
#import "NSStreamDelegate-Protocol.h"

@class AFHTTPBodyPart, NSEnumerator, NSInputStream, NSMutableArray, NSMutableData, NSOutputStream;

@interface AFMultipartBodyStreamProvider : _AVAudioSessionCategoryPlayback <NSCopying, NSStreamDelegate>
{
    id _self;
    unsigned int _stringEncoding;
    NSMutableArray *_HTTPBodyParts;
    NSEnumerator *_HTTPBodyPartEnumerator;
    AFHTTPBodyPart *_currentHTTPBodyPart;
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    NSMutableData *_buffer;
    unsigned int _numberOfBytesInPacket;
    double _delay;
}

- (void)setDelay:(double)fp8;
- (double)delay;
- (void)setBufferLength:(unsigned int)fp8;
- (unsigned int)bufferLength;
- (void)setBuffer:(id)fp8;
- (id)buffer;
- (void)setOutputStream:(id)fp8;
- (id)outputStream;
- (void)setInputStream:(id)fp8;
- (void)setCurrentHTTPBodyPart:(id)fp8;
- (id)currentHTTPBodyPart;
- (void)setHTTPBodyPartEnumerator:(id)fp8;
- (id)HTTPBodyPartEnumerator;
- (void)setHTTPBodyParts:(id)fp8;
- (id)HTTPBodyParts;
- (void)setStringEncoding:(unsigned int)fp8;
- (unsigned int)stringEncoding;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned long long)contentLength;
- (void)close;
- (void)handleOutputStreamSpaceAvailable;
- (void)stream:(id)fp8 handleEvent:(unsigned int)fp12;
- (BOOL)isEmpty;
- (id)inputStream;
- (void)appendHTTPBodyPart:(id)fp8;
- (void)setInitialAndFinalBoundaries;
- (void)dealloc;
- (id)initWithStringEncoding:(unsigned int)fp8;

@end

