/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPRequestOperation.h"

@class NSError, NSXMLParser;

@interface AFXMLRequestOperation : AFHTTPRequestOperation
{
    NSXMLParser *_responseXMLParser;
    NSError *_XMLError;
}

+ (BOOL)canProcessRequest:(id)fp8;
+ (id)acceptableContentTypes;
+ (id)XMLParserRequestOperationWithRequest:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (void)setXMLError:(id)fp8;
- (id)XMLError;
- (void)setResponseXMLParser:(id)fp8;
- (void).cxx_destruct;
- (void)setCompletionBlockWithSuccess:(id)fp(null) failure:(void)fp8;
- (void)cancel;
- (id)error;
- (id)responseXMLParser;

@end

