/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineNode.h"

@interface BaseStyledTextNode : JMOutlineNode
{
    unsigned int _numThumbnailsPrefetched;
}

- (void)setNumThumbnailsPrefetched:(unsigned int)fp8;
- (unsigned int)numThumbnailsPrefetched;
- (void)prefetchThumbnailsToCacheOnComplete:(id)fp(null);
- (float)heightForBodyConstrainedToWidth:(float)fp8;
- (id)thumbLinks;
- (id)styledText;
- (BOOL)containsRestrictedContent;
- (BOOL)containsNSFWContent;
- (id)elementId;
- (void)setInlinePreviewLink:(id)fp8;
- (id)inlinePreviewLink;
- (void)setInlineImageAspectRatio:(id)fp8;
- (id)inlineImageAspectRatio;

@end

