/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface BITCrashReportTextFormatter : _AVAudioSessionCategoryPlayback
{
}

+ (id)arrayOfAppUUIDsForCrashReport:(id)fp8;
+ (id)stringValueForCrashReport:(id)fp8 crashReporterKey:(id)fp12;
+ (id)formatStackFrame:(id)fp8 frameIndex:(unsigned int)fp12 report:(id)fp16;

@end

