/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDate, NSNumber, NSString;

@interface BITFeedbackMessage : _AVAudioSessionCategoryPlayback
{
    BOOL _userMessage;
    NSString *_text;
    NSString *_userID;
    NSString *_name;
    NSString *_email;
    NSDate *_date;
    NSNumber *_id;
    NSString *_token;
    int _status;
}

- (void)setUserMessage:(BOOL)fp8;
- (BOOL)userMessage;
- (void)setStatus:(int)fp8;
- (int)status;
- (void)setToken:(id)fp8;
- (id)token;
- (void)setId:(id)fp8;
- (id)id;
- (void)setDate:(id)fp8;
- (id)date;
- (void)setEmail:(id)fp8;
- (id)email;
- (void)setName:(id)fp8;
- (id)name;
- (void)setUserID:(id)fp8;
- (id)userID;
- (void)setText:(id)fp8;
- (id)text;
- (void).cxx_destruct;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)init;

@end

