/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextFieldDelegate-Protocol.h"

@class BITFeedbackManager, NSString;

@interface BITFeedbackUserDataViewController : _AVAudioSessionCategoryPlayback <UITextFieldDelegate>
{
    int _statusBarStyle;
    id <BITFeedbackUserDataDelegate> _delegate;
    BITFeedbackManager *_manager;
    NSString *_name;
    NSString *_email;
}

- (void)setEmail:(id)fp8;
- (id)email;
- (void)setName:(id)fp8;
- (id)name;
- (void)setManager:(id)fp8;
- (id)manager;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)saveAction:(id)fp8;
- (void)dismissAction:(id)fp8;
- (void)userEmailEntered:(id)fp8;
- (void)userNameEntered:(id)fp8;
- (BOOL)allRequiredFieldsEntered;
- (BOOL)validateEmail;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithStyle:(int)fp8;

@end

