/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "BITFeedbackUserDataDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class BITFeedbackManager, NSString, UITextView;

@interface BITFeedbackComposeViewController : _AVAudioSessionCategoryPlayback <BITFeedbackUserDataDelegate, UITextViewDelegate>
{
    int _statusBarStyle;
    BOOL _blockUserDataScreen;
    id <BITFeedbackComposeViewControllerDelegate> _delegate;
    BITFeedbackManager *_manager;
    UITextView *_textView;
    NSString *_text;
}

- (void)setText:(id)fp8;
- (id)text;
- (void)setTextView:(id)fp8;
- (id)textView;
- (void)setManager:(id)fp8;
- (id)manager;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)textViewDidChange:(id)fp8;
- (void)userDataUpdateFinished;
- (void)userDataUpdateCancelled;
- (void)sendAction:(id)fp8;
- (void)dismissAction:(id)fp8;
- (void)setUserDataAction;
- (void)dismiss;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)keyboardWillBeHidden:(id)fp8;
- (void)keyboardWasShown:(id)fp8;
- (void)prepareWithItems:(id)fp8;
- (id)init;

@end

