/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface BITHockeyBaseViewController : _AVAudioSessionCategoryPlayback
{
    BOOL _modal;
    int _statusBarStyle;
    BOOL _modalAnimated;
}

- (void)setModalAnimated:(BOOL)fp8;
- (BOOL)modalAnimated;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)onDismissModal:(id)fp8;
- (id)initWithModalStyle:(BOOL)fp8;
- (id)init;

@end

