/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BITHockeyBaseManager.h"

#import "UIAlertViewDelegate-Protocol.h"

@class BITUpdateViewController, NSArray, NSDate, NSDictionary, NSMutableData, NSNumber, NSString, NSURLConnection, UIView;

@interface BITUpdateManager : BITHockeyBaseManager <UIAlertViewDelegate>
{
    NSString *_currentAppVersion;
    BITUpdateViewController *_currentHockeyViewController;
    BOOL _dataFound;
    BOOL _showFeedback;
    BOOL _updateAlertShowing;
    BOOL _lastCheckFailed;
    BOOL _sendUsageData;
    BOOL _didSetupDidBecomeActiveNotifications;
    BOOL _firstStartAfterInstall;
    NSNumber *_versionID;
    NSString *_versionUUID;
    NSString *_uuid;
    BOOL _checkForUpdateOnLaunch;
    BOOL _alwaysShowUpdateReminder;
    BOOL _showDirectInstallOption;
    BOOL _requireAuthorization;
    BOOL _updateAvailable;
    BOOL _checkInProgress;
    BOOL _checkForTracker;
    BOOL _disableUpdateManager;
    id _delegate;
    int _updateSetting;
    NSString *_authenticationSecret;
    NSDate *_expiryDate;
    NSMutableData *_receivedData;
    NSDate *_lastCheck;
    NSArray *_appVersions;
    NSURLConnection *_urlConnection;
    NSDate *_usageStartTimestamp;
    UIView *_blockingView;
    NSString *_companyName;
    NSDictionary *_trackerConfig;
}

- (id)currentHockeyViewController;
- (void)setDisableUpdateManager:(BOOL)fp8;
- (BOOL)isUpdateManagerDisabled;
- (void)setTrackerConfig:(id)fp8;
- (id)trackerConfig;
- (void)setCheckForTracker:(BOOL)fp8;
- (BOOL)checkForTracker;
- (void)setCompanyName:(id)fp8;
- (id)companyName;
- (id)blockingView;
- (void)setUsageStartTimestamp:(id)fp8;
- (id)usageStartTimestamp;
- (void)setUrlConnection:(id)fp8;
- (id)urlConnection;
- (id)appVersions;
- (id)lastCheck;
- (void)setReceivedData:(id)fp8;
- (id)receivedData;
- (void)setCheckInProgress:(BOOL)fp8;
- (BOOL)isCheckInProgress;
- (void)setUpdateAvailable:(BOOL)fp8;
- (BOOL)isUpdateAvailable;
- (void)setExpiryDate:(id)fp8;
- (id)expiryDate;
- (void)setAuthenticationSecret:(id)fp8;
- (id)authenticationSecret;
- (void)setRequireAuthorization:(BOOL)fp8;
- (BOOL)isRequireAuthorization;
- (void)setShowDirectInstallOption:(BOOL)fp8;
- (BOOL)isShowingDirectInstallOption;
- (void)setAlwaysShowUpdateReminder:(BOOL)fp8;
- (BOOL)alwaysShowUpdateReminder;
- (void)setCheckForUpdateOnLaunch:(BOOL)fp8;
- (BOOL)isCheckForUpdateOnLaunch;
- (void)setUpdateSetting:(int)fp8;
- (int)updateSetting;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)setBlockingView:(id)fp8;
- (id)newestAppVersion;
- (void)setAppVersions:(id)fp8;
- (void)setLastCheck:(id)fp8;
- (id)currentAppVersion;
- (void)setCurrentHockeyViewController:(id)fp8;
- (BOOL)hasNewerMandatoryVersion;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)startManager;
- (BOOL)appVersionIsAuthorized;
- (BOOL)initiateAppDownload;
- (void)checkForUpdateShowFeedback:(BOOL)fp8;
- (void)checkForUpdate;
- (void)checkForAuthorization;
- (BOOL)shouldCheckForUpdates;
- (void)showBlockingScreen:(id)fp8 image:(id)fp12;
- (void)alertFallback:(id)fp8;
- (void)showCheckForUpdateAlert;
- (void)showUpdateView;
- (id)hockeyViewController:(BOOL)fp8;
- (void)dealloc;
- (id)init;
- (id)findVisibleWindow;
- (void)saveAppCache;
- (void)loadAppCache;
- (void)checkUpdateAvailable;
- (int)authorizationState;
- (id)authenticationToken;
- (id)deviceIdentifier;
- (id)installationDateString;
- (id)currentUsageString;
- (void)stopUsage;
- (void)startUsage;
- (void)checkExpiryDateReached;
- (BOOL)expiryDateReached;
- (void)cleanupDidBecomeActiveNotifications;
- (void)setupDidBecomeActiveNotifications;
- (void)didBecomeActiveActions;
- (void)reportError:(id)fp8;

@end

