/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIWebViewDelegate-Protocol.h"

@class NSString, UIColor, UIWebView;

@interface BITWebTableViewCell : _AVAudioSessionCategoryPlayback <UIWebViewDelegate>
{
    UIWebView *_webView;
    NSString *_webViewContent;
    UIColor *_cellBackgroundColor;
    struct CGSize _webViewSize;
}

- (void)setCellBackgroundColor:(id)fp8;
- (id)cellBackgroundColor;
- (void)setWebViewSize:(struct CGSize)fp8;
- (struct CGSize)webViewSize;
- (id)webViewContent;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void).cxx_destruct;
- (void)webViewDidFinishLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)prepareForReuse;
- (void)setFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)setWebViewContent:(id)fp8;
- (void)removeWebView;
- (void)showWebView;
- (void)addWebView;

@end

