/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserViewController.h"

@interface BrowserViewController_iPhone : BrowserViewController
{
}

- (void)contentCoordinatorStandardBrowserDidFinishLoading:(id)fp8;
- (void)loadView;
- (void)viewDidLoad;

@end

