/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UIImageView, UILabel;

@interface CanvasPreviewDemo : _AVAudioSessionCategoryPlayback
{
    UIImageView *imageView;
    UIButton *upgradeButton;
    UILabel *iOS4RecommendedLabel;
}

- (void)setIOS4RecommendedLabel:(id)fp8;
- (id)iOS4RecommendedLabel;
- (void)setUpgradeButton:(id)fp8;
- (id)upgradeButton;
- (void)setImageView:(id)fp8;
- (id)imageView;
- (void).cxx_destruct;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)upgradePressed:(id)fp8;
- (void)closePanel:(id)fp8;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

