/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineNode.h"

@class NSString;

@interface CenteredTextNode : JMOutlineNode
{
    NSString *_title;
    NSString *_selectedTitle;
}

+ (Class)cellClass;
+ (id)nodeWithTitle:(id)fp8;
+ (id)nodeWithTitle:(id)fp8 selectedTitle:(id)fp12;
- (void)setSelectedTitle:(id)fp8;
- (id)selectedTitle;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)post;

@end

