/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineNode.h"

@class NSString, UIColor;

@interface CenteredButtonNode : JMOutlineNode
{
    NSString *_title;
    UIColor *_buttonColor;
}

+ (Class)cellClass;
- (void)setButtonColor:(id)fp8;
- (id)buttonColor;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)fp8 buttonColor:(id)fp12;

@end

