/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BaseStyledTextNode.h"

@class Comment, NSNumber, Post;

@interface CommentPostHeaderNode : BaseStyledTextNode
{
    BOOL _isPlaceholderPost;
    BOOL _forceImageLoad;
    Post *_post;
    Comment *_comment;
    NSNumber *_inlineImageAspectRatio;
}

+ (Class)cellClass;
+ (id)placeholderNodeForPost:(id)fp8;
+ (id)nodeForHeaderPost:(id)fp8;
- (void)setForceImageLoad:(BOOL)fp8;
- (BOOL)forceImageLoad;
- (void)setIsPlaceholderPost:(BOOL)fp8;
- (BOOL)isPlaceholderPost;
- (void)setInlineImageAspectRatio:(id)fp8;
- (id)inlineImageAspectRatio;
- (void)setComment:(id)fp8;
- (id)comment;
- (void)setPost:(id)fp8;
- (id)post;
- (void).cxx_destruct;
- (id)thumbLinks;
- (float)heightForBodyConstrainedToWidth:(float)fp8;
- (id)styledText;
- (id)elementId;
- (BOOL)containsRestrictedContent;
- (BOOL)containsNSFWContent;

@end

