/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMViewOverlay.h"

@interface CommentSeparatorBar : JMViewOverlay
{
    unsigned int _commentCount;
}

- (void)setCommentCount:(unsigned int)fp8;
- (unsigned int)commentCount;
- (void)updateWithCommentCount:(unsigned int)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

