/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class JMViewOverlay, ModButtonOverlay, OverlayViewContainer, Post, PostModerationControlView;

@interface CommentPostHeaderToolbar : _AVAudioSessionCategoryPlayback
{
    BOOL _shouldHighlightCanvasButton;
    id _onModerationSendMessage;
    id _onCanvasButtonTap;
    OverlayViewContainer *_containerView;
    JMViewOverlay *_subredditLinkOverlay;
    JMViewOverlay *_authorLinkOverlay;
    JMViewOverlay *_timeOverlay;
    JMViewOverlay *_scoreOverlay;
    JMViewOverlay *_canvasOverlay;
    ModButtonOverlay *_modButtonOverlay;
    PostModerationControlView *_modToolsView;
    Post *_post;
}

+ (id)postHeaderToolbar;
- (void)setPost:(id)fp8;
- (id)post;
- (void)setModToolsView:(id)fp8;
- (id)modToolsView;
- (void)setModButtonOverlay:(id)fp8;
- (id)modButtonOverlay;
- (void)setCanvasOverlay:(id)fp8;
- (id)canvasOverlay;
- (void)setScoreOverlay:(id)fp8;
- (id)scoreOverlay;
- (void)setTimeOverlay:(id)fp8;
- (id)timeOverlay;
- (void)setAuthorLinkOverlay:(id)fp8;
- (id)authorLinkOverlay;
- (void)setSubredditLinkOverlay:(id)fp8;
- (id)subredditLinkOverlay;
- (void)setContainerView:(id)fp8;
- (id)containerView;
- (void)setShouldHighlightCanvasButton:(BOOL)fp8;
- (BOOL)shouldHighlightCanvasButton;
- (void)setOnCanvasButtonTap:(id)fp(null);
- (id)onCanvasButtonTap;
- (void)setOnModerationSendMessage:(id)fp(null);
- (id)onModerationSendMessage;
- (void).cxx_destruct;
- (void)hideModTools;
- (void)didTapModButton;
- (void)dismissModToolsView:(id)fp8;
- (void)presentModToolsView:(id)fp8;
- (void)layoutSubviews;
- (void)updateOverlays;
- (void)setNeedsDisplay;
- (void)updateWithPost:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

