/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMTableCell.h"

@interface CreatePostMoreOptionsCell : JMTableCell
{
}

+ (float)heightForNode:(id)fp8 tableView:(id)fp12;
- (void)drawContainerNode:(id)fp8 rect:(struct CGRect)fp12;
- (void)updateSubviews;
- (void)prepareContentView:(id)fp8;

@end

