/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIColor;

@interface DCCrossHairView : _AVAudioSessionCategoryPlayback
{
    UIColor *color;
}

- (void)setColor:(id)fp8;
- (id)color;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 color:(id)fp24;

@end

