/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class DCCrossHairView, NSMutableArray, UILabel;

@interface DCFrameView : _AVAudioSessionCategoryPlayback
{
    id <DCFrameViewDelegate> delegate;
    UILabel *touchPointLabel;
    NSMutableArray *rectsToOutline;
    DCCrossHairView *touchPointView;
    struct CGRect mainRect;
    struct CGRect superRect;
}

- (void)setTouchPointView:(id)fp8;
- (id)touchPointView;
- (void)setRectsToOutline:(id)fp8;
- (id)rectsToOutline;
- (void)setTouchPointLabel:(id)fp8;
- (id)touchPointLabel;
- (struct CGRect)superRect;
- (struct CGRect)mainRect;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)drawRect:(struct CGRect)fp8;
- (void)setSuperRect:(struct CGRect)fp8;
- (void)setMainRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 delegate:(id)fp24;

@end

