/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "DCFrameViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class DCFrameView, DCStatusBarOverlay, NSMutableArray, NSMutableDictionary, UIGestureRecognizer, UITextView, UIView;

@interface DCIntrospect : _AVAudioSessionCategoryPlayback <DCFrameViewDelegate, UITextViewDelegate, UIWebViewDelegate>
{
    BOOL keyboardBindingsOn;
    BOOL showStatusBarOverlay;
    BOOL on;
    BOOL handleArrowKeys;
    BOOL viewOutlines;
    BOOL highlightNonOpaqueViews;
    BOOL flashOnRedraw;
    BOOL showingHelp;
    UIGestureRecognizer *invokeGestureRecognizer;
    DCStatusBarOverlay *statusBarOverlay;
    UITextView *inputTextView;
    DCFrameView *frameView;
    NSMutableDictionary *objectNames;
    UIView *currentView;
    float originalAlpha;
    NSMutableArray *currentViewHistory;
    struct CGRect originalFrame;
}

+ (id)sharedIntrospector;
+ (void)workaroundUITextInputTraitsPropertiesBug;
+ (void)initialize;
- (void)setShowingHelp:(BOOL)fp8;
- (BOOL)showingHelp;
- (void)setCurrentViewHistory:(id)fp8;
- (id)currentViewHistory;
- (void)setOriginalAlpha:(float)fp8;
- (float)originalAlpha;
- (void)setOriginalFrame:(struct CGRect)fp8;
- (struct CGRect)originalFrame;
- (void)setCurrentView:(id)fp8;
- (id)currentView;
- (void)setObjectNames:(id)fp8;
- (id)objectNames;
- (void)setFrameView:(id)fp8;
- (id)frameView;
- (void)setInputTextView:(id)fp8;
- (id)inputTextView;
- (void)setStatusBarOverlay:(id)fp8;
- (id)statusBarOverlay;
- (void)setFlashOnRedraw:(BOOL)fp8;
- (BOOL)flashOnRedraw;
- (void)setHighlightNonOpaqueViews:(BOOL)fp8;
- (BOOL)highlightNonOpaqueViews;
- (void)setViewOutlines:(BOOL)fp8;
- (BOOL)viewOutlines;
- (void)setHandleArrowKeys:(BOOL)fp8;
- (BOOL)handleArrowKeys;
- (void)setOn:(BOOL)fp8;
- (BOOL)on;
- (id)invokeGestureRecognizer;
- (void)setShowStatusBarOverlay:(BOOL)fp8;
- (BOOL)showStatusBarOverlay;
- (BOOL)keyboardBindingsOn;
- (void).cxx_destruct;
- (BOOL)shouldIgnoreView:(id)fp8;
- (BOOL)view:(id)fp8 containsSubview:(id)fp12;
- (void)fadeView:(id)fp8 toAlpha:(float)fp12;
- (id)viewsAtPoint:(struct CGPoint)fp8 inView:(id)fp16;
- (id)mainWindow;
- (id)subclassesOfClass:(Class)fp8;
- (void)logAccessabilityPropertiesForObject:(id)fp8;
- (void)logPropertiesForObject:(id)fp8;
- (void)logPropertiesForCurrentView;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)toggleHelp;
- (id)describeColor:(id)fp8;
- (id)describeProperty:(id)fp8 value:(id)fp12;
- (void)flashRect:(struct CGRect)fp8 inView:(id)fp24;
- (void)callDrawRectOnViewsInSubview:(id)fp8;
- (void)toggleRedrawFlashing;
- (void)setBackgroundColor:(id)fp8 ofNonOpaqueViewsInSubview:(id)fp12;
- (void)toggleNonOpaqueViews;
- (void)addOutlinesToFrameViewFromSubview:(id)fp8;
- (void)toggleOutlines;
- (void)forceReloadOfView;
- (void)forceSetNeedsLayout;
- (void)forceSetNeedsDisplay;
- (void)logRecursiveDescriptionForView:(id)fp8;
- (void)logRecursiveDescriptionForCurrentView;
- (void)showTemporaryStringInStatusBar:(id)fp8;
- (void)updateViews;
- (void)updateStatusBar;
- (void)updateFrameView;
- (void)removeNameForObject:(id)fp8;
- (void)removeNamesForViewsInView:(id)fp8;
- (id)nameForObject:(id)fp8;
- (void)setName:(id)fp8 forObject:(id)fp12 accessedWithSelf:(BOOL)fp16;
- (void)logCodeForCurrentViewChanges;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (void)textViewDidChangeSelection:(id)fp8;
- (void)statusBarTapped;
- (void)selectView:(id)fp8;
- (void)touchAtPoint:(struct CGPoint)fp8;
- (void)invokeIntrospector;
- (void)setKeyboardBindingsOn:(BOOL)fp8;
- (void)setInvokeGestureRecognizer:(id)fp8;
- (void)resetInputTextView;
- (void)takeFirstResponder;
- (void)start;

@end

