/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface DecoratedView : _AVAudioSessionCategoryPlayback
{
}

- (void)drawRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 decorators:(id)fp(null);
- (id)initWithFrame:(struct CGRect)fp8 decorator:(id)fp(null);

@end

