/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface DefaultSHKConfigurator : _AVAudioSessionCategoryPlayback
{
}

- (id)popOverSourceRect;
- (id)textMessageToRecipients;
- (id)facebookURLShareDescription;
- (id)facebookURLSharePictureURI;
- (id)sharedWithSignature;
- (id)mailJPGQuality;
- (id)isMailHTML;
- (id)mailToRecipients;
- (id)printOutputType;
- (id)allowAutoShare;
- (id)allowOffline;
- (id)authPrefix;
- (id)favsPrefixKey;
- (id)maxFavCount;
- (id)isUsingCocoaPods;
- (Class)SHKFormControllerSubclass;
- (Class)SHKShareMenuCellSubclass;
- (Class)SHKShareMenuSubclass;
- (Class)SHKActionSheetSubclass;
- (id)autoOrderFavoriteSharers;
- (id)defaultFavoriteFileSharers;
- (id)defaultFavoriteSharersForMimeType:(id)fp8;
- (id)defaultFavoriteSharersForFile:(id)fp8;
- (id)defaultFavoriteTextSharers;
- (id)defaultFavoriteImageSharers;
- (id)defaultFavoriteURLSharers;
- (id)showActionSheetMoreButton;
- (id)sharersPlistName;
- (id)shareMenuAlphabeticalOrder;
- (id)modalTransitionStyleForController:(id)fp8;
- (id)modalPresentationStyleForController:(id)fp8;
- (id)formBackgroundColor;
- (id)formFontColor;
- (id)barTintForView:(id)fp8;
- (id)barStyle;
- (BOOL)dropboxShouldOverwriteExistedFile;
- (id)dropboxRootFolder;
- (id)bufferClientSecret;
- (id)bufferClientID;
- (id)dropboxAppSecret;
- (id)dropboxAppKey;
- (id)youTubeSecret;
- (id)youTubeConsumerKey;
- (id)instagramLetterBoxColor;
- (id)instagramLetterBoxImages;
- (id)plurkCallbackURL;
- (id)plurkAppSecret;
- (id)plurkAppKey;
- (id)hatenaScope;
- (id)hatenaSecret;
- (id)hatenaConsumerKey;
- (id)tumblrCallbackUrl;
- (id)tumblrSecret;
- (id)tumblrConsumerKey;
- (id)foursquareV2RedirectURI;
- (id)foursquareV2ClientId;
- (id)readabilityUseXAuth;
- (id)readabilitySecret;
- (id)readabilityConsumerKey;
- (id)linkedInCallbackUrl;
- (id)linkedInSecret;
- (id)linkedInConsumerKey;
- (id)bitLyKey;
- (id)bitLyLogin;
- (id)flickrCallbackUrl;
- (id)flickrSecretKey;
- (id)flickrConsumerKey;
- (id)evernoteSecret;
- (id)evernoteConsumerKey;
- (id)evernoteHost;
- (id)twitterUsername;
- (id)twitterUseXAuth;
- (id)twitterCallbackUrl;
- (id)twitterSecret;
- (id)twitterConsumerKey;
- (id)forcePreIOS5TwitterAccess;
- (id)diigoKey;
- (id)pocketConsumerKey;
- (id)googlePlusClientId;
- (id)forcePreIOS6FacebookPosting;
- (id)facebookReadPermissions;
- (id)facebookWritePermissions;
- (id)facebookLocalAppId;
- (id)facebookAppId;
- (id)vkontakteAppId;
- (id)appURL;
- (id)appName;

@end

