/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SubredditNode.h"

@interface DiscoverySubredditNode : SubredditNode
{
    id _onThumbnailTap;
}

+ (Class)cellClass;
- (void)setOnThumbnailTap:(id)fp(null);
- (id)onThumbnailTap;
- (void).cxx_destruct;

@end

