/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "OptionNode.h"

@class DiscoveryCategory;

@interface DiscoveryCategoryNode : OptionNode
{
    DiscoveryCategory *_category;
}

+ (Class)cellClass;
+ (id)categoryNodeForCategory:(id)fp8;
- (void)setCategory:(id)fp8;
- (id)category;
- (void).cxx_destruct;

@end

