/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMgetNoteSearchText_args : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__authenticationToken;
    NSString *__guid;
    BOOL __noteOnly;
    BOOL __tokenizeForIndexing;
    BOOL __authenticationToken_isset;
    BOOL __guid_isset;
    BOOL __noteOnly_isset;
    BOOL __tokenizeForIndexing_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetTokenizeForIndexing;
- (BOOL)tokenizeForIndexingIsSet;
- (void)setTokenizeForIndexing:(BOOL)fp8;
- (BOOL)tokenizeForIndexing;
- (void)unsetNoteOnly;
- (BOOL)noteOnlyIsSet;
- (void)setNoteOnly:(BOOL)fp8;
- (BOOL)noteOnly;
- (void)unsetGuid;
- (BOOL)guidIsSet;
- (void)setGuid:(id)fp8;
- (id)guid;
- (void)unsetAuthenticationToken;
- (BOOL)authenticationTokenIsSet;
- (void)setAuthenticationToken:(id)fp8;
- (id)authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithAuthenticationToken:(id)fp8 guid:(id)fp12 noteOnly:(BOOL)fp16 tokenizeForIndexing:(BOOL)fp20;
- (id)init;

@end

