/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol EDAMNoteStore <NSObject>
- (id)findRelated:(id)fp8 query:(id)fp12 resultSpec:(id)fp16;
- (id)authenticateToSharedNote:(id)fp8 noteKey:(id)fp12 authenticationToken:(id)fp16;
- (void)stopSharingNote:(id)fp8 guid:(id)fp12;
- (id)shareNote:(id)fp8 guid:(id)fp12;
- (void)emailNote:(id)fp8 parameters:(id)fp12;
- (id)getSharedNotebookByAuth:(id)fp8;
- (id)authenticateToSharedNotebook:(id)fp8 authenticationToken:(id)fp12;
- (int)expungeLinkedNotebook:(id)fp8 guid:(id)fp12;
- (id)listLinkedNotebooks:(id)fp8;
- (int)updateLinkedNotebook:(id)fp8 linkedNotebook:(id)fp12;
- (id)createLinkedNotebook:(id)fp8 linkedNotebook:(id)fp12;
- (int)expungeSharedNotebooks:(id)fp8 sharedNotebookIds:(id)fp12;
- (id)listSharedNotebooks:(id)fp8;
- (int)sendMessageToSharedNotebookMembers:(id)fp8 notebookGuid:(id)fp12 messageText:(id)fp16 recipients:(id)fp20;
- (int)setSharedNotebookRecipientSettings:(id)fp8 sharedNotebookId:(long long)fp12 recipientSettings:(id)fp20;
- (int)updateSharedNotebook:(id)fp8 sharedNotebook:(id)fp12;
- (id)createSharedNotebook:(id)fp8 sharedNotebook:(id)fp12;
- (id)getPublicNotebook:(int)fp8 publicUri:(id)fp12;
- (id)getResourceAttributes:(id)fp8 guid:(id)fp12;
- (id)getResourceAlternateData:(id)fp8 guid:(id)fp12;
- (id)getResourceRecognition:(id)fp8 guid:(id)fp12;
- (id)getResourceByHash:(id)fp8 noteGuid:(id)fp12 contentHash:(id)fp16 withData:(BOOL)fp20 withRecognition:(BOOL)fp24 withAlternateData:(BOOL)fp28;
- (id)getResourceData:(id)fp8 guid:(id)fp12;
- (int)updateResource:(id)fp8 resource:(id)fp12;
- (int)unsetResourceApplicationDataEntry:(id)fp8 guid:(id)fp12 key:(id)fp16;
- (int)setResourceApplicationDataEntry:(id)fp8 guid:(id)fp12 key:(id)fp16 value:(id)fp20;
- (id)getResourceApplicationDataEntry:(id)fp8 guid:(id)fp12 key:(id)fp16;
- (id)getResourceApplicationData:(id)fp8 guid:(id)fp12;
- (id)getResource:(id)fp8 guid:(id)fp12 withData:(BOOL)fp16 withRecognition:(BOOL)fp20 withAttributes:(BOOL)fp24 withAlternateData:(BOOL)fp28;
- (id)getNoteVersion:(id)fp8 noteGuid:(id)fp12 updateSequenceNum:(int)fp16 withResourcesData:(BOOL)fp20 withResourcesRecognition:(BOOL)fp24 withResourcesAlternateData:(BOOL)fp28;
- (id)listNoteVersions:(id)fp8 noteGuid:(id)fp12;
- (id)copyNote:(id)fp8 noteGuid:(id)fp12 toNotebookGuid:(id)fp16;
- (int)expungeInactiveNotes:(id)fp8;
- (int)expungeNotes:(id)fp8 noteGuids:(id)fp12;
- (int)expungeNote:(id)fp8 guid:(id)fp12;
- (int)deleteNote:(id)fp8 guid:(id)fp12;
- (id)updateNote:(id)fp8 note:(id)fp12;
- (id)createNote:(id)fp8 note:(id)fp12;
- (id)getNoteTagNames:(id)fp8 guid:(id)fp12;
- (id)getResourceSearchText:(id)fp8 guid:(id)fp12;
- (id)getNoteSearchText:(id)fp8 guid:(id)fp12 noteOnly:(BOOL)fp16 tokenizeForIndexing:(BOOL)fp20;
- (id)getNoteContent:(id)fp8 guid:(id)fp12;
- (int)unsetNoteApplicationDataEntry:(id)fp8 guid:(id)fp12 key:(id)fp16;
- (int)setNoteApplicationDataEntry:(id)fp8 guid:(id)fp12 key:(id)fp16 value:(id)fp20;
- (id)getNoteApplicationDataEntry:(id)fp8 guid:(id)fp12 key:(id)fp16;
- (id)getNoteApplicationData:(id)fp8 guid:(id)fp12;
- (id)getNote:(id)fp8 guid:(id)fp12 withContent:(BOOL)fp16 withResourcesData:(BOOL)fp20 withResourcesRecognition:(BOOL)fp24 withResourcesAlternateData:(BOOL)fp28;
- (id)findNoteCounts:(id)fp8 filter:(id)fp12 withTrash:(BOOL)fp16;
- (id)findNotesMetadata:(id)fp8 filter:(id)fp12 offset:(int)fp16 maxNotes:(int)fp20 resultSpec:(id)fp24;
- (int)findNoteOffset:(id)fp8 filter:(id)fp12 guid:(id)fp16;
- (id)findNotes:(id)fp8 filter:(id)fp12 offset:(int)fp16 maxNotes:(int)fp20;
- (int)expungeSearch:(id)fp8 guid:(id)fp12;
- (int)updateSearch:(id)fp8 search:(id)fp12;
- (id)createSearch:(id)fp8 search:(id)fp12;
- (id)getSearch:(id)fp8 guid:(id)fp12;
- (id)listSearches:(id)fp8;
- (int)expungeTag:(id)fp8 guid:(id)fp12;
- (void)untagAll:(id)fp8 guid:(id)fp12;
- (int)updateTag:(id)fp8 tag:(id)fp12;
- (id)createTag:(id)fp8 tag:(id)fp12;
- (id)getTag:(id)fp8 guid:(id)fp12;
- (id)listTagsByNotebook:(id)fp8 notebookGuid:(id)fp12;
- (id)listTags:(id)fp8;
- (int)expungeNotebook:(id)fp8 guid:(id)fp12;
- (int)updateNotebook:(id)fp8 notebook:(id)fp12;
- (id)createNotebook:(id)fp8 notebook:(id)fp12;
- (id)getDefaultNotebook:(id)fp8;
- (id)getNotebook:(id)fp8 guid:(id)fp12;
- (id)listNotebooks:(id)fp8;
- (id)getLinkedNotebookSyncChunk:(id)fp8 linkedNotebook:(id)fp12 afterUSN:(int)fp16 maxEntries:(int)fp20 fullSyncOnly:(BOOL)fp24;
- (id)getLinkedNotebookSyncState:(id)fp8 linkedNotebook:(id)fp12;
- (id)getFilteredSyncChunk:(id)fp8 afterUSN:(int)fp12 maxEntries:(int)fp16 filter:(id)fp20;
- (id)getSyncChunk:(id)fp8 afterUSN:(int)fp12 maxEntries:(int)fp16 fullSyncOnly:(BOOL)fp20;
- (id)getSyncStateWithMetrics:(id)fp8 clientMetrics:(id)fp12;
- (id)getSyncState:(id)fp8;
@end

