/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMNotebookDescriptor : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__guid;
    NSString *__notebookDisplayName;
    NSString *__contactName;
    BOOL __hasSharedNotebook;
    int __joinedUserCount;
    BOOL __guid_isset;
    BOOL __notebookDisplayName_isset;
    BOOL __contactName_isset;
    BOOL __hasSharedNotebook_isset;
    BOOL __joinedUserCount_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetJoinedUserCount;
- (BOOL)joinedUserCountIsSet;
- (void)setJoinedUserCount:(int)fp8;
- (int)joinedUserCount;
- (void)unsetHasSharedNotebook;
- (BOOL)hasSharedNotebookIsSet;
- (void)setHasSharedNotebook:(BOOL)fp8;
- (BOOL)hasSharedNotebook;
- (void)unsetContactName;
- (BOOL)contactNameIsSet;
- (void)setContactName:(id)fp8;
- (id)contactName;
- (void)unsetNotebookDisplayName;
- (BOOL)notebookDisplayNameIsSet;
- (void)setNotebookDisplayName:(id)fp8;
- (id)notebookDisplayName;
- (void)unsetGuid;
- (BOOL)guidIsSet;
- (void)setGuid:(id)fp8;
- (id)guid;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithGuid:(id)fp8 notebookDisplayName:(id)fp12 contactName:(id)fp16 hasSharedNotebook:(BOOL)fp20 joinedUserCount:(int)fp24;
- (id)init;

@end

