/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSMutableDictionary;

@interface EDAMNoteCollectionCounts : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSMutableDictionary *__notebookCounts;
    NSMutableDictionary *__tagCounts;
    int __trashCount;
    BOOL __notebookCounts_isset;
    BOOL __tagCounts_isset;
    BOOL __trashCount_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetTrashCount;
- (BOOL)trashCountIsSet;
- (void)setTrashCount:(int)fp8;
- (int)trashCount;
- (void)unsetTagCounts;
- (BOOL)tagCountsIsSet;
- (void)setTagCounts:(id)fp8;
- (id)tagCounts;
- (void)unsetNotebookCounts;
- (BOOL)notebookCountsIsSet;
- (void)setNotebookCounts:(id)fp8;
- (id)notebookCounts;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithNotebookCounts:(id)fp8 tagCounts:(id)fp12 trashCount:(int)fp16;
- (id)init;

@end

