/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMcheckVersion_args : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__clientName;
    short __edamVersionMajor;
    short __edamVersionMinor;
    BOOL __clientName_isset;
    BOOL __edamVersionMajor_isset;
    BOOL __edamVersionMinor_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetEdamVersionMinor;
- (BOOL)edamVersionMinorIsSet;
- (void)setEdamVersionMinor:(short)fp8;
- (short)edamVersionMinor;
- (void)unsetEdamVersionMajor;
- (BOOL)edamVersionMajorIsSet;
- (void)setEdamVersionMajor:(short)fp8;
- (short)edamVersionMajor;
- (void)unsetClientName;
- (BOOL)clientNameIsSet;
- (void)setClientName:(id)fp8;
- (id)clientName;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithClientName:(id)fp8 edamVersionMajor:(short)fp12 edamVersionMinor:(short)fp16;
- (id)init;

@end

