/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMgetNoteVersion_args : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__authenticationToken;
    NSString *__noteGuid;
    int __updateSequenceNum;
    BOOL __withResourcesData;
    BOOL __withResourcesRecognition;
    BOOL __withResourcesAlternateData;
    BOOL __authenticationToken_isset;
    BOOL __noteGuid_isset;
    BOOL __updateSequenceNum_isset;
    BOOL __withResourcesData_isset;
    BOOL __withResourcesRecognition_isset;
    BOOL __withResourcesAlternateData_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetWithResourcesAlternateData;
- (BOOL)withResourcesAlternateDataIsSet;
- (void)setWithResourcesAlternateData:(BOOL)fp8;
- (BOOL)withResourcesAlternateData;
- (void)unsetWithResourcesRecognition;
- (BOOL)withResourcesRecognitionIsSet;
- (void)setWithResourcesRecognition:(BOOL)fp8;
- (BOOL)withResourcesRecognition;
- (void)unsetWithResourcesData;
- (BOOL)withResourcesDataIsSet;
- (void)setWithResourcesData:(BOOL)fp8;
- (BOOL)withResourcesData;
- (void)unsetUpdateSequenceNum;
- (BOOL)updateSequenceNumIsSet;
- (void)setUpdateSequenceNum:(int)fp8;
- (int)updateSequenceNum;
- (void)unsetNoteGuid;
- (BOOL)noteGuidIsSet;
- (void)setNoteGuid:(id)fp8;
- (id)noteGuid;
- (void)unsetAuthenticationToken;
- (BOOL)authenticationTokenIsSet;
- (void)setAuthenticationToken:(id)fp8;
- (id)authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithAuthenticationToken:(id)fp8 noteGuid:(id)fp12 updateSequenceNum:(int)fp16 withResourcesData:(BOOL)fp20 withResourcesRecognition:(BOOL)fp24 withResourcesAlternateData:(BOOL)fp28;
- (id)init;

@end

