/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class EDAMLazyMap, NSMutableDictionary, NSString;

@interface EDAMNoteAttributes : _AVAudioSessionCategoryPlayback <NSCoding>
{
    long long __subjectDate;
    double __latitude;
    double __longitude;
    double __altitude;
    NSString *__author;
    NSString *__source;
    NSString *__sourceURL;
    NSString *__sourceApplication;
    long long __shareDate;
    long long __reminderOrder;
    long long __reminderDoneTime;
    long long __reminderTime;
    NSString *__placeName;
    NSString *__contentClass;
    EDAMLazyMap *__applicationData;
    NSString *__lastEditedBy;
    NSMutableDictionary *__classifications;
    int __creatorId;
    int __lastEditorId;
    BOOL __subjectDate_isset;
    BOOL __latitude_isset;
    BOOL __longitude_isset;
    BOOL __altitude_isset;
    BOOL __author_isset;
    BOOL __source_isset;
    BOOL __sourceURL_isset;
    BOOL __sourceApplication_isset;
    BOOL __shareDate_isset;
    BOOL __reminderOrder_isset;
    BOOL __reminderDoneTime_isset;
    BOOL __reminderTime_isset;
    BOOL __placeName_isset;
    BOOL __contentClass_isset;
    BOOL __applicationData_isset;
    BOOL __lastEditedBy_isset;
    BOOL __classifications_isset;
    BOOL __creatorId_isset;
    BOOL __lastEditorId_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetLastEditorId;
- (BOOL)lastEditorIdIsSet;
- (void)setLastEditorId:(int)fp8;
- (int)lastEditorId;
- (void)unsetCreatorId;
- (BOOL)creatorIdIsSet;
- (void)setCreatorId:(int)fp8;
- (int)creatorId;
- (void)unsetClassifications;
- (BOOL)classificationsIsSet;
- (void)setClassifications:(id)fp8;
- (id)classifications;
- (void)unsetLastEditedBy;
- (BOOL)lastEditedByIsSet;
- (void)setLastEditedBy:(id)fp8;
- (id)lastEditedBy;
- (void)unsetApplicationData;
- (BOOL)applicationDataIsSet;
- (void)setApplicationData:(id)fp8;
- (id)applicationData;
- (void)unsetContentClass;
- (BOOL)contentClassIsSet;
- (void)setContentClass:(id)fp8;
- (id)contentClass;
- (void)unsetPlaceName;
- (BOOL)placeNameIsSet;
- (void)setPlaceName:(id)fp8;
- (id)placeName;
- (void)unsetReminderTime;
- (BOOL)reminderTimeIsSet;
- (void)setReminderTime:(long long)fp8;
- (long long)reminderTime;
- (void)unsetReminderDoneTime;
- (BOOL)reminderDoneTimeIsSet;
- (void)setReminderDoneTime:(long long)fp8;
- (long long)reminderDoneTime;
- (void)unsetReminderOrder;
- (BOOL)reminderOrderIsSet;
- (void)setReminderOrder:(long long)fp8;
- (long long)reminderOrder;
- (void)unsetShareDate;
- (BOOL)shareDateIsSet;
- (void)setShareDate:(long long)fp8;
- (long long)shareDate;
- (void)unsetSourceApplication;
- (BOOL)sourceApplicationIsSet;
- (void)setSourceApplication:(id)fp8;
- (id)sourceApplication;
- (void)unsetSourceURL;
- (BOOL)sourceURLIsSet;
- (void)setSourceURL:(id)fp8;
- (id)sourceURL;
- (void)unsetSource;
- (BOOL)sourceIsSet;
- (void)setSource:(id)fp8;
- (id)source;
- (void)unsetAuthor;
- (BOOL)authorIsSet;
- (void)setAuthor:(id)fp8;
- (id)author;
- (void)unsetAltitude;
- (BOOL)altitudeIsSet;
- (void)setAltitude:(double)fp8;
- (double)altitude;
- (void)unsetLongitude;
- (BOOL)longitudeIsSet;
- (void)setLongitude:(double)fp8;
- (double)longitude;
- (void)unsetLatitude;
- (BOOL)latitudeIsSet;
- (void)setLatitude:(double)fp8;
- (double)latitude;
- (void)unsetSubjectDate;
- (BOOL)subjectDateIsSet;
- (void)setSubjectDate:(long long)fp8;
- (long long)subjectDate;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithSubjectDate:(long long)fp8 latitude:(double)fp16 longitude:(double)fp24 altitude:(double)fp32 author:(id)fp40 source:(id)fp44 sourceURL:(id)fp48 sourceApplication:(id)fp52 shareDate:(long long)fp56 reminderOrder:(long long)fp64 reminderDoneTime:(long long)fp72 reminderTime:(long long)fp80 placeName:(id)fp88 contentClass:(id)fp92 applicationData:(id)fp96 lastEditedBy:(id)fp100 classifications:(id)fp104 creatorId:(int)fp108 lastEditorId:(int)fp112;
- (id)init;

@end

