/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMTag : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__guid;
    NSString *__name;
    NSString *__parentGuid;
    int __updateSequenceNum;
    BOOL __guid_isset;
    BOOL __name_isset;
    BOOL __parentGuid_isset;
    BOOL __updateSequenceNum_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetUpdateSequenceNum;
- (BOOL)updateSequenceNumIsSet;
- (void)setUpdateSequenceNum:(int)fp8;
- (int)updateSequenceNum;
- (void)unsetParentGuid;
- (BOOL)parentGuidIsSet;
- (void)setParentGuid:(id)fp8;
- (id)parentGuid;
- (void)unsetName;
- (BOOL)nameIsSet;
- (void)setName:(id)fp8;
- (id)name;
- (void)unsetGuid;
- (BOOL)guidIsSet;
- (void)setGuid:(id)fp8;
- (id)guid;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithGuid:(id)fp8 name:(id)fp12 parentGuid:(id)fp16 updateSequenceNum:(int)fp20;
- (id)init;

@end

