/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMPremiumInfo : _AVAudioSessionCategoryPlayback <NSCoding>
{
    long long __currentTime;
    BOOL __premium;
    BOOL __premiumRecurring;
    long long __premiumExpirationDate;
    BOOL __premiumExtendable;
    BOOL __premiumPending;
    BOOL __premiumCancellationPending;
    BOOL __canPurchaseUploadAllowance;
    NSString *__sponsoredGroupName;
    int __sponsoredGroupRole;
    BOOL __premiumUpgradable;
    BOOL __currentTime_isset;
    BOOL __premium_isset;
    BOOL __premiumRecurring_isset;
    BOOL __premiumExpirationDate_isset;
    BOOL __premiumExtendable_isset;
    BOOL __premiumPending_isset;
    BOOL __premiumCancellationPending_isset;
    BOOL __canPurchaseUploadAllowance_isset;
    BOOL __sponsoredGroupName_isset;
    BOOL __sponsoredGroupRole_isset;
    BOOL __premiumUpgradable_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetPremiumUpgradable;
- (BOOL)premiumUpgradableIsSet;
- (void)setPremiumUpgradable:(BOOL)fp8;
- (BOOL)premiumUpgradable;
- (void)unsetSponsoredGroupRole;
- (BOOL)sponsoredGroupRoleIsSet;
- (void)setSponsoredGroupRole:(int)fp8;
- (int)sponsoredGroupRole;
- (void)unsetSponsoredGroupName;
- (BOOL)sponsoredGroupNameIsSet;
- (void)setSponsoredGroupName:(id)fp8;
- (id)sponsoredGroupName;
- (void)unsetCanPurchaseUploadAllowance;
- (BOOL)canPurchaseUploadAllowanceIsSet;
- (void)setCanPurchaseUploadAllowance:(BOOL)fp8;
- (BOOL)canPurchaseUploadAllowance;
- (void)unsetPremiumCancellationPending;
- (BOOL)premiumCancellationPendingIsSet;
- (void)setPremiumCancellationPending:(BOOL)fp8;
- (BOOL)premiumCancellationPending;
- (void)unsetPremiumPending;
- (BOOL)premiumPendingIsSet;
- (void)setPremiumPending:(BOOL)fp8;
- (BOOL)premiumPending;
- (void)unsetPremiumExtendable;
- (BOOL)premiumExtendableIsSet;
- (void)setPremiumExtendable:(BOOL)fp8;
- (BOOL)premiumExtendable;
- (void)unsetPremiumExpirationDate;
- (BOOL)premiumExpirationDateIsSet;
- (void)setPremiumExpirationDate:(long long)fp8;
- (long long)premiumExpirationDate;
- (void)unsetPremiumRecurring;
- (BOOL)premiumRecurringIsSet;
- (void)setPremiumRecurring:(BOOL)fp8;
- (BOOL)premiumRecurring;
- (void)unsetPremium;
- (BOOL)premiumIsSet;
- (void)setPremium:(BOOL)fp8;
- (BOOL)premium;
- (void)unsetCurrentTime;
- (BOOL)currentTimeIsSet;
- (void)setCurrentTime:(long long)fp8;
- (long long)currentTime;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithCurrentTime:(long long)fp8 premium:(BOOL)fp16 premiumRecurring:(BOOL)fp20 premiumExpirationDate:(long long)fp24 premiumExtendable:(BOOL)fp32 premiumPending:(BOOL)fp36 premiumCancellationPending:(BOOL)fp40 canPurchaseUploadAllowance:(BOOL)fp44 sponsoredGroupName:(id)fp48 sponsoredGroupRole:(int)fp52 premiumUpgradable:(BOOL)fp56;
- (id)init;

@end

