/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class EDAMSavedSearchScope, NSString;

@interface EDAMSavedSearch : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__guid;
    NSString *__name;
    NSString *__query;
    int __format;
    int __updateSequenceNum;
    EDAMSavedSearchScope *__scope;
    BOOL __guid_isset;
    BOOL __name_isset;
    BOOL __query_isset;
    BOOL __format_isset;
    BOOL __updateSequenceNum_isset;
    BOOL __scope_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetScope;
- (BOOL)scopeIsSet;
- (void)setScope:(id)fp8;
- (id)scope;
- (void)unsetUpdateSequenceNum;
- (BOOL)updateSequenceNumIsSet;
- (void)setUpdateSequenceNum:(int)fp8;
- (int)updateSequenceNum;
- (void)unsetFormat;
- (BOOL)formatIsSet;
- (void)setFormat:(int)fp8;
- (int)format;
- (void)unsetQuery;
- (BOOL)queryIsSet;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)unsetName;
- (BOOL)nameIsSet;
- (void)setName:(id)fp8;
- (id)name;
- (void)unsetGuid;
- (BOOL)guidIsSet;
- (void)setGuid:(id)fp8;
- (id)guid;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithGuid:(id)fp8 name:(id)fp12 query:(id)fp16 format:(int)fp20 updateSequenceNum:(int)fp24 scope:(id)fp28;
- (id)init;

@end

