/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMNoteVersionId : _AVAudioSessionCategoryPlayback <NSCoding>
{
    int __updateSequenceNum;
    long long __updated;
    long long __saved;
    NSString *__title;
    BOOL __updateSequenceNum_isset;
    BOOL __updated_isset;
    BOOL __saved_isset;
    BOOL __title_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetTitle;
- (BOOL)titleIsSet;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)unsetSaved;
- (BOOL)savedIsSet;
- (void)setSaved:(long long)fp8;
- (long long)saved;
- (void)unsetUpdated;
- (BOOL)updatedIsSet;
- (void)setUpdated:(long long)fp8;
- (long long)updated;
- (void)unsetUpdateSequenceNum;
- (BOOL)updateSequenceNumIsSet;
- (void)setUpdateSequenceNum:(int)fp8;
- (int)updateSequenceNum;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithUpdateSequenceNum:(int)fp8 updated:(long long)fp12 saved:(long long)fp20 title:(id)fp28;
- (id)init;

@end

