/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMUserException : _AVAudioSessionCategoryPlayback <NSCoding>
{
    int __errorCode;
    NSString *__parameter;
    BOOL __errorCode_isset;
    BOOL __parameter_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetParameter;
- (BOOL)parameterIsSet;
- (void)setParameter:(id)fp8;
- (id)parameter;
- (void)unsetErrorCode;
- (BOOL)errorCodeIsSet;
- (void)setErrorCode:(int)fp8;
- (int)errorCode;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithErrorCode:(int)fp8 parameter:(id)fp12;
- (id)init;

@end

