/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMSyncChunkFilter : _AVAudioSessionCategoryPlayback <NSCoding>
{
    BOOL __includeNotes;
    BOOL __includeNoteResources;
    BOOL __includeNoteAttributes;
    BOOL __includeNotebooks;
    BOOL __includeTags;
    BOOL __includeSearches;
    BOOL __includeResources;
    BOOL __includeLinkedNotebooks;
    BOOL __includeExpunged;
    BOOL __includeNoteApplicationDataFullMap;
    BOOL __includeResourceApplicationDataFullMap;
    BOOL __includeNoteResourceApplicationDataFullMap;
    NSString *__requireNoteContentClass;
    BOOL __includeNotes_isset;
    BOOL __includeNoteResources_isset;
    BOOL __includeNoteAttributes_isset;
    BOOL __includeNotebooks_isset;
    BOOL __includeTags_isset;
    BOOL __includeSearches_isset;
    BOOL __includeResources_isset;
    BOOL __includeLinkedNotebooks_isset;
    BOOL __includeExpunged_isset;
    BOOL __includeNoteApplicationDataFullMap_isset;
    BOOL __includeResourceApplicationDataFullMap_isset;
    BOOL __includeNoteResourceApplicationDataFullMap_isset;
    BOOL __requireNoteContentClass_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetRequireNoteContentClass;
- (BOOL)requireNoteContentClassIsSet;
- (void)setRequireNoteContentClass:(id)fp8;
- (id)requireNoteContentClass;
- (void)unsetIncludeNoteResourceApplicationDataFullMap;
- (BOOL)includeNoteResourceApplicationDataFullMapIsSet;
- (void)setIncludeNoteResourceApplicationDataFullMap:(BOOL)fp8;
- (BOOL)includeNoteResourceApplicationDataFullMap;
- (void)unsetIncludeResourceApplicationDataFullMap;
- (BOOL)includeResourceApplicationDataFullMapIsSet;
- (void)setIncludeResourceApplicationDataFullMap:(BOOL)fp8;
- (BOOL)includeResourceApplicationDataFullMap;
- (void)unsetIncludeNoteApplicationDataFullMap;
- (BOOL)includeNoteApplicationDataFullMapIsSet;
- (void)setIncludeNoteApplicationDataFullMap:(BOOL)fp8;
- (BOOL)includeNoteApplicationDataFullMap;
- (void)unsetIncludeExpunged;
- (BOOL)includeExpungedIsSet;
- (void)setIncludeExpunged:(BOOL)fp8;
- (BOOL)includeExpunged;
- (void)unsetIncludeLinkedNotebooks;
- (BOOL)includeLinkedNotebooksIsSet;
- (void)setIncludeLinkedNotebooks:(BOOL)fp8;
- (BOOL)includeLinkedNotebooks;
- (void)unsetIncludeResources;
- (BOOL)includeResourcesIsSet;
- (void)setIncludeResources:(BOOL)fp8;
- (BOOL)includeResources;
- (void)unsetIncludeSearches;
- (BOOL)includeSearchesIsSet;
- (void)setIncludeSearches:(BOOL)fp8;
- (BOOL)includeSearches;
- (void)unsetIncludeTags;
- (BOOL)includeTagsIsSet;
- (void)setIncludeTags:(BOOL)fp8;
- (BOOL)includeTags;
- (void)unsetIncludeNotebooks;
- (BOOL)includeNotebooksIsSet;
- (void)setIncludeNotebooks:(BOOL)fp8;
- (BOOL)includeNotebooks;
- (void)unsetIncludeNoteAttributes;
- (BOOL)includeNoteAttributesIsSet;
- (void)setIncludeNoteAttributes:(BOOL)fp8;
- (BOOL)includeNoteAttributes;
- (void)unsetIncludeNoteResources;
- (BOOL)includeNoteResourcesIsSet;
- (void)setIncludeNoteResources:(BOOL)fp8;
- (BOOL)includeNoteResources;
- (void)unsetIncludeNotes;
- (BOOL)includeNotesIsSet;
- (void)setIncludeNotes:(BOOL)fp8;
- (BOOL)includeNotes;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithIncludeNotes:(BOOL)fp8 includeNoteResources:(BOOL)fp12 includeNoteAttributes:(BOOL)fp16 includeNotebooks:(BOOL)fp20 includeTags:(BOOL)fp24 includeSearches:(BOOL)fp28 includeResources:(BOOL)fp32 includeLinkedNotebooks:(BOOL)fp36 includeExpunged:(BOOL)fp40 includeNoteApplicationDataFullMap:(BOOL)fp44 includeResourceApplicationDataFullMap:(BOOL)fp48 includeNoteResourceApplicationDataFullMap:(BOOL)fp52 requireNoteContentClass:(id)fp56;
- (id)init;

@end

