/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@interface EDAMSavedSearchScope : _AVAudioSessionCategoryPlayback <NSCoding>
{
    BOOL __includeAccount;
    BOOL __includePersonalLinkedNotebooks;
    BOOL __includeBusinessLinkedNotebooks;
    BOOL __includeAccount_isset;
    BOOL __includePersonalLinkedNotebooks_isset;
    BOOL __includeBusinessLinkedNotebooks_isset;
}

- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetIncludeBusinessLinkedNotebooks;
- (BOOL)includeBusinessLinkedNotebooksIsSet;
- (void)setIncludeBusinessLinkedNotebooks:(BOOL)fp8;
- (BOOL)includeBusinessLinkedNotebooks;
- (void)unsetIncludePersonalLinkedNotebooks;
- (BOOL)includePersonalLinkedNotebooksIsSet;
- (void)setIncludePersonalLinkedNotebooks:(BOOL)fp8;
- (BOOL)includePersonalLinkedNotebooks;
- (void)unsetIncludeAccount;
- (BOOL)includeAccountIsSet;
- (void)setIncludeAccount:(BOOL)fp8;
- (BOOL)includeAccount;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithIncludeAccount:(BOOL)fp8 includePersonalLinkedNotebooks:(BOOL)fp12 includeBusinessLinkedNotebooks:(BOOL)fp16;
- (id)init;

@end

