/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMPublicUserInfo : _AVAudioSessionCategoryPlayback <NSCoding>
{
    int __userId;
    NSString *__shardId;
    int __privilege;
    NSString *__username;
    NSString *__noteStoreUrl;
    NSString *__webApiUrlPrefix;
    BOOL __userId_isset;
    BOOL __shardId_isset;
    BOOL __privilege_isset;
    BOOL __username_isset;
    BOOL __noteStoreUrl_isset;
    BOOL __webApiUrlPrefix_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetWebApiUrlPrefix;
- (BOOL)webApiUrlPrefixIsSet;
- (void)setWebApiUrlPrefix:(id)fp8;
- (id)webApiUrlPrefix;
- (void)unsetNoteStoreUrl;
- (BOOL)noteStoreUrlIsSet;
- (void)setNoteStoreUrl:(id)fp8;
- (id)noteStoreUrl;
- (void)unsetUsername;
- (BOOL)usernameIsSet;
- (void)setUsername:(id)fp8;
- (id)username;
- (void)unsetPrivilege;
- (BOOL)privilegeIsSet;
- (void)setPrivilege:(int)fp8;
- (int)privilege;
- (void)unsetShardId;
- (BOOL)shardIdIsSet;
- (void)setShardId:(id)fp8;
- (id)shardId;
- (void)unsetUserId;
- (BOOL)userIdIsSet;
- (void)setUserId:(int)fp8;
- (int)userId;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithUserId:(int)fp8 shardId:(id)fp12 privilege:(int)fp16 username:(id)fp20 noteStoreUrl:(id)fp24 webApiUrlPrefix:(id)fp28;
- (id)init;

@end

