/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface EDAMNoteFilter : _AVAudioSessionCategoryPlayback <NSCoding>
{
    int __order;
    BOOL __ascending;
    NSString *__words;
    NSString *__notebookGuid;
    NSMutableArray *__tagGuids;
    NSString *__timeZone;
    BOOL __inactive;
    NSString *__emphasized;
    BOOL __order_isset;
    BOOL __ascending_isset;
    BOOL __words_isset;
    BOOL __notebookGuid_isset;
    BOOL __tagGuids_isset;
    BOOL __timeZone_isset;
    BOOL __inactive_isset;
    BOOL __emphasized_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetEmphasized;
- (BOOL)emphasizedIsSet;
- (void)setEmphasized:(id)fp8;
- (id)emphasized;
- (void)unsetInactive;
- (BOOL)inactiveIsSet;
- (void)setInactive:(BOOL)fp8;
- (BOOL)inactive;
- (void)unsetTimeZone;
- (BOOL)timeZoneIsSet;
- (void)setTimeZone:(id)fp8;
- (id)timeZone;
- (void)unsetTagGuids;
- (BOOL)tagGuidsIsSet;
- (void)setTagGuids:(id)fp8;
- (id)tagGuids;
- (void)unsetNotebookGuid;
- (BOOL)notebookGuidIsSet;
- (void)setNotebookGuid:(id)fp8;
- (id)notebookGuid;
- (void)unsetWords;
- (BOOL)wordsIsSet;
- (void)setWords:(id)fp8;
- (id)words;
- (void)unsetAscending;
- (BOOL)ascendingIsSet;
- (void)setAscending:(BOOL)fp8;
- (BOOL)ascending;
- (void)unsetOrder;
- (BOOL)orderIsSet;
- (void)setOrder:(int)fp8;
- (int)order;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithOrder:(int)fp8 ascending:(BOOL)fp12 words:(id)fp16 notebookGuid:(id)fp20 tagGuids:(id)fp24 timeZone:(id)fp28 inactive:(BOOL)fp32 emphasized:(id)fp36;
- (id)init;

@end

