/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "TProcessor-Protocol.h"

@class NSDictionary;

@interface EDAMUserStoreProcessor : _AVAudioSessionCategoryPlayback <TProcessor>
{
    id <EDAMUserStore> mService;
    NSDictionary *mMethodMap;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)process_getNoteStoreUrl_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_getPremiumInfo_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_getPublicUserInfo_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_getUser_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_refreshAuthentication_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_authenticateToBusiness_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_revokeLongSession_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_completeTwoFactorAuthentication_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_authenticateLongSession_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_authenticate_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_getBootstrapInfo_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (void)process_checkVersion_withSequenceID:(int)fp8 inProtocol:(id)fp12 outProtocol:(id)fp16;
- (BOOL)processOnInputProtocol:(id)fp8 outputProtocol:(id)fp12;
- (id)service;
- (id)initWithUserStore:(id)fp8;

@end

