/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMNotFoundException : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__identifier;
    NSString *__key;
    BOOL __identifier_isset;
    BOOL __key_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetKey;
- (BOOL)keyIsSet;
- (void)setKey:(id)fp8;
- (id)key;
- (void)unsetIdentifier;
- (BOOL)identifierIsSet;
- (void)setIdentifier:(id)fp8;
- (id)identifier;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithIdentifier:(id)fp8 key:(id)fp12;
- (id)init;

@end

