/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@interface EDAMClientUsageMetrics : _AVAudioSessionCategoryPlayback <NSCoding>
{
    int __sessions;
    BOOL __sessions_isset;
}

- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetSessions;
- (BOOL)sessionsIsSet;
- (void)setSessions:(int)fp8;
- (int)sessions;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithSessions:(int)fp8;
- (id)init;

@end

