/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class EDAMBootstrapSettings, NSString;

@interface EDAMBootstrapProfile : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *__name;
    EDAMBootstrapSettings *__settings;
    BOOL __name_isset;
    BOOL __settings_isset;
}

- (void).cxx_destruct;
- (id)description;
- (void)write:(id)fp8;
- (void)read:(id)fp8;
- (void)unsetSettings;
- (BOOL)settingsIsSet;
- (void)setSettings:(id)fp8;
- (id)settings;
- (void)unsetName;
- (BOOL)nameIsSet;
- (void)setName:(id)fp8;
- (id)name;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithName:(id)fp8 settings:(id)fp12;
- (id)init;

@end

