/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class CALayer, UIActivityIndicatorView, UILabel;

@interface EGORefreshTableHeaderView : _AVAudioSessionCategoryPlayback
{
    UILabel *lastUpdatedLabel;
    UILabel *statusLabel;
    CALayer *arrowImage;
    UIActivityIndicatorView *activityView;
    int _state;
}

- (int)state;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setState:(int)fp8;
- (void)setCurrentDate;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

