/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface ENApplicationBridge : _AVAudioSessionCategoryPlayback
{
}

+ (id)newApplicationBridge;
- (void)performRequest:(id)fp8;
- (void)performRequest:(id)fp8 withCallbackURL:(id)fp12;
- (void)_performIphoneRequest:(id)fp8 withCallbackURL:(id)fp12;
- (id)evernoteDownloadURL;
- (BOOL)isEvernoteInstalled;
- (id)_iphoneBaseURL;

@end

