/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDictionary, NSString, NSURL;

@interface ENGCOAuth : _AVAudioSessionCategoryPlayback
{
    NSDictionary *__parameters;
    NSString *__method;
    NSURL *__url;
    NSString *_signatureSecret;
    NSDictionary *_OAuthParameters;
}

+ (id)URLRequestForPath:(id)fp8 POSTParameters:(id)fp12 host:(id)fp16 consumerKey:(id)fp20 consumerSecret:(id)fp24 accessToken:(id)fp28 tokenSecret:(id)fp32;
+ (id)URLRequestForPath:(id)fp8 GETParameters:(id)fp12 scheme:(id)fp16 host:(id)fp20 consumerKey:(id)fp24 consumerSecret:(id)fp28 accessToken:(id)fp32 tokenSecret:(id)fp36;
+ (id)URLRequestForPath:(id)fp8 GETParameters:(id)fp12 host:(id)fp16 consumerKey:(id)fp20 consumerSecret:(id)fp24 accessToken:(id)fp28 tokenSecret:(id)fp32;
+ (id)queryStringFromParameters:(id)fp8;
+ (id)timeStamp;
+ (id)nonce;
+ (void)setHTTPShouldHandleCookies:(BOOL)fp8;
+ (void)setTimeStampOffset:(long)fp8;
+ (void)setUserAgent:(id)fp8;
- (void)setOAuthParameters:(id)fp8;
- (id)OAuthParameters;
- (void)setSignatureSecret:(id)fp8;
- (id)signatureSecret;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)setHTTPMethod:(id)fp8;
- (id)HTTPMethod;
- (void)setRequestParameters:(id)fp8;
- (id)requestParameters;
- (void).cxx_destruct;
- (id)signatureBase;
- (id)signature;
- (id)authorizationHeader;
- (id)request;
- (id)initWithConsumerKey:(id)fp8 consumerSecret:(id)fp12 accessToken:(id)fp16 tokenSecret:(id)fp20;

@end

