/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "ENApplicationRequest-Protocol.h"

@class NSString;

@interface ENLinkNotebookRequest : _AVAudioSessionCategoryPlayback <ENApplicationRequest>
{
    NSString *_shareKey;
    NSString *_shardID;
    NSString *_name;
    NSString *_ownerName;
}

+ (id)linkNotebookRequestWithName:(id)fp8 ownerName:(id)fp12 shareKey:(id)fp16 shardID:(id)fp20;
- (void)setName:(id)fp8;
- (id)name;
- (void)setShardID:(id)fp8;
- (id)shardID;
- (void)setShareKey:(id)fp8;
- (id)shareKey;
- (void)setOwnerName:(id)fp8;
- (id)ownerName;
- (void).cxx_destruct;
- (id)description;
- (id)requestIdentifier;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;

@end

