/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ENOAuthViewControllerDelegate <NSObject>
- (void)oauthViewController:(id)fp8 receivedOAuthCallbackURL:(id)fp12;
- (void)oauthViewController:(id)fp8 didFailWithError:(id)fp12;
- (void)oauthViewControllerDidSwitchProfile:(id)fp8;
- (void)oauthViewControllerDidCancel:(id)fp8;
@end

