/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "ENApplicationRequest-Protocol.h"

@class NSData, NSString;

@interface ENResourceAttachment : _AVAudioSessionCategoryPlayback <ENApplicationRequest>
{
    NSData *mResourceData;
    NSString *mMimeType;
    NSString *mFilename;
    NSString *mFilepath;
}

- (void)setFilepath:(id)fp8;
- (id)filepath;
- (void)setFilename:(id)fp8;
- (id)filename;
- (void)setMimeType:(id)fp8;
- (id)mimeType;
- (void)setResourceData:(id)fp8;
- (id)resourceData;
- (void).cxx_destruct;
- (id)description;
- (id)requestIdentifier;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;

@end

