/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "ENOAuthViewControllerDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class EDAMNoteStoreClient, EDAMUser, EDAMUserStoreClient, ENCredentialStore, ENOAuthViewController, NSArray, NSDate, NSMutableData, NSString, NSURLResponse, UIViewController;

@interface EvernoteSession : _AVAudioSessionCategoryPlayback <ENOAuthViewControllerDelegate, SKStoreProductViewControllerDelegate>
{
    BOOL _isSwitchingInProgress;
    BOOL _isMultitaskLoginDisabled;
    UIViewController *_viewController;
    NSURLResponse *_response;
    NSMutableData *_receivedData;
    ENCredentialStore *_credentialStore;
    NSString *_host;
    NSString *_consumerKey;
    NSString *_consumerSecret;
    NSString *_tokenSecret;
    id _completionHandler;
    struct dispatch_queue_s *_queue;
    id <ENSessionDelegate> _delegate;
    int _state;
    NSArray *_profiles;
    EDAMUser *_businessUser;
    NSString *_currentProfile;
    ENOAuthViewController *_oauthViewController;
    EDAMNoteStoreClient *_noteStoreClient;
    EDAMUserStoreClient *_userStoreClient;
    EDAMNoteStoreClient *_businessNoteStoreClient;
    NSDate *_startDate;
}

+ (BOOL)isTokenExpiredWithError:(id)fp8;
+ (id)parametersFromQueryString:(id)fp8;
+ (id)queryStringFromParameters:(id)fp8;
+ (id)sharedSession;
+ (void)setSharedSessionHost:(id)fp8 consumerKey:(id)fp12 consumerSecret:(id)fp16;
- (void)setStartDate:(id)fp8;
- (id)startDate;
- (void)setBusinessNoteStoreClient:(id)fp8;
- (id)businessNoteStoreClient;
- (void)setUserStoreClient:(id)fp8;
- (id)userStoreClient;
- (void)setNoteStoreClient:(id)fp8;
- (id)noteStoreClient;
- (void)setOauthViewController:(id)fp8;
- (id)oauthViewController;
- (void)setIsMultitaskLoginDisabled:(BOOL)fp8;
- (BOOL)isMultitaskLoginDisabled;
- (void)setIsSwitchingInProgress:(BOOL)fp8;
- (BOOL)isSwitchingInProgress;
- (void)setCurrentProfile:(id)fp8;
- (id)currentProfile;
- (void)setBusinessUser:(id)fp8;
- (id)businessUser;
- (void)setProfiles:(id)fp8;
- (id)profiles;
- (void)setState:(int)fp8;
- (int)state;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (struct dispatch_queue_s *)queue;
- (void)setCompletionHandler:(id)fp(null);
- (id)completionHandler;
- (void)setTokenSecret:(id)fp8;
- (id)tokenSecret;
- (void)setConsumerSecret:(id)fp8;
- (id)consumerSecret;
- (void)setConsumerKey:(id)fp8;
- (id)consumerKey;
- (void)setHost:(id)fp8;
- (id)host;
- (void)setCredentialStore:(id)fp8;
- (id)credentialStore;
- (void)setReceivedData:(id)fp8;
- (id)receivedData;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setViewController:(id)fp8;
- (id)viewController;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)fp8;
- (void)installAppWithId:(int)fp8 withViewController:(id)fp12;
- (void)installSkitchAppUsingViewController:(id)fp8;
- (void)installEvernoteAppUsingViewController:(id)fp8;
- (void)getOAuthTokenForURL:(id)fp8;
- (void)oauthViewController:(id)fp8 receivedOAuthCallbackURL:(id)fp12;
- (void)gotCallbackURL:(id)fp8;
- (BOOL)canHandleSwitchProfileURL:(id)fp8;
- (BOOL)canHandleOpenURL:(id)fp8;
- (void)oauthViewController:(id)fp8 didFailWithError:(id)fp12;
- (void)oauthViewControllerDidSwitchProfile:(id)fp8;
- (void)oauthViewControllerDidCancel:(id)fp8;
- (void)verifyCFBundleURLSchemes;
- (void)updateCurrentBootstrapProfileWithName:(id)fp8;
- (void)switchProfile;
- (void)completeAuthenticationWithError:(id)fp8;
- (void)saveBusinessCredentialsWithEdamUserId:(id)fp8 noteStoreUrl:(id)fp12 webApiUrlPrefix:(id)fp16 authenticationToken:(id)fp20;
- (void)saveCredentialsWithEdamUserId:(id)fp8 noteStoreUrl:(id)fp12 webApiUrlPrefix:(id)fp16 authenticationToken:(id)fp20;
- (void)openOAuthViewControllerWithURL:(id)fp8;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)handleDidBecomeActive;
- (BOOL)handleOpenURL:(id)fp8;
- (id)userAuthorizationURLStringWithParameters:(id)fp8;
- (id)oauthCallback;
- (id)callbackScheme;
- (void)startOauthAuthentication;
- (void)verifyConsumerKeyAndSecret;
- (void)authenticateWithViewController:(id)fp8 completionHandler:(id)fp(null);
- (void)emptyCookieJar;
- (void)clearAllClients;
- (void)logout;
- (BOOL)isEvernoteInstalled;
- (id)connectionWithRequest:(id)fp8;
- (id)noteStoreWithNoteStoreURL:(id)fp8;
- (id)businessNoteStore;
- (id)userStore;
- (id)noteStore;
- (id)webApiUrlPrefix;
- (id)noteStoreUrl;
- (id)userStoreUrl;
- (BOOL)isAuthenticated;
- (id)businessAuthenticationToken;
- (id)authenticationToken;
- (id)credentialsForBusiness;
- (id)credentials;
- (void)commonInit;
- (id)initWithHost:(id)fp8 consumerKey:(id)fp12 consumerSecret:(id)fp16;
- (id)init;
- (void)dealloc;

@end

