/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ENAPI.h"

@interface EvernoteUserStore : ENAPI
{
}

+ (id)userStore;
- (void)revokeLongSessionWithAuthenticationToken:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (void)authenticateToBusinessWithSuccess:(id)fp(null) failure:(void)fp8;
- (void)getNoteStoreUrlWithSuccess:(id)fp(null) failure:(void)fp8;
- (void)getPremiumInfoWithSuccess:(id)fp(null) failure:(void)fp8;
- (void)getPublicUserInfoWithUsername:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (void)getUserWithSuccess:(id)fp(null) failure:(void)fp8;
- (void)getBootstrapInfoWithLocale:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (void)checkVersionWithClientName:(id)fp8 edamVersionMajor:(short)fp12 edamVersionMinor:(short)fp16 success:(id)fp(null) failure:(void)fp20;
- (id)initWithSession:(id)fp8;
- (void)isUserMemberOfBusinessWithSuccess:(id)fp(null) failure:(void)fp8;

@end

