/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMViewOverlay.h"

@class UIImage;

@interface FaviconOverlay : JMViewOverlay
{
    UIImage *_icon;
}

- (void)setIcon:(id)fp8;
- (id)icon;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (void)updateWithUrl:(id)fp8;
- (id)init;

@end

