/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSDate, NSString;

@interface FBAccessTokenData : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *_accessToken;
    NSArray *_permissions;
    NSDate *_expirationDate;
    int _loginType;
    NSDate *_refreshDate;
    NSDate *_permissionsRefreshDate;
}

+ (id)createTokenFromString:(id)fp8 permissions:(id)fp12 expirationDate:(id)fp16 loginType:(int)fp20 refreshDate:(id)fp24 permissionsRefreshDate:(id)fp28;
+ (id)createTokenFromString:(id)fp8 permissions:(id)fp12 expirationDate:(id)fp16 loginType:(int)fp20 refreshDate:(id)fp24;
+ (id)createTokenFromDictionary:(id)fp8;
+ (id)createTokenFromFacebookURL:(id)fp8 appID:(id)fp12 urlSchemeSuffix:(id)fp16;
- (void)setPermissionsRefreshDate:(id)fp8;
- (id)permissionsRefreshDate;
- (void)setRefreshDate:(id)fp8;
- (id)refreshDate;
- (int)loginType;
- (id)expirationDate;
- (void)setPermissions:(id)fp8;
- (id)permissions;
- (id)accessToken;
- (id)description;
- (id)dictionary;
- (BOOL)isEqualToAccessTokenData:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (id)initWithToken:(id)fp8 permissions:(id)fp12 expirationDate:(id)fp16 loginType:(int)fp20 refreshDate:(id)fp24 permissionsRefreshDate:(id)fp28;

@end

