/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class FBAppBridgeTypeToJSONConverter, NSMutableDictionary, NSString;

@interface FBAppBridge : _AVAudioSessionCategoryPlayback
{
    NSMutableDictionary *_pendingAppCalls;
    NSMutableDictionary *_callbacks;
    FBAppBridgeTypeToJSONConverter *_jsonConverter;
    NSString *_appID;
    NSString *_bundleID;
    NSString *_appName;
}

+ (id)errorFromDictionary:(id)fp8;
+ (id)appIconFromBundleInfo:(id)fp8;
+ (id)installedFBNativeAppVersionForMethod:(id)fp8 minVersion:(id)fp12;
+ (id)urlForMethod:(id)fp8 queryParams:(id)fp12 version:(id)fp16;
+ (id)symmetricKeyAndForceRefresh:(BOOL)fp8;
+ (id)sharedInstance;
- (void)setAppName:(id)fp8;
- (id)appName;
- (void)setBundleID:(id)fp8;
- (id)bundleID;
- (void)setAppID:(id)fp8;
- (id)appID;
- (void)setJsonConverter:(id)fp8;
- (id)jsonConverter;
- (void)setCallbacks:(id)fp8;
- (id)callbacks;
- (void)setPendingAppCalls:(id)fp8;
- (id)pendingAppCalls;
- (void)deletePasteboardsForAppCallID:(id)fp8;
- (void)savePasteboardNames:(id)fp8 forAppCallID:(id)fp12;
- (id)dictionaryFromJSONString:(id)fp8;
- (id)jsonStringFromDictionary:(id)fp8;
- (void)stopTrackingCallWithID:(id)fp8;
- (void)trackAppCall:(id)fp8 withCompletionHandler:(id)fp(null);
- (void)addAppMetadataToDictionary:(id)fp8;
- (id)decryptUrlQueryParams:(id)fp8 method:(id)fp12 fallbackHandler:(id)fp(null);
- (BOOL)processResponse:(id)fp8 method:(id)fp12 session:(id)fp16 fallbackHandler:(id)fp(null);
- (void)handleDidBecomeActive;
- (BOOL)handleOpenURL:(id)fp8 sourceApplication:(id)fp12 session:(id)fp16 fallbackHandler:(id)fp(null);
- (void)invoke:(id)fp(null) forFailedAppCall:(void)fp8 withMessage:(id)fp12;
- (void)performDialogAppCall:(id)fp8 version:(id)fp12 session:(id)fp16 completionHandler:(id)fp(null);
- (void)dispatchDialogAppCall:(id)fp8 version:(id)fp12 session:(id)fp16 completionHandler:(id)fp(null);
- (void)dealloc;
- (id)init;

@end

