/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray;

@interface FBAppBridgeTypeToJSONConverter : _AVAudioSessionCategoryPlayback
{
    NSMutableArray *_createdPasteboardNames;
}

+ (id)appBridgeTypeFromJSON:(id)fp8;
- (void)setCreatedPasteboardNames:(id)fp8;
- (id)createdPasteboardNames;
- (id)jsonFromData:(id)fp8 tag:(id)fp12;
- (id)convertedArrayFromArray:(id)fp8 convertingToJSON:(BOOL)fp12;
- (id)convertedDictionaryFromDictionary:(id)fp8 convertingToJSON:(BOOL)fp12;
- (id)convertedObjectFromObject:(id)fp8 convertingToJSON:(BOOL)fp12;
- (id)dictionaryWithAppBridgeTypesFromJSONDictionary:(id)fp8;
- (id)jsonDictionaryFromDictionaryWithAppBridgeTypes:(id)fp8;
- (void)dealloc;

@end

