/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class FBAccessTokenData, FBAppLinkData, FBDialogsData, NSError, NSString;

@interface FBAppCall : _AVAudioSessionCategoryPlayback
{
    NSString *_ID;
    NSError *_error;
    FBDialogsData *_dialogData;
    FBAppLinkData *_appLinkData;
    FBAccessTokenData *_accessTokenData;
}

+ (void)openDeferredAppLink:(id)fp(null);
+ (void)invokeHandler:(id)fp(null) withError:(void)fp8;
+ (BOOL)invokeHandler:(id)fp(null) withAccessToken:(void)fp8 appLinkData:(id)fp12;
+ (BOOL)tryOpenSession:(id)fp8 withAccessToken:(id)fp12;
+ (void)handleDidBecomeActiveWithSession:(id)fp8;
+ (void)handleDidBecomeActive;
+ (BOOL)handleOpenURL:(id)fp8 sourceApplication:(id)fp12 withSession:(id)fp16 fallbackHandler:(id)fp(null);
+ (BOOL)handleOpenURL:(id)fp8 sourceApplication:(id)fp12 withSession:(id)fp16;
+ (BOOL)handleOpenURL:(id)fp8 sourceApplication:(id)fp12 fallbackHandler:(id)fp(null);
+ (BOOL)handleOpenURL:(id)fp8 sourceApplication:(id)fp12;
+ (id)appCallFromURL:(id)fp8;
+ (id)appCallFromApplinkArgs_v2:(id)fp8 applinkArgs:(id)fp12 createTimeUTC:(id)fp16 originalQueryParameters:(id)fp20;
- (void)setAccessTokenData:(id)fp8;
- (id)accessTokenData;
- (void)setAppLinkData:(id)fp8;
- (id)appLinkData;
- (void)setDialogData:(id)fp8;
- (id)dialogData;
- (void)setError:(id)fp8;
- (id)error;
- (void)setID:(id)fp8;
- (id)ID;
- (BOOL)isValid;
- (unsigned int)hash;
- (BOOL)isEqualToAppCall:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithID:(id)fp8 enforceScheme:(BOOL)fp12 appID:(id)fp16 urlSchemeSuffix:(id)fp20;
- (id)init:(BOOL)fp8;
- (id)init;

@end

