/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class FBSession, NSMutableDictionary, NSMutableSet, NSRegularExpression, NSTimer;

@interface FBAppEvents : _AVAudioSessionCategoryPlayback
{
    BOOL _haveOutstandingPersistedData;
    BOOL _appSupportsImplicitLogging;
    BOOL _haveFetchedAppSettings;
    int _flushBehavior;
    FBSession *_lastSessionLoggedTo;
    FBSession *_anonymousSession;
    NSMutableDictionary *_appAuthSessions;
    NSTimer *_flushTimer;
    NSTimer *_attributionIDRecheckTimer;
    int _appSupportsAttributionStatus;
    NSRegularExpression *_eventNameRegex;
    NSMutableSet *_validatedIdentifiers;
}

+ (id)flushReasonToString:(int)fp8;
+ (id)customAudienceThirdPartyIDRequest:(id)fp8;
+ (void)ensureOnMainThread;
+ (id)persistenceFilePath;
+ (void)clearPersistedAppEventData;
+ (id)retrievePersistedAppEventData;
+ (void)persistAppEventsData:(id)fp8;
+ (void)logAndNotify:(id)fp8;
+ (long)unixTimeNow;
+ (id)unaffinitizedSessionFromToken:(id)fp8 appID:(id)fp12;
+ (id)singleton;
+ (void)flush;
+ (void)setFlushBehavior:(int)fp8;
+ (int)flushBehavior;
+ (void)activateApp;
+ (void)setLimitEventUsage:(BOOL)fp8;
+ (BOOL)limitEventUsage;
+ (void)logConversionPixel:(id)fp8 valueOfPixel:(double)fp12 session:(id)fp20;
+ (void)logPurchase:(double)fp8 currency:(id)fp16 parameters:(id)fp20 session:(id)fp24;
+ (void)logPurchase:(double)fp8 currency:(id)fp16 parameters:(id)fp20;
+ (void)logPurchase:(double)fp8 currency:(id)fp16;
+ (void)logImplicitEvent:(id)fp8 valueToSum:(id)fp12 parameters:(id)fp16 session:(id)fp20;
+ (void)logEvent:(id)fp8 valueToSum:(id)fp12 parameters:(id)fp16 session:(id)fp20;
+ (void)logEvent:(id)fp8 valueToSum:(double)fp12 parameters:(id)fp20;
+ (void)logEvent:(id)fp8 parameters:(id)fp12;
+ (void)logEvent:(id)fp8 valueToSum:(double)fp12;
+ (void)logEvent:(id)fp8;
- (void)setValidatedIdentifiers:(id)fp8;
- (id)validatedIdentifiers;
- (void)setEventNameRegex:(id)fp8;
- (id)eventNameRegex;
- (void)setHaveFetchedAppSettings:(BOOL)fp8;
- (BOOL)haveFetchedAppSettings;
- (void)setAppSupportsImplicitLogging:(BOOL)fp8;
- (BOOL)appSupportsImplicitLogging;
- (void)setAppSupportsAttributionStatus:(int)fp8;
- (int)appSupportsAttributionStatus;
- (void)setAttributionIDRecheckTimer:(id)fp8;
- (id)attributionIDRecheckTimer;
- (void)setFlushTimer:(id)fp8;
- (id)flushTimer;
- (void)setAppAuthSessions:(id)fp8;
- (id)appAuthSessions;
- (void)setAnonymousSession:(id)fp8;
- (id)anonymousSession;
- (void)setLastSessionLoggedTo:(id)fp8;
- (id)lastSessionLoggedTo;
- (void)setHaveOutstandingPersistedData:(BOOL)fp8;
- (BOOL)haveOutstandingPersistedData;
- (void)setFlushBehavior:(int)fp8;
- (int)flushBehavior;
- (id)instanceCustomAudienceThirdPartyIDRequest:(id)fp8;
- (void)persistDataIfNotInFlight;
- (void)applicationTerminating;
- (void)applicationMovingFromActiveState;
- (BOOL)updateAppEventsStateWithPersistedData:(id)fp8;
- (void)applicationDidBecomeActive;
- (void)attributionIDRecheckTimerFired:(id)fp8;
- (void)flushTimerFired:(id)fp8;
- (void)handleActivitiesPostCompletion:(id)fp8 loggingEntry:(id)fp12 session:(id)fp16;
- (id)sessionToSendRequestTo:(id)fp8;
- (BOOL)doesSessionHaveUserToken:(id)fp8;
- (void)appendAttributionAndAdvertiserIDs:(id)fp8 session:(id)fp12;
- (void)flushOnMainQueue:(int)fp8 session:(id)fp12;
- (void)flush:(int)fp8 session:(id)fp12;
- (void)instanceFlush:(int)fp8;
- (void)instanceLogEvent:(id)fp8 valueToSum:(id)fp12 parameters:(id)fp16 isImplicitlyLogged:(BOOL)fp20 session:(id)fp24;
- (BOOL)regexValidateIdentifier:(id)fp8;
- (BOOL)validateIdentifier:(id)fp8;
- (id)init;

@end

