/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol FBCacheIndexFileDelegate <NSObject>
- (void)cacheIndex:(id)fp8 deleteFileWithName:(id)fp12;
- (void)cacheIndex:(id)fp8 writeFileWithName:(id)fp12 data:(id)fp16;
@end

