/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "FBCacheIndexFileDelegate-Protocol.h"

@class FBCacheIndex, NSCache, NSObject<OS_dispatch_queue>, NSString;

@interface FBDataDiskCache : _AVAudioSessionCategoryPlayback <FBCacheIndexFileDelegate>
{
    NSCache *_inMemoryCache;
    FBCacheIndex *_cacheIndex;
    NSString *_dataCachePath;
    NSObject<OS_dispatch_queue> *_fileQueue;
}

+ (id)sharedCache;
- (id)fileQueue;
- (void)setDataCachePath:(id)fp8;
- (id)dataCachePath;
- (void)setData:(id)fp8 forURL:(id)fp12;
- (void)removeDataForSession:(id)fp8;
- (void)removeDataForUrl:(id)fp8;
- (id)dataForURL:(id)fp8;
- (BOOL)_doesFileExist:(id)fp8;
- (void)cacheIndex:(id)fp8 deleteFileWithName:(id)fp12;
- (void)cacheIndex:(id)fp8 writeFileWithName:(id)fp12 data:(id)fp16;
- (void)setCacheSizeMemory:(unsigned int)fp8;
- (unsigned int)cacheSizeMemory;
- (void)dealloc;
- (id)init;

@end

