/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface FBDynamicFrameworkLoader : _AVAudioSessionCategoryPlayback
{
}

+ (void)setSqlitePath:(id)fp8;
+ (id)sqlitePath;
+ (void)setFrameworkPathTemplate:(id)fp8;
+ (id)frameworkPathTemplate;
+ (void *)loadSymbol:(id)fp8 withFramework:(id)fp12;
+ (struct __SecRandom *)loadkSecRandomDefault;
+ (id)loadStringConstant:(id)fp8 withFramework:(id)fp12;
+ (Class)loadClass:(id)fp8 withFramework:(id)fp12;

@end

