/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface FBErrorUtility : _AVAudioSessionCategoryPlayback
{
}

+ (id)fberrorForSystemPasswordChange:(id)fp8;
+ (id)fberrorForRetry:(id)fp8;
+ (void)fberrorGetCodeValueForError:(id)fp8 index:(unsigned int)fp12 code:(int *)fp16 subcode:(int *)fp20;
+ (BOOL)fberrorIsErrorFromSystemSession:(id)fp8;
+ (int)fberrorCategoryFromError:(id)fp8 code:(int)fp12 subcode:(int)fp16 returningUserMessage:(id *)fp20 andShouldNotifyUser:(char *)fp24;
+ (id)userMessageForError:(id)fp8;
+ (BOOL)shouldNotifyUserForError:(id)fp8;
+ (int)errorCategoryForError:(id)fp8;

@end

