/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface FBFetchedAppSettings : _AVAudioSessionCategoryPlayback
{
    BOOL _supportsAttribution;
    BOOL _supportsImplicitSdkLogging;
    BOOL _suppressNativeGdp;
    NSString *_serverAppName;
    NSString *_appID;
}

- (void)setAppID:(id)fp8;
- (id)appID;
- (void)setSuppressNativeGdp:(BOOL)fp8;
- (BOOL)suppressNativeGdp;
- (void)setSupportsImplicitSdkLogging:(BOOL)fp8;
- (BOOL)supportsImplicitSdkLogging;
- (void)setSupportsAttribution:(BOOL)fp8;
- (BOOL)supportsAttribution;
- (void)setServerAppName:(id)fp8;
- (id)serverAppName;
- (void)dealloc;
- (id)initWithAppID:(id)fp8;
- (id)init;

@end

