/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBViewController.h"

#import "FBGraphObjectPagingLoaderDelegate-Protocol.h"
#import "FBGraphObjectSelectionChangedDelegate-Protocol.h"
#import "FBGraphObjectViewControllerDelegate-Protocol.h"

@class FBGraphObjectPagingLoader, FBGraphObjectTableDataSource, FBGraphObjectTableSelection, FBSession, NSSet, NSString, UIActivityIndicatorView, UITableView;

@interface FBFriendPickerViewController : FBViewController <FBGraphObjectSelectionChangedDelegate, FBGraphObjectViewControllerDelegate, FBGraphObjectPagingLoaderDelegate>
{
    BOOL _allowsMultipleSelection;
    BOOL _trackActiveSession;
    FBGraphObjectTableDataSource *_dataSource;
    id <FBViewControllerDelegate> _delegate;
    NSSet *_fieldsForRequest;
    FBGraphObjectTableSelection *_selectionManager;
    UIActivityIndicatorView *_spinner;
    UITableView *_tableView;
    NSString *_userID;
    FBGraphObjectPagingLoader *_loader;
    int _sortOrdering;
    int _displayOrdering;
    FBSession *_session;
}

+ (id)requestWithUserID:(id)fp8 fields:(id)fp12 dataSource:(id)fp16 session:(id)fp20;
+ (id)cacheDescriptorWithUserID:(id)fp8 fieldsForRequest:(id)fp12;
+ (id)cacheDescriptor;
- (id)session;
- (void)setTrackActiveSession:(BOOL)fp8;
- (BOOL)trackActiveSession;
- (void)setDisplayOrdering:(int)fp8;
- (int)displayOrdering;
- (void)setSortOrdering:(int)fp8;
- (int)sortOrdering;
- (void)setLoader:(id)fp8;
- (id)loader;
- (void)setUserID:(id)fp8;
- (id)userID;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setSelectionManager:(id)fp8;
- (id)selectionManager;
- (void)setFieldsForRequest:(id)fp8;
- (id)fieldsForRequest;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setDataSource:(id)fp8;
- (id)dataSource;
- (void)pagingLoaderWasCancelled:(id)fp8;
- (void)pagingLoader:(id)fp8 handleError:(id)fp12;
- (void)pagingLoaderDidFinishLoading:(id)fp8;
- (void)pagingLoader:(id)fp8 didLoadData:(id)fp12;
- (void)pagingLoader:(id)fp8 willLoadURL:(id)fp12;
- (void)graphObjectTableDataSource:(id)fp8 customizeTableCell:(id)fp12;
- (id)graphObjectTableDataSource:(id)fp8 pictureUrlOfItem:(id)fp12;
- (id)graphObjectTableDataSource:(id)fp8 titleSuffixOfItem:(id)fp12;
- (id)graphObjectTableDataSource:(id)fp8 titleOfItem:(id)fp12;
- (BOOL)graphObjectTableDataSource:(id)fp8 filterIncludesItem:(id)fp12;
- (void)graphObjectTableSelectionDidChange:(id)fp8;
- (void)logAppEvents:(BOOL)fp8;
- (void)centerAndStartSpinner;
- (void)loadDataSkippingRoundTripIfCached:(id)fp8;
- (id)requestForLoadData;
- (void)clearData;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)removeSessionObserver:(id)fp8;
- (void)addSessionObserver:(id)fp8;
- (void)clearSelection;
- (void)updateView;
- (void)loadData;
- (void)configureUsingCachedDescriptor:(id)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)setSession:(id)fp8;
- (id)selection;
- (void)setItemPicturesEnabled:(BOOL)fp8;
- (BOOL)itemPicturesEnabled;
- (void)setAllowsMultipleSelection:(BOOL)fp8;
- (BOOL)allowsMultipleSelection;
- (void)dealloc;
- (void)initialize;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

