/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"

@class NSArray, NSDictionary, NSMutableSet, NSString, UIImage, UILocalizedIndexedCollation;

@interface FBGraphObjectTableDataSource : _AVAudioSessionCategoryPlayback <UITableViewDataSource>
{
    BOOL _useCollation;
    BOOL _showSections;
    BOOL _itemTitleSuffixEnabled;
    BOOL _itemPicturesEnabled;
    BOOL _itemSubtitleEnabled;
    BOOL _expectingMoreGraphObjects;
    NSArray *_data;
    UIImage *_defaultPicture;
    id <FBGraphObjectViewControllerDelegate> _controllerDelegate;
    NSString *_groupByField;
    NSArray *_indexKeys;
    NSDictionary *_indexMap;
    NSMutableSet *_pendingURLConnections;
    id <FBGraphObjectSelectionQueryDelegate> _selectionDelegate;
    NSArray *_sortDescriptors;
    id <FBGraphObjectDataSourceDataNeededDelegate> _dataNeededDelegate;
    UILocalizedIndexedCollation *_collation;
}

- (void)setCollation:(id)fp8;
- (id)collation;
- (void)setExpectingMoreGraphObjects:(BOOL)fp8;
- (BOOL)expectingMoreGraphObjects;
- (void)setDataNeededDelegate:(id)fp8;
- (id)dataNeededDelegate;
- (void)setSortDescriptors:(id)fp8;
- (id)sortDescriptors;
- (void)setSelectionDelegate:(id)fp8;
- (id)selectionDelegate;
- (void)setPendingURLConnections:(id)fp8;
- (id)pendingURLConnections;
- (void)setItemSubtitleEnabled:(BOOL)fp8;
- (BOOL)itemSubtitleEnabled;
- (void)setItemPicturesEnabled:(BOOL)fp8;
- (BOOL)itemPicturesEnabled;
- (void)setItemTitleSuffixEnabled:(BOOL)fp8;
- (BOOL)itemTitleSuffixEnabled;
- (void)setIndexMap:(id)fp8;
- (id)indexMap;
- (void)setIndexKeys:(id)fp8;
- (id)indexKeys;
- (void)setShowSections:(BOOL)fp8;
- (BOOL)showSections;
- (BOOL)useCollation;
- (void)setGroupByField:(id)fp8;
- (id)groupByField;
- (void)setControllerDelegate:(id)fp8;
- (id)controllerDelegate;
- (void)setDefaultPicture:(id)fp8;
- (id)defaultPicture;
- (void)setData:(id)fp8;
- (id)data;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (id)sectionIndexTitlesForTableView:(id)fp8;
- (int)tableView:(id)fp8 sectionForSectionIndexTitle:(id)fp12 atIndex:(int)fp16;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)addOrRemovePendingConnection:(id)fp8;
- (id)tableView:(id)fp8 imageForItem:(id)fp12;
- (id)sectionItemsForSection:(int)fp8;
- (id)titleForSection:(int)fp8;
- (BOOL)isActivityIndicatorIndexPath:(id)fp8;
- (BOOL)isLastSection:(int)fp8;
- (id)indexPathForItem:(id)fp8;
- (id)itemAtIndexPath:(id)fp8;
- (id)indexKeyOfItem:(id)fp8;
- (id)cellWithTableView:(id)fp8;
- (void)setSortingBySingleField:(id)fp8 ascending:(BOOL)fp12;
- (void)setSortingByFields:(id)fp8 ascending:(BOOL)fp12;
- (BOOL)filterIncludesItem:(id)fp8;
- (void)update;
- (void)cancelPendingRequests;
- (void)bindTableView:(id)fp8;
- (BOOL)hasGraphObjects;
- (void)appendGraphObjects:(id)fp8;
- (void)clearGraphObjects;
- (void)prepareForNewRequest;
- (id)fieldsForRequestIncluding:(id)fp8;
- (void)dealloc;
- (id)init;
- (void)setUseCollation:(BOOL)fp8;

@end

