/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface FBInsights : _AVAudioSessionCategoryPlayback
{
}

+ (void)flush;
+ (void)setFlushBehavior:(int)fp8;
+ (int)flushBehavior;
+ (void)logConversionPixel:(id)fp8 valueOfPixel:(double)fp12 session:(id)fp20;
+ (void)logConversionPixel:(id)fp8 valueOfPixel:(double)fp12;
+ (void)logPurchase:(double)fp8 currency:(id)fp16 parameters:(id)fp20 session:(id)fp24;
+ (void)logPurchase:(double)fp8 currency:(id)fp16 parameters:(id)fp20;
+ (void)logPurchase:(double)fp8 currency:(id)fp16;
+ (void)setAppVersion:(id)fp8;
+ (id)appVersion;

@end

