/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBDialogsParams.h"

@class FBSession, NSArray;

@interface FBLoginDialogParams : FBDialogsParams
{
    BOOL _isRefreshOnly;
    NSArray *_permissions;
    int _writePrivacy;
    FBSession *_session;
}

- (void)setSession:(id)fp8;
- (id)session;
- (void)setIsRefreshOnly:(BOOL)fp8;
- (BOOL)isRefreshOnly;
- (void)setWritePrivacy:(int)fp8;
- (int)writePrivacy;
- (void)setPermissions:(id)fp8;
- (id)permissions;
- (id)appBridgeVersion;
- (id)dictionaryMethodArgs;
- (void)dealloc;

@end

