/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIActionSheetDelegate-Protocol.h"

@class FBRequestConnection, FBSession, NSArray, NSNumber, UIButton, UILabel;

@interface FBLoginView : _AVAudioSessionCategoryPlayback <UIActionSheetDelegate>
{
    id <FBLoginViewDelegate> _delegate;
    UILabel *_label;
    UIButton *_button;
    FBSession *_session;
    FBRequestConnection *_request;
    id <FBGraphUser> _user;
    NSArray *_permissions;
    NSArray *_readPermissions;
    NSArray *_publishPermissions;
    int _defaultAudience;
    NSNumber *_lastObservedStateWasOpen;
    id _sessionStateHandler;
    id _requestHandler;
}

- (void)setRequestHandler:(id)fp(null);
- (id)requestHandler;
- (void)setSessionStateHandler:(id)fp(null);
- (id)sessionStateHandler;
- (void)setLastObservedStateWasOpen:(id)fp8;
- (id)lastObservedStateWasOpen;
- (void)setDefaultAudience:(int)fp8;
- (int)defaultAudience;
- (void)setPublishPermissions:(id)fp8;
- (id)publishPermissions;
- (void)setReadPermissions:(id)fp8;
- (id)readPermissions;
- (void)setPermissions:(id)fp8;
- (id)permissions;
- (void)setUser:(id)fp8;
- (id)user;
- (void)setRequest:(id)fp8;
- (id)request;
- (void)setSession:(id)fp8;
- (id)session;
- (void)setButton:(id)fp8;
- (id)button;
- (void)setLabel:(id)fp8;
- (id)label;
- (id)delegate;
- (void)buttonPressed:(id)fp8;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)handleActiveSessionUnsetNotifications:(id)fp8;
- (void)handleActiveSessionSetNotifications:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)unwireViewForSession;
- (void)wireViewForSession:(id)fp8;
- (void)wireViewForSessionWithoutOpening:(id)fp8;
- (void)informDelegateOfError:(id)fp8;
- (void)informDelegate:(BOOL)fp8;
- (void)fetchMeInfo;
- (void)configureViewForStateLoggedIn:(BOOL)fp8;
- (id)logOutText;
- (id)logInText;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (struct CGSize)intrinsicContentSize;
- (void)initialize;
- (void)initializeBlocks;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithPublishPermissions:(id)fp8 defaultAudience:(int)fp12;
- (id)initWithReadPermissions:(id)fp8;
- (id)initWithPermissions:(id)fp8;
- (id)init;

@end

