/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBDialogsParams.h"

@class NSString;

@interface FBOpenGraphActionShareDialogParams : FBDialogsParams
{
    id <FBOpenGraphAction> _action;
    NSString *_previewPropertyName;
    NSString *_actionType;
}

+ (id)getIdOrUrlFromObject:(id)fp8;
+ (id)getPostedObjectTypeFromObject:(id)fp8;
- (void)setActionType:(id)fp8;
- (id)actionType;
- (void)setPreviewPropertyName:(id)fp8;
- (id)previewPropertyName;
- (void)setAction:(id)fp8;
- (id)action;
- (BOOL)containsUIImages:(id)fp8;
- (id)appBridgeVersion;
- (id)dictionaryMethodArgs;
- (id)flattenGraphObjects:(id)fp8;
- (id)flattenObject:(id)fp8;
- (id)validate;
- (void)dealloc;

@end

