/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBViewController.h"

#import "FBGraphObjectPagingLoaderDelegate-Protocol.h"
#import "FBGraphObjectSelectionChangedDelegate-Protocol.h"
#import "FBGraphObjectViewControllerDelegate-Protocol.h"

@class FBGraphObjectPagingLoader, FBGraphObjectTableDataSource, FBGraphObjectTableSelection, FBSession, NSSet, NSString, NSTimer, UIActivityIndicatorView, UITableView;

@interface FBPlacePickerViewController : FBViewController <FBGraphObjectSelectionChangedDelegate, FBGraphObjectViewControllerDelegate, FBGraphObjectPagingLoaderDelegate>
{
    BOOL _hasSearchTextChangedSinceLastQuery;
    BOOL _trackActiveSession;
    FBGraphObjectTableDataSource *_dataSource;
    id <FBViewControllerDelegate> _delegate;
    NSSet *_fieldsForRequest;
    FBGraphObjectPagingLoader *_loader;
    int _radiusInMeters;
    int _resultsLimit;
    NSString *_searchText;
    NSTimer *_searchTextChangedTimer;
    FBGraphObjectTableSelection *_selectionManager;
    UIActivityIndicatorView *_spinner;
    UITableView *_tableView;
    FBSession *_session;
    CDAnonymousStruct1 _locationCoordinate;
}

+ (id)requestForPlacesSearchAtCoordinate:(CDAnonymousStruct1)fp8 radiusInMeters:(int)fp24 resultsLimit:(int)fp28 searchText:(id)fp32 fields:(id)fp36 datasource:(id)fp40 session:(id)fp44;
+ (id)cacheDescriptorWithLocationCoordinate:(CDAnonymousStruct1)fp8 radiusInMeters:(int)fp24 searchText:(id)fp28 resultsLimit:(int)fp32 fieldsForRequest:(id)fp36;
- (void)setTrackActiveSession:(BOOL)fp8;
- (BOOL)trackActiveSession;
- (id)session;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setSelectionManager:(id)fp8;
- (id)selectionManager;
- (void)setSearchTextChangedTimer:(id)fp8;
- (id)searchTextChangedTimer;
- (void)setSearchText:(id)fp8;
- (id)searchText;
- (void)setResultsLimit:(int)fp8;
- (int)resultsLimit;
- (void)setRadiusInMeters:(int)fp8;
- (int)radiusInMeters;
- (void)setLocationCoordinate:(CDAnonymousStruct1)fp8;
- (CDAnonymousStruct1)locationCoordinate;
- (void)setLoader:(id)fp8;
- (id)loader;
- (void)setFieldsForRequest:(id)fp8;
- (id)fieldsForRequest;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setDataSource:(id)fp8;
- (id)dataSource;
- (void)pagingLoaderWasCancelled:(id)fp8;
- (void)pagingLoader:(id)fp8 handleError:(id)fp12;
- (void)pagingLoaderDidFinishLoading:(id)fp8;
- (void)pagingLoader:(id)fp8 didLoadData:(id)fp12;
- (void)pagingLoader:(id)fp8 willLoadURL:(id)fp12;
- (id)graphObjectTableDataSource:(id)fp8 pictureUrlOfItem:(id)fp12;
- (id)graphObjectTableDataSource:(id)fp8 subtitleOfItem:(id)fp12;
- (id)graphObjectTableDataSource:(id)fp8 titleOfItem:(id)fp12;
- (BOOL)graphObjectTableDataSource:(id)fp8 filterIncludesItem:(id)fp12;
- (void)graphObjectTableSelectionDidChange:(id)fp8;
- (void)logAppEvents:(BOOL)fp8;
- (void)clearData;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)removeSessionObserver:(id)fp8;
- (void)addSessionObserver:(id)fp8;
- (void)centerAndStartSpinner;
- (void)searchTextChangedTimerFired:(id)fp8;
- (id)createSearchTextChangedTimer;
- (void)updateView;
- (void)loadDataPostThrottleSkippingRoundTripIfCached:(id)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)clearSelection;
- (void)configureUsingCachedDescriptor:(id)fp8;
- (void)loadData;
- (void)setSession:(id)fp8;
- (id)selection;
- (void)setItemPicturesEnabled:(BOOL)fp8;
- (BOOL)itemPicturesEnabled;
- (void)dealloc;
- (void)initialize;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

