/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBCacheDescriptor.h"

#import "FBGraphObjectPagingLoaderDelegate-Protocol.h"

@class FBGraphObjectPagingLoader, NSSet, NSString;

@interface FBPlacePickerCacheDescriptor : FBCacheDescriptor <FBGraphObjectPagingLoaderDelegate>
{
    BOOL _hasCompletedFetch;
    int _radiusInMeters;
    int _resultsLimit;
    NSString *_searchText;
    NSSet *_fieldsForRequest;
    FBGraphObjectPagingLoader *_loader;
    CDAnonymousStruct1 _locationCoordinate;
}

- (void)setHasCompletedFetch:(BOOL)fp8;
- (BOOL)hasCompletedFetch;
- (void)setLoader:(id)fp8;
- (id)loader;
- (void)setFieldsForRequest:(id)fp8;
- (id)fieldsForRequest;
- (void)setSearchText:(id)fp8;
- (id)searchText;
- (void)setResultsLimit:(int)fp8;
- (int)resultsLimit;
- (void)setRadiusInMeters:(int)fp8;
- (int)radiusInMeters;
- (void)setLocationCoordinate:(CDAnonymousStruct1)fp8;
- (CDAnonymousStruct1)locationCoordinate;
- (void)pagingLoaderDidFinishLoading:(id)fp8;
- (void)prefetchAndCacheForSession:(id)fp8;
- (void)dealloc;
- (id)initWithLocationCoordinate:(CDAnonymousStruct1)fp8 radiusInMeters:(int)fp24 searchText:(id)fp28 resultsLimit:(int)fp32 fieldsForRequest:(id)fp36;

@end

