/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface FBRequestHandlerFactory : _AVAudioSessionCategoryPlayback
{
}

+ (id)handlerThatReconnects:(SEL)fp4 forRequest:(id)fp(null);
+ (id)handlerThatAlertsUser:(SEL)fp4 forRequest:(id)fp(null);
+ (id)handlerThatRetries:(SEL)fp4 forRequest:(id)fp(null);

@end

