/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class FBSession, NSMutableDictionary, NSString;

@interface FBSessionAuthLogger : _AVAudioSessionCategoryPlayback
{
    NSString *_ID;
    NSMutableDictionary *_extras;
    FBSession *_session;
    NSString *_authMethod;
}

- (void)setAuthMethod:(id)fp8;
- (id)authMethod;
- (void)setSession:(id)fp8;
- (id)session;
- (void)setExtras:(id)fp8;
- (id)extras;
- (void)setID:(id)fp8;
- (id)ID;
- (id)newEventParameters;
- (void)logEndAuthWithResult:(id)fp8 error:(id)fp12;
- (void)logEndAuthMethodWithResult:(id)fp8 error:(id)fp12;
- (void)logStartAuthMethod:(id)fp8;
- (void)logStartAuth;
- (void)logEvent:(id)fp8 result:(id)fp12 error:(id)fp16;
- (void)logEvent:(id)fp8 params:(id)fp12;
- (void)addExtrasForNextEvent:(id)fp8;
- (void)dealloc;
- (id)initWithSession:(id)fp8 ID:(id)fp12 authMethod:(id)fp16;
- (id)initWithSession:(id)fp8;

@end

