/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray, NSMutableDictionary;

@interface FBSessionLoginStrategyParams : _AVAudioSessionCategoryPlayback
{
    BOOL _tryIntegratedAuth;
    BOOL _tryFBAppAuth;
    BOOL _trySafariAuth;
    BOOL _tryFallback;
    BOOL _isReauthorize;
    BOOL _canFetchAppSettings;
    int _defaultAudience;
    NSArray *_permissions;
    NSMutableDictionary *_webParams;
}

- (void)setWebParams:(id)fp8;
- (id)webParams;
- (void)setCanFetchAppSettings:(BOOL)fp8;
- (BOOL)canFetchAppSettings;
- (void)setPermissions:(id)fp8;
- (id)permissions;
- (void)setDefaultAudience:(int)fp8;
- (int)defaultAudience;
- (void)setIsReauthorize:(BOOL)fp8;
- (BOOL)isReauthorize;
- (void)setTryFallback:(BOOL)fp8;
- (BOOL)tryFallback;
- (void)setTrySafariAuth:(BOOL)fp8;
- (BOOL)trySafariAuth;
- (void)setTryFBAppAuth:(BOOL)fp8;
- (BOOL)tryFBAppAuth;
- (void)setTryIntegratedAuth:(BOOL)fp8;
- (BOOL)tryIntegratedAuth;
- (void)dealloc;

@end

