/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class FBTask;

@interface FBTaskCompletionSource : _AVAudioSessionCategoryPlayback
{
    FBTask *_task;
}

+ (id)taskCompletionSource;
- (void)setTask:(id)fp8;
- (id)task;
- (BOOL)trySetCancelled;
- (BOOL)trySetException:(id)fp8;
- (BOOL)trySetError:(id)fp8;
- (BOOL)trySetResult:(id)fp8;
- (void)cancel;
- (void)setException:(id)fp8;
- (void)setError:(id)fp8;
- (void)setResult:(id)fp8;
- (void)dealloc;
- (id)init;

@end

