/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableData, NSURLConnection, NSURLResponse;

@interface FBURLConnection : _AVAudioSessionCategoryPlayback
{
    BOOL _skipRoundtripIfCached;
    NSURLConnection *_connection;
    NSMutableData *_data;
    id _handler;
    unsigned int _loggerSerialNumber;
    unsigned long _requestStartTime;
    NSURLResponse *_response;
}

+ (void)initialize;
- (void)setSkipRoundtripIfCached:(BOOL)fp8;
- (BOOL)skipRoundtripIfCached;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setRequestStartTime:(unsigned long)fp8;
- (unsigned long)requestStartTime;
- (unsigned int)loggerSerialNumber;
- (void)setHandler:(id)fp(null);
- (id)handler;
- (void)setData:(id)fp8;
- (id)data;
- (void)setConnection:(id)fp8;
- (id)connection;
- (id)getCache;
- (BOOL)isCDNURL:(id)fp8;
- (BOOL)shouldShortCircuitRedirectResponse:(id)fp8;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)cancel;
- (void)dealloc;
- (void)logMessage:(id)fp8;
- (void)invokeHandler:(id)fp(null) error:(void)fp8 response:(id)fp12 responseData:(id)fp16;
- (void)logAndInvokeHandler:(id)fp(null) cachedData:(void)fp8 forURL:(id)fp12;
- (void)logAndInvokeHandler:(id)fp(null) response:(void)fp8 responseData:(id)fp12;
- (void)logAndInvokeHandler:(id)fp(null) error:(void)fp8;
- (id)initWithRequest:(id)fp8 skipRoundTripIfCached:(BOOL)fp12 completionHandler:(id)fp(null);
- (id)initWithURL:(id)fp8 completionHandler:(id)fp(null);

@end

