/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBViewController.h"

@class FBProfilePictureView, NSArray, NSBundle, UIButton, UIImageView, UILabel;

@interface FBUserSettingsViewController : FBViewController
{
    BOOL _attemptingLogin;
    FBProfilePictureView *_profilePicture;
    UILabel *_connectedStateLabel;
    id <FBGraphUser> _me;
    UIButton *_loginLogoutButton;
    NSArray *_permissions;
    NSArray *_readPermissions;
    NSArray *_publishPermissions;
    int _defaultAudience;
    UIImageView *_backgroundImageView;
    NSBundle *_bundle;
    id _sessionStateHandler;
    id _requestHandler;
}

- (void)setRequestHandler:(id)fp(null);
- (id)requestHandler;
- (void)setSessionStateHandler:(id)fp(null);
- (id)sessionStateHandler;
- (void)setBundle:(id)fp8;
- (id)bundle;
- (void)setBackgroundImageView:(id)fp8;
- (id)backgroundImageView;
- (void)setAttemptingLogin:(BOOL)fp8;
- (BOOL)attemptingLogin;
- (void)setDefaultAudience:(int)fp8;
- (int)defaultAudience;
- (void)setPublishPermissions:(id)fp8;
- (id)publishPermissions;
- (void)setReadPermissions:(id)fp8;
- (id)readPermissions;
- (void)setPermissions:(id)fp8;
- (id)permissions;
- (void)setLoginLogoutButton:(id)fp8;
- (id)loginLogoutButton;
- (void)setMe:(id)fp8;
- (id)me;
- (void)setConnectedStateLabel:(id)fp8;
- (id)connectedStateLabel;
- (void)setProfilePicture:(id)fp8;
- (id)profilePicture;
- (void)handleActiveSessionStateChanged:(id)fp8;
- (void)loginLogoutButtonPressed:(id)fp8;
- (void)openSession;
- (void)sessionStateChanged:(id)fp8 state:(int)fp12 error:(id)fp16;
- (void)updateControls;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidUnload;
- (void)updateBackgroundImage;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (id)init;
- (void)initializeBlocks;

@end

