/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface FBUtility : _AVAudioSessionCategoryPlayback
{
}

+ (id)dialogBaseURL;
+ (void)deleteFacebookCookies;
+ (BOOL)isSystemAccountStoreAvailable;
+ (BOOL)isMultitaskingSupported;
+ (id)buildFacebookUrlWithPre:(id)fp8 withPost:(id)fp12;
+ (id)buildFacebookUrlWithPre:(id)fp8;
+ (BOOL)isRegisteredURLScheme:(id)fp8;
+ (id)newUUIDString;
+ (BOOL)isRetinaDisplay;
+ (id)simpleJSONDecode:(id)fp8 error:(id *)fp12;
+ (id)simpleJSONDecode:(id)fp8;
+ (id)simpleJSONEncode:(id)fp8 error:(id *)fp12 writingOptions:(unsigned int)fp16;
+ (id)simpleJSONEncode:(id)fp8;
+ (void)updateParametersWithEventUsageLimitsAndBundleInfo:(id)fp8;
+ (int)advertisingTrackingStatus;
+ (id)advertiserID;
+ (id)attributionID;
+ (void)callTheFetchAppSettingsCallback:(id)fp(null);
+ (BOOL)isFetchedFBAppSettingsStale;
+ (id)fetchedAppSettings;
+ (void)fetchAppSettings:(id)fp8 callback:(id)fp(null);
+ (id)addBasicInfoPermission:(id)fp8;
+ (BOOL)areAllPermissionsReadPermissions:(id)fp8;
+ (BOOL)isPublishPermission:(id)fp8;
+ (BOOL)isFacebookBundleIdentifier:(id)fp8;
+ (id)localizedStringForKey:(id)fp8 withDefault:(id)fp12 inBundle:(id)fp16;
+ (id)localizedStringForKey:(id)fp8 withDefault:(id)fp12;
+ (id)facebookSDKBundle;
+ (id)expirationDateFromExpirationTimeIntervalString:(id)fp8;
+ (id)expirationDateFromExpirationUnixTimeString:(id)fp8;
+ (id)stringAppBaseUrlFromAppId:(id)fp8 urlSchemeSuffix:(id)fp12;
+ (id)stringFBIDFromObject:(id)fp8;
+ (void)centerView:(id)fp8 tableView:(id)fp12;
+ (id)graphObjectInArray:(id)fp8 withSameIDAs:(id)fp12;
+ (double)randomTimeInterval:(double)fp8 withMaxValue:(double)fp16;
+ (unsigned long)currentTimeInMilliseconds;
+ (id)stringByURLEncodingString:(id)fp8;
+ (id)stringByURLDecodingString:(id)fp8;
+ (id)stringBySerializingQueryParameters:(id)fp8;
+ (id)dictionaryByParsingURLQueryPart:(id)fp8;
+ (id)queryParamsDictionaryFromFBURL:(id)fp8;

@end

