/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABOutlineViewController.h"

@class SubredditFolder, UserSubredditPreferences;

@interface FoldersViewController : ABOutlineViewController
{
    BOOL _ranOnComplete;
    UserSubredditPreferences *_subredditPrefs;
    SubredditFolder *_renamingFolder;
    id _onComplete;
}

+ (id)navControllerWithSubredditPreferences:(id)fp8 onComplete:(id)fp(null);
- (void)setRanOnComplete:(BOOL)fp8;
- (BOOL)ranOnComplete;
- (void)setOnComplete:(id)fp(null);
- (id)onComplete;
- (void)setRenamingFolder:(id)fp8;
- (id)renamingFolder;
- (void)setSubredditPrefs:(id)fp8;
- (id)subredditPrefs;
- (void).cxx_destruct;
- (struct CGSize)contentSizeForViewInPopover;
- (void)closeFolderEditor;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)generateNodes;
- (void)animateFolderChanges;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithSubredditPreferences:(id)fp8 onComplete:(id)fp(null);
- (void)tableView:(id)fp8 moveRowAtIndexPath:(id)fp12 toIndexPath:(id)fp16;
- (id)tableView:(id)fp8 targetIndexPathForMoveFromRowAtIndexPath:(id)fp12 toProposedIndexPath:(id)fp16;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (BOOL)tableView:(id)fp8 canMoveRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 shouldIndentWhileEditingRowAtIndexPath:(id)fp12;

@end

