/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GalleryViewController.h"

@interface GalleryViewController_iPad : GalleryViewController
{
}

+ (void)fixStatusBarOverlapping;
- (void)viewDidAppear:(BOOL)fp8;
- (BOOL)hidesStatusBarAndNavigationBarWhenPresented;
- (void)showCommentsForPost:(id)fp8;
- (void)viewDidLoad;
- (void)dismissAfterHidingStatusBar;
- (void)dismiss;
- (void)loadView;

@end

