/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SyncHandler.h"

@interface GroupSyncHandler : SyncHandler
{
}

- (void)finishedProcessingRemoteMerge;
- (id)mergeChangeFromLocalObject:(id)fp8 remoteObject:(id)fp12;
- (id)mergedFolder:(id)fp8 withFolder:(id)fp12 basedOnChangeLog:(id)fp16;
- (id)mergedFolderForIdent:(id)fp8 local:(id)fp12 remote:(id)fp16 basedOnChangeLog:(id)fp20;
- (id)mergedSubfolderListWithLocal:(id)fp8 remote:(id)fp12 basedOnChangeLog:(id)fp16;
- (BOOL)subredditList:(id)fp8 containsSubredditWithUrl:(id)fp12;
- (BOOL)folderList:(id)fp8 containsFolderWithIdent:(id)fp12;
- (BOOL)shouldRemoveFolder:(id)fp8 basedOnChangeLog:(id)fp12;
- (BOOL)shouldRemoveSubreddit:(id)fp8 fromFolder:(id)fp12 basedOnChangeLog:(id)fp16;
- (int)lastReorderActionByBasedOnChangeLog:(id)fp8;
- (int)lastModifiedByForFolder:(id)fp8 basedOnChangeLog:(id)fp12;
- (int)lastModifiedByForSubreddit:(id)fp8 basedOnChangeLog:(id)fp12;
- (id)mergedChangeLogWithLocal:(id)fp8 remote:(id)fp12;
- (BOOL)changeLog:(id)fp8 containsChangeRecord:(id)fp12;
- (BOOL)requiresSyncing:(id)fp8 remoteObject:(id)fp12;
- (void)finishedSendingToCloudAfterUserDefaultsChange;
- (BOOL)shouldSendToCloudOnUserDefaultsChange;
- (id)keyToMonitor;

@end

