/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol iCarouselDataSource <NSObject>
- (id)carousel:(id)fp8 viewForItemAtIndex:(unsigned int)fp12;
- (unsigned int)numberOfItemsInCarousel:(id)fp8;
@end

