/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMViewOverlay.h"

@class InlineImageNode;

@interface InlineImageOverlay : JMViewOverlay
{
    InlineImageNode *_node;
}

+ (void)precacheImageForNode:(id)fp8 constrainedToWidth:(float)fp12;
+ (float)heightForInlinePreviewForNode:(id)fp8 constrainedToWidth:(float)fp12;
- (void)setNode:(id)fp8;
- (id)node;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (id)fetchInlineImageOnComplete:(id)fp(null);
- (void)grabInlineImage;
- (void)updateForNode:(id)fp8;

@end

