/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMTableNode.h"

@class NSString;

@interface ItemSelectorManualEntryNode : JMTableNode
{
    NSString *placeholder_;
    NSString *enteredString_;
}

+ (id)nodeWithPlaceholder:(id)fp8;
+ (SEL)selectedAction;
+ (Class)cellClass;
- (void)setEnteredString:(id)fp8;
- (id)enteredString;
- (void)setPlaceholder:(id)fp8;
- (id)placeholder;
- (void).cxx_destruct;

@end

