/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMContentOptimizer.h"

@interface JMAlbumContentOptimizer : JMContentOptimizer
{
}

+ (id)extractPageTitleFromHTML:(id)fp8;
+ (id)extractGalleryImagesWithoutCaptionsOrDescriptionsFromHTML:(id)fp8;
+ (id)extractGalleryImagesWithCaptionsAndDescriptionsFromHTML:(id)fp8;
+ (BOOL)canHandleOptimizationForURL:(id)fp8;
- (id)contentTypeIdentifier;
- (void)didRetrieveGalleryItems:(id)fp8 albumTitle:(id)fp12;
- (void)fetchGalleryItems;
- (void)loadView;
- (id)initWithURL:(id)fp8;

@end

