/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMAlbumContentOptimizer.h"

#import "JMGalleryPagingViewDelegate-Protocol.h"

@class JMGalleryPagingView, NSMutableArray, NSString, UILabel;

@interface JMAlbumContentOptimizer_iPhone : JMAlbumContentOptimizer <JMGalleryPagingViewDelegate>
{
    BOOL _i_albumViewNeedsLayout;
    NSMutableArray *_pagedViewCache;
    NSMutableArray *_galleryItems;
    JMGalleryPagingView *_pagingView;
    UILabel *_captionLabel;
    UILabel *_pageLabel;
    NSString *_frameObservationToken;
    struct CGSize _i_lastFrameSize;
}

- (void)setFrameObservationToken:(id)fp8;
- (id)frameObservationToken;
- (void)setI_lastFrameSize:(struct CGSize)fp8;
- (struct CGSize)i_lastFrameSize;
- (void)setI_albumViewNeedsLayout:(BOOL)fp8;
- (BOOL)i_albumViewNeedsLayout;
- (void)setPageLabel:(id)fp8;
- (id)pageLabel;
- (void)setCaptionLabel:(id)fp8;
- (id)captionLabel;
- (void)setPagingView:(id)fp8;
- (id)pagingView;
- (void)setGalleryItems:(id)fp8;
- (id)galleryItems;
- (void)setPagedViewCache:(id)fp8;
- (id)pagedViewCache;
- (void).cxx_destruct;
- (void)willUnloadView;
- (void)layoutAlbumViewAnimated:(BOOL)fp8;
- (void)setAlbumViewNeedsLayout;
- (void)pagingViewDidFinishScrollAnimation:(id)fp8;
- (void)pagingViewDidStartScrollAnimation:(id)fp8;
- (void)pagingViewNeedsMoreResults:(id)fp8;
- (void)pagingView:(id)fp8 didScrollToPage:(unsigned int)fp12;
- (id)pagingView:(id)fp8 contentViewForPage:(unsigned int)fp12;
- (unsigned int)numberOfPagesForPagingView:(id)fp8;
- (id)dequeuePagedViewFromCache;
- (void)buildPagedViewCache;
- (void)didRetrieveGalleryItems:(id)fp8 albumTitle:(id)fp12;
- (void)didSingleTap;
- (void)loadView;

@end

