/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol JMCarouselViewDelegate <NSObject>
- (void)carouselViewDidFinishAnimating:(id)fp8;
- (void)carouselViewDidBeginAnimating:(id)fp8;
- (void)carouselView:(id)fp8 didHideItemAtIndex:(unsigned int)fp12;
- (void)carouselView:(id)fp8 didShowItemAtIndex:(unsigned int)fp12;
- (void)carouselView:(id)fp8 didSelectItemAtIndex:(unsigned int)fp12;
- (BOOL)carouselViewShouldWrap:(id)fp8;
- (struct CGSize)carouselViewGridSize:(id)fp8;
@end

