/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol JMCarouselTrackViewDelegate <NSObject>
- (unsigned int)carouselTrackViewNumberOfItems:(id)fp8;
- (struct CGSize)carouselTrackGridSize:(id)fp8;
- (BOOL)carouselTrackViewShouldWrap:(id)fp8;
- (id)carouselTrackView:(id)fp8 placeholderContentViewForItemAtIndex:(unsigned int)fp12 replacingExistingContentView:(id)fp16;
- (id)carouselTrackView:(id)fp8 contentViewForItemAtIndex:(unsigned int)fp12 replacingExistingContentView:(id)fp16;
@end

