/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIScrollViewDelegate-Protocol.h"

@class JMCarouselView;

@interface JMCarouselScrollView : _AVAudioSessionCategoryPlayback <UIScrollViewDelegate>
{
    JMCarouselView *_parentCarouselView;
    id _onDidScroll;
    id _snapOffsetNearestToContentOffsetAction;
    float _preScrollXOffset;
    int _scrollState;
}

- (void)setScrollState:(int)fp8;
- (int)scrollState;
- (void)setPreScrollXOffset:(float)fp8;
- (float)preScrollXOffset;
- (void)setSnapOffsetNearestToContentOffsetAction:(id)fp(null);
- (id)snapOffsetNearestToContentOffsetAction;
- (void)setOnDidScroll:(id)fp(null);
- (id)onDidScroll;
- (void)setParentCarouselView:(id)fp8;
- (id)parentCarouselView;
- (void).cxx_destruct;
- (float)jm_xOffset;
- (void)setJm_xOffset:(float)fp8;
- (void)setXOffset:(float)fp8 animated:(BOOL)fp12;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)scrollViewWillBeginDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)handleDidScroll;
- (BOOL)allowingTouchesOnScrollView;
- (void)didTap:(id)fp8;
- (BOOL)offsetFallsOutsideOfScrollBoundaries:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

