/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMSliderComponent.h"

@class UIActivityIndicatorView;

@interface JMCenterView : JMSliderComponent
{
    UIActivityIndicatorView *activityView_;
    struct CGPoint touchStartPoint_;
}

+ (id)sliderButtonForSlider:(id)fp8 withTitle:(id)fp12;
- (void)setActivityView:(id)fp8;
- (id)activityView;
- (void)setTouchStartPoint:(struct CGPoint)fp8;
- (struct CGPoint)touchStartPoint;
- (void).cxx_destruct;
- (id)initForSlider:(id)fp8 withTitle:(id)fp12;
- (void)setLoading:(BOOL)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (struct CGPoint)touchPoint:(id)fp8;
- (struct CGSize)sizeOfButton;
- (void)drawButtonInRect:(struct CGRect)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

