/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class JMOptimalProgressBar, NSObject<JMContentOptimizerDelegate>, NSURL, UIView;

@interface JMContentOptimizer : _AVAudioSessionCategoryPlayback
{
    NSURL *_URL;
    NSObject<JMContentOptimizerDelegate> *_delegate;
    UIView *_i_view;
    JMOptimalProgressBar *_progressView;
}

+ (BOOL)canHandleOptimizationForURL:(id)fp8;
+ (Class)contentOptimizerForURL:(id)fp8;
+ (id)availableOptimizers;
+ (id)optimizerForURL:(id)fp8;
- (void)setProgressView:(id)fp8;
- (id)progressView;
- (void)setI_view:(id)fp8;
- (id)i_view;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setURL:(id)fp8;
- (id)URL;
- (void).cxx_destruct;
- (BOOL)hasSettings;
- (void)showSettings;
- (BOOL)disablesOptimalSwitchOnFailure;
- (id)contentTypeIdentifier;
- (void)willLayoutView;
- (void)willUnloadView;
- (BOOL)isViewLoaded;
- (void)applyThemeSettings;
- (void)recommendAnotherOptimizer:(id)fp8;
- (void)recommendOptimalContentSize:(struct CGSize)fp8;
- (void)optimisationDidSucceed;
- (void)optimisationDidFail;
- (void)optimisationDidProgress:(float)fp8;
- (float)progress;
- (id)view;
- (void)loadView;
- (id)initWithURL:(id)fp8;

@end

