/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImage;

@interface JMDelayedAnimationFrame : _AVAudioSessionCategoryPlayback
{
    UIImage *_decompressedImage;
    int _delay;
}

- (void)setDelay:(int)fp8;
- (int)delay;
- (void)setDecompressedImage:(id)fp8;
- (id)decompressedImage;
- (void).cxx_destruct;

@end

