/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSRecursiveLock, NSString;

@interface JMDiskCache : _AVAudioSessionCategoryPlayback
{
    BOOL _allowPermanentDiskFlush;
    NSString *_cachePath;
    NSRecursiveLock *_lock;
}

+ (id)shared;
- (void)setAllowPermanentDiskFlush:(BOOL)fp8;
- (BOOL)allowPermanentDiskFlush;
- (void)setLock:(id)fp8;
- (id)lock;
- (void)setCachePath:(id)fp8;
- (id)cachePath;
- (void).cxx_destruct;
- (void)removeCachedImageForKey:(id)fp8;
- (id)cachedImageForUrlKey:(id)fp8;
- (void)cacheImage:(id)fp8 forUrlKey:(id)fp12 writeToDisk:(BOOL)fp16;
- (void)removeCachedImageForKey:(id)fp8 permanent:(BOOL)fp12;
- (id)cachedImageForUrlKey:(id)fp8 permanent:(BOOL)fp12;
- (void)cacheImage:(id)fp8 forUrlKey:(id)fp12 writeToDisk:(BOOL)fp16 permanent:(BOOL)fp20;
- (void)writeImageToDisk:(id)fp8 forKey:(id)fp12 permanentStorage:(BOOL)fp16;
- (id)diskImageForKey:(id)fp8 permanentStorage:(BOOL)fp12;
- (id)diskDataForKey:(id)fp8 permanentStorage:(BOOL)fp12;
- (void)writeToDiskWithData:(id)fp8 forKey:(id)fp12 permanentStorage:(BOOL)fp16;
- (BOOL)doesFileExistForKey:(id)fp8 permanentStorage:(BOOL)fp12;
- (id)filePathForKey:(id)fp8 permanentStorage:(BOOL)fp12;
- (void)checkCacheOveruse;
- (unsigned int)totalCacheCost;
- (void)addToCacheCostFileSize:(unsigned int)fp8;
- (void)clearCache;
- (void)fastFlushDiskCache;
- (void)clearAllDiskCache;
- (void)clearPermanentDiskCache;
- (void)clearTemporaryDiskCache;
- (void)clearMemoryCache;
- (void)initializeCacheFolder;
- (id)permanentCachePath;
- (id)temporaryCachePath;
- (void)allowPermanentCacheIfNeeded;
- (id)init;

@end

