/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface JMDOMLinkableItem : _AVAudioSessionCategoryPlayback
{
    NSString *_hostName;
    NSString *_xpath;
}

+ (id)deeplinkableItemWithHost:(id)fp8 xpath:(id)fp12;
- (void)setXpath:(id)fp8;
- (id)xpath;
- (void)setHostName:(id)fp8;
- (id)hostName;
- (void).cxx_destruct;

@end

