/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface JMEnumMaps : _AVAudioSessionCategoryPlayback
{
}

+ (id)enumMapMatchingFamily:(id)fp8 withValue:(int)fp12;
+ (void)logMappedEnums;
+ (id)mapsForEnumFamily:(id)fp8;
+ (id)enumMapForEnumName:(id)fp8;
+ (void)initialize;

@end

