/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface JMEnumMap : _AVAudioSessionCategoryPlayback
{
    NSString *_enumFamily;
    NSString *_enumIdent;
    NSString *_title;
    NSString *_shortTitle;
    int _enumValue;
}

- (void)setEnumValue:(int)fp8;
- (int)enumValue;
- (void)setShortTitle:(id)fp8;
- (id)shortTitle;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setEnumIdent:(id)fp8;
- (id)enumIdent;
- (void)setEnumFamily:(id)fp8;
- (id)enumFamily;
- (void).cxx_destruct;
- (id)description;
- (id)initWithFamily:(id)fp8 ident:(id)fp12 enumValue:(int)fp16 title:(id)fp20 shortTitle:(id)fp24;

@end

