/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UILabel;

@interface JMGalleryPreviewButton : _AVAudioSessionCategoryPlayback
{
    UILabel *_nsfwOverlay;
    UIImageView *_thumbnailImageView;
    UIImageView *_thumbnailShadowOverlay;
    UIImageView *_arrowView;
}

- (void)setArrowView:(id)fp8;
- (id)arrowView;
- (void)setThumbnailShadowOverlay:(id)fp8;
- (id)thumbnailShadowOverlay;
- (void)setThumbnailImageView:(id)fp8;
- (id)thumbnailImageView;
- (void)setNsfwOverlay:(id)fp8;
- (id)nsfwOverlay;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)assignArrowToLeft;
- (void)assignArrowToRight;
- (void)setHighlighted:(BOOL)fp8;
- (void)updateForDownloadProgress:(float)fp8;
- (void)setThumbnailImageWithUrl:(id)fp8 nsfw:(BOOL)fp12;
- (void)cancelNetworkConnections;
- (id)initWithFrame:(struct CGRect)fp8;

@end

