/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMImageDecorator.h"

@class NSString;

@interface JMGalleryGridItemDecorator : JMImageDecorator
{
    NSString *_title;
    int _mediaType;
    struct CGSize _containerSize;
}

- (void)setContainerSize:(struct CGSize)fp8;
- (struct CGSize)containerSize;
- (void)setMediaType:(int)fp8;
- (int)mediaType;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)decoratedImageWithImage:(id)fp8;
- (id)decoratorKey;
- (id)initWithGalleryItem:(id)fp8 containerSize:(struct CGSize)fp12;

@end

