/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGallerySettingNode.h"

@class NSString;

@interface JMGallerySettingYesNoOptionNode : JMGallerySettingNode
{
    BOOL _optionValue;
    NSString *_optionDescription;
}

+ (Class)cellClass;
- (void)setOptionDescription:(id)fp8;
- (id)optionDescription;
- (void)setOptionValue:(BOOL)fp8;
- (BOOL)optionValue;
- (void).cxx_destruct;

@end

