/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineNode.h"

@class NSString;

@interface JMGallerySettingNode : JMOutlineNode
{
    BOOL _hidesUnderline;
    BOOL _shouldHighlight;
    NSString *_title;
    NSString *_iconName;
}

+ (Class)cellClass;
- (void)setShouldHighlight:(BOOL)fp8;
- (BOOL)shouldHighlight;
- (void)setHidesUnderline:(BOOL)fp8;
- (BOOL)hidesUnderline;
- (void)setIconName:(id)fp8;
- (id)iconName;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;

@end

