/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class JMGalleryToolbarContentView, UIImageView, UILabel;

@interface JMGalleryToolbar : _AVAudioSessionCategoryPlayback
{
    UIImageView *_bottomPeak;
    UIImageView *_barView;
    UIImageView *_barShadowViewLeft;
    UIImageView *_barShadowViewRight;
    JMGalleryToolbarContentView *_i_contentView;
    UILabel *_captionLabel;
    UILabel *_captionSubtitleLabel;
    UIImageView *_captionUnderlay;
}

- (void)setCaptionUnderlay:(id)fp8;
- (id)captionUnderlay;
- (void)setCaptionSubtitleLabel:(id)fp8;
- (id)captionSubtitleLabel;
- (void)setCaptionLabel:(id)fp8;
- (id)captionLabel;
- (void)setI_contentView:(id)fp8;
- (id)i_contentView;
- (void)setBarShadowViewRight:(id)fp8;
- (id)barShadowViewRight;
- (void)setBarShadowViewLeft:(id)fp8;
- (id)barShadowViewLeft;
- (void)setBarView:(id)fp8;
- (id)barView;
- (void)setBottomPeak:(id)fp8;
- (id)bottomPeak;
- (void).cxx_destruct;
- (id)contentView;
- (id)caption;
- (void)showCaption;
- (void)hideCaption;
- (void)alignToTopOfView:(id)fp8;
- (void)alignToBottomOfView:(id)fp8;
- (void)setToolbarContentView:(id)fp8;
- (void)layoutSubviews;
- (void)setCaptionTitle:(id)fp8 subtitle:(id)fp12;
- (void)appendCaptionOverlay;
- (id)initWithFrame:(struct CGRect)fp8 appendsCaptionOverlay:(BOOL)fp24;

@end

