/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGalleryFocusToolbar.h"

@class JMGalleryToolbarItem;

@interface JMGalleryInteractionToolbar : JMGalleryFocusToolbar
{
    JMGalleryToolbarItem *_navigationSwitchItem;
}

- (void)setNavigationSwitchItem:(id)fp8;
- (id)navigationSwitchItem;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

