/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "JMGalleryTVViewProtocol-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class UIImage, UIImageView;

@interface JMGalleryImageScrollView : _AVAudioSessionCategoryPlayback <JMGalleryTVViewProtocol, UIScrollViewDelegate>
{
    UIImageView *_imageView;
    id _onPinchCloseAction;
    id _onZoomStartAction;
    id _onZoomFinishAction;
    UIImage *_placeholderImage;
}

- (void)setPlaceholderImage:(id)fp8;
- (id)placeholderImage;
- (void)setOnZoomFinishAction:(id)fp(null);
- (id)onZoomFinishAction;
- (void)setOnZoomStartAction:(id)fp(null);
- (id)onZoomStartAction;
- (void)setOnPinchCloseAction:(id)fp(null);
- (id)onPinchCloseAction;
- (void)setImageView:(id)fp8;
- (id)imageView;
- (void).cxx_destruct;
- (void)didRemoveFromSecondScreen;
- (void)willRemoveFromSecondScreen;
- (void)didAppearOnSecondScreen;
- (void)willAppearOnSecondScreen;
- (void)setDirectImage:(id)fp8;
- (id)image;
- (void)didDoubleTapAtPoint:(struct CGPoint)fp8;
- (void)zoomInToPoint:(struct CGPoint)fp8;
- (void)scaleToFitAnimated:(BOOL)fp8;
- (void)scaleToFillAnimated:(BOOL)fp8;
- (void)scrollViewDidZoom:(id)fp8;
- (void)layoutScrollView;
- (void)scrollViewDidEndZooming:(id)fp8 withView:(id)fp12 atScale:(float)fp16;
- (void)scrollViewWillBeginZooming:(id)fp8 withView:(id)fp12;
- (void)setRemoteImageWithURL:(id)fp8 placeholderImage:(id)fp12 onProgress:(id)fp(null) onComplete:(void)fp16 onFailure:(id)fp(null);
- (void)resetZoomAndOffset;
- (id)viewForZoomingInScrollView:(id)fp8;
- (void)scaleImageToFit;
- (void)scaleImageToFitSize:(struct CGSize)fp8 animated:(BOOL)fp16;
- (id)initWithFrame:(struct CGRect)fp8;

@end

