/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGalleryGridItemDecorator.h"

@interface JMGalleryGridItemDecorator_iPhone : JMGalleryGridItemDecorator
{
}

+ (id)etchedShadowedImageFromImage:(id)fp8 scaledToSize:(struct CGSize)fp12;
- (id)decoratedImageWithImage:(id)fp8;

@end

