/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "JMGalleryPagingViewDelegate-Protocol.h"

@class JMGalleryItem, JMGalleryPagingView, JMGalleryViewController, UIView;

@interface JMGalleryViewCoordinator : _AVAudioSessionCategoryPlayback <JMGalleryPagingViewDelegate>
{
    id <JMGalleryDataSourceProtocol> _datasource;
    JMGalleryViewController *_parentController;
    JMGalleryPagingView *_pagingView;
    JMGalleryItem *_lastActiveGalleryItem;
    UIView *_i_view;
}

- (void)setI_view:(id)fp8;
- (id)i_view;
- (void)setLastActiveGalleryItem:(id)fp8;
- (id)lastActiveGalleryItem;
- (void)setPagingView:(id)fp8;
- (id)pagingView;
- (void)setParentController:(id)fp8;
- (id)parentController;
- (void)setDatasource:(id)fp8;
- (id)datasource;
- (void).cxx_destruct;
- (void)reloadPage;
- (void)pagingViewNeedsMoreResults:(id)fp8;
- (void)pagingViewDidFinishScrollAnimation:(id)fp8;
- (void)pagingViewDidStartScrollAnimation:(id)fp8;
- (void)pagingView:(id)fp8 didScrollToPage:(unsigned int)fp12;
- (id)pagingView:(id)fp8 contentViewForPage:(unsigned int)fp12;
- (unsigned int)numberOfPagesForPagingView:(id)fp8;
- (void)willDisappear;
- (float)toolbarHeight;
- (float)toolbarOffset;
- (void)willBecomeActiveForGalleryItem:(id)fp8;
- (id)galleryToolbar;
- (void)handleMidRotation;
- (id)view;
- (void)loadView;
- (id)initWithDatasource:(id)fp8 parentViewController:(id)fp12;

@end

