/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface JMGalleryItem : _AVAudioSessionCategoryPlayback
{
    BOOL _shouldStartPlaybackAutomaticallyOnNextDisplay;
    BOOL _i_requiresTapToReveal;
    int _mediaType;
    NSString *_title;
    NSString *_subtitle;
    NSString *_thumbnailUrl;
    NSString *_imageUrl;
    NSString *_mediaUrl;
    NSString *_linkedUrl;
}

+ (void)updateGalleryItemsWithThumbnailAndMediaUrls:(id)fp8 shouldStopWhen:(id)fp(null) onComplete:(void)fp12;
+ (void)filterOutGalleryItemsTooLargeDevice:(id)fp8 shouldStopWhen:(id)fp(null) onComplete:(void)fp12;
+ (BOOL)isGalleryCompatibleURL:(id)fp8;
- (void)setI_requiresTapToReveal:(BOOL)fp8;
- (BOOL)i_requiresTapToReveal;
- (void)setShouldStartPlaybackAutomaticallyOnNextDisplay:(BOOL)fp8;
- (BOOL)shouldStartPlaybackAutomaticallyOnNextDisplay;
- (void)setLinkedUrl:(id)fp8;
- (id)linkedUrl;
- (void)setMediaUrl:(id)fp8;
- (id)mediaUrl;
- (void)setImageUrl:(id)fp8;
- (id)imageUrl;
- (void)setThumbnailUrl:(id)fp8;
- (id)thumbnailUrl;
- (void)setSubtitle:(id)fp8;
- (id)subtitle;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setMediaType:(int)fp8;
- (int)mediaType;
- (void).cxx_destruct;
- (BOOL)requiresTapToReveal;
- (void)setRequiresTapToReveal:(BOOL)fp8;
- (void)updateThumbnailAndImageUrlsOnComplete:(id)fp(null) onFailure:(void)fp8;

@end

