/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineViewController.h"

@class NSString, UIPopoverController;

@interface JMGallerySettingsController : JMOutlineViewController
{
    UIPopoverController *_jm_presentingPopoverController;
    NSString *_optionTitleToHighlight;
}

+ (float)recommendedSettingScreenHeight;
+ (BOOL)setting_showNSFWWarnings;
+ (BOOL)setting_autoplayShouldIncludeGIFs;
+ (BOOL)setting_autoplayShouldIncludeVideos;
+ (BOOL)setting_autoplayShouldIncludeNSFWContent;
+ (float)setting_readingSpeedFactor;
+ (BOOL)setting_showTitleIntrosOnTV;
+ (BOOL)setting_showTitleIntrosOnDevice;
+ (BOOL)i_galleryBooleanSettingForPrefkey:(id)fp8 setToValueIfEmpty:(BOOL)fp12;
- (void)setOptionTitleToHighlight:(id)fp8;
- (id)optionTitleToHighlight;
- (void)setJm_presentingPopoverController:(id)fp8;
- (id)jm_presentingPopoverController;
- (void).cxx_destruct;
- (void)generateNodes;
- (void)setupDefaultsIfNecessary;
- (void)userDidChangeReadingSpeedToFactor:(float)fp8;
- (void)animateNodeChanges;
- (id)yesNoOptionWithTitle:(id)fp8 prefKey:(id)fp12;
- (void)viewDidLoad;
- (void)loadView;
- (void)userDidTapDone;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

