/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMAnimatedControl.h"

@interface JMGalleryPlaybackButton : JMAnimatedControl
{
    float _i_progress;
}

- (void)setI_progress:(float)fp8;
- (float)i_progress;
- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;
- (void)setHighlighted:(BOOL)fp8;
- (void)setProgress:(float)fp8;
- (float)progress;
- (void)drawRect:(struct CGRect)fp8;
- (id)progressTrackColor;
- (void)drawProgressTrackWithProgressColor:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

