/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGallerySettingNode.h"

@interface JMGallerySettingReadingSpeedNode : JMGallerySettingNode
{
    float _initialValue;
    id _onSliderValueChange;
}

+ (Class)cellClass;
- (void)setOnSliderValueChange:(id)fp(null);
- (id)onSliderValueChange;
- (void)setInitialValue:(float)fp8;
- (float)initialValue;
- (void).cxx_destruct;

@end

