/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class JMGalleryItem, UIImageView;

@interface JMGalleryCarouselItemView : _AVAudioSessionCategoryPlayback
{
    JMGalleryItem *_galleryItem;
    UIImageView *_placeholderBackgroundView;
    UIImageView *_thumbnailView;
}

- (void)setThumbnailView:(id)fp8;
- (id)thumbnailView;
- (void)setPlaceholderBackgroundView:(id)fp8;
- (id)placeholderBackgroundView;
- (void)setGalleryItem:(id)fp8;
- (id)galleryItem;
- (void).cxx_destruct;
- (void)updateWithGalleryItem:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

