/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGalleryFocusCoordinator.h"

#import "JMCarouselViewDataSource-Protocol.h"
#import "JMCarouselViewDelegate-Protocol.h"

@class JMCarouselView, UIButton;

@interface JMGalleryFocusCoordinator_iPad : JMGalleryFocusCoordinator <JMCarouselViewDataSource, JMCarouselViewDelegate>
{
    JMCarouselView *_carouselView;
    UIButton *_exitCanvasButton;
}

- (void)setExitCanvasButton:(id)fp8;
- (id)exitCanvasButton;
- (void)setCarouselView:(id)fp8;
- (id)carouselView;
- (void).cxx_destruct;
- (void)carouselView:(id)fp8 didHideItemAtIndex:(unsigned int)fp12;
- (void)carouselView:(id)fp8 didShowItemAtIndex:(unsigned int)fp12;
- (void)carouselView:(id)fp8 didSelectItemAtIndex:(unsigned int)fp12;
- (BOOL)carouselViewShouldWrap:(id)fp8;
- (struct CGSize)carouselViewGridSize:(id)fp8;
- (void)carouselViewDidFinishAnimating:(id)fp8;
- (void)carouselViewDidBeginAnimating:(id)fp8;
- (void)pagingView:(id)fp8 didScrollToPage:(unsigned int)fp12;
- (void)pagingView:(id)fp8 isScrollingFromPage:(int)fp12 toPage:(int)fp16 progress:(float)fp20;
- (void)animateCarouselToSelectItem:(id)fp8;
- (void)toggleFullscreenAnimated:(BOOL)fp8;
- (void)fadePagingViewToGalleryItemAtIndex:(unsigned int)fp8;
- (unsigned int)numberOfItemsInCarouselView:(id)fp8;
- (id)carouselView:(id)fp8 placeholderContentViewForItemAtIndex:(unsigned int)fp12 replacingExistingContentView:(id)fp16;
- (id)carouselView:(id)fp8 contentViewForItemAtIndex:(unsigned int)fp12 replacingExistingContentView:(id)fp16;
- (id)reusableCarouselThumbnailFromExistingContentView:(id)fp8;
- (void)reloadPage;
- (void)testImageFadeStartingAtIndex:(unsigned int)fp8;
- (void)willBecomeActiveForGalleryItem:(id)fp8;
- (void)handleMidRotation;
- (float)recommendedCarouselWidth;
- (float)toolbarHeight;
- (float)toolbarOffset;
- (void)createCarouselView;
- (void)decorateGlobalToolbar;
- (void)loadView;
- (void)reloadCarouselThumbnailsAfterAppHasBecomeActive;
- (id)initWithDatasource:(id)fp8 parentViewController:(id)fp12;
- (void)dealloc;

@end

