/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMCarouselView.h"

@class JMGalleryCarouselTargetView;

@interface JMGalleryCarouselView : JMCarouselView
{
    JMGalleryCarouselTargetView *_targetView;
}

- (void)setTargetView:(id)fp8;
- (id)targetView;
- (void).cxx_destruct;
- (void)appendHorizontalShadowsToCarousel;
- (void)appendVerticalShadowsToCarousel;
- (void)appendCarouselTargetView;
- (id)initWithFrame:(struct CGRect)fp8 dataSource:(id)fp24 delegate:(id)fp28;

@end

