/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIScrollViewDelegate-Protocol.h"

@class JMGalleryPageContainerView, JMGalleryPagingWrapperScrollView;

@interface JMGalleryPagingView : _AVAudioSessionCategoryPlayback <UIScrollViewDelegate>
{
    BOOL _delegateIsListeningForDidScrollEvent;
    unsigned int _pageIndex;
    id <JMGalleryPagingViewDelegate> _delegate;
    JMGalleryPageContainerView *_previousViewContainer;
    JMGalleryPageContainerView *_currentViewContainer;
    JMGalleryPageContainerView *_nextViewContainer;
    JMGalleryPagingWrapperScrollView *_wrapperView;
    float _lastReportedDidScrollEventOffset;
}

- (void)setLastReportedDidScrollEventOffset:(float)fp8;
- (float)lastReportedDidScrollEventOffset;
- (void)setDelegateIsListeningForDidScrollEvent:(BOOL)fp8;
- (BOOL)delegateIsListeningForDidScrollEvent;
- (void)setWrapperView:(id)fp8;
- (id)wrapperView;
- (void)setNextViewContainer:(id)fp8;
- (id)nextViewContainer;
- (void)setCurrentViewContainer:(id)fp8;
- (id)currentViewContainer;
- (void)setPreviousViewContainer:(id)fp8;
- (id)previousViewContainer;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setPageIndex:(unsigned int)fp8;
- (unsigned int)pageIndex;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)fp8;
- (void)willMoveToWindow:(id)fp8;
- (id)contentViewForSelectedPage;
- (void)goPrevious;
- (void)goNext;
- (void)jumpToPageIndex:(unsigned int)fp8;
- (void)scrollToCurrent;
- (void)layoutSubviews;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewWillBeginDecelerating:(id)fp8;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)didPageLeft;
- (void)didPageRight;
- (void)updateContainerContents;
- (void)layoutPagingPanes;
- (id)initWithFrame:(struct CGRect)fp8 delegate:(id)fp24;

@end

