/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMContentOptimizer.h"

@class JMGalleryFocusMediaView, NSURL;

@interface JMImageContentOptimizer : JMContentOptimizer
{
    BOOL _fadeInWillBeHandledExternallyAfterLoading;
    BOOL _i_imageViewNeedsLayout;
    NSURL *_deeplinkedImageURL;
    JMGalleryFocusMediaView *_photoView;
    struct CGSize _i_lastPhotoSize;
}

+ (BOOL)canHandleOptimizationForURL:(id)fp8;
- (void)setI_lastPhotoSize:(struct CGSize)fp8;
- (struct CGSize)i_lastPhotoSize;
- (void)setI_imageViewNeedsLayout:(BOOL)fp8;
- (BOOL)i_imageViewNeedsLayout;
- (void)setPhotoView:(id)fp8;
- (id)photoView;
- (void)setFadeInWillBeHandledExternallyAfterLoading:(BOOL)fp8;
- (BOOL)fadeInWillBeHandledExternallyAfterLoading;
- (void)setDeeplinkedImageURL:(id)fp8;
- (id)deeplinkedImageURL;
- (void).cxx_destruct;
- (id)contentTypeIdentifier;
- (BOOL)isAnimated;
- (struct CGRect)visibleImageRect;
- (void)setImageViewNeedsLayout;
- (void)willUnloadView;
- (void)applyThemeSettings;
- (void)fadeInLoadedImageOnAnimationComplete:(id)fp(null);
- (void)didLoadImage:(id)fp8;
- (void)fetchImage;
- (void)fetchRemoteImageAtURL:(id)fp8;
- (void)loadView;
- (void)dealloc;

@end

