/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "JMOptimalSwitchDelegate-Protocol.h"

@class JMOptimalToolbar, NSObject<JMOptimalToolbarCoordinatorDelegate>;

@interface JMOptimalToolbarCoordinator : _AVAudioSessionCategoryPlayback <JMOptimalSwitchDelegate>
{
    JMOptimalToolbar *_toolbar;
    NSObject<JMOptimalToolbarCoordinatorDelegate> *_delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setToolbar:(id)fp8;
- (id)toolbar;
- (void).cxx_destruct;
- (void)applyThemeSettings;
- (void)optimalSwitch:(id)fp8 didChangeOptimalTo:(BOOL)fp12;
- (void)progressBarEndIndeterminate;
- (void)progressBarStartIndeterminate;
- (BOOL)optimalSwitchDisabled;
- (void)setOptimalSwitchDisabled:(BOOL)fp8;
- (void)setOptimal:(BOOL)fp8 animated:(BOOL)fp12;
- (void)updateWithOptimalProgress:(float)fp8;
- (void)didTapSettingsButton;
- (id)view;
- (id)initWithDelegate:(id)fp8;
- (void)exitPullToRefreshMode;
- (void)updateWithPullToRefreshProgress:(float)fp8;
- (void)setPrePullProgressValue:(float)fp8;
- (float)prePullProgressValue;
- (void)setPrePullProgressMode:(unsigned int)fp8;
- (unsigned int)prePullProgressMode;

@end

