/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMAnimatedControl.h"

@interface JMOptimalProgressBar : JMAnimatedControl
{
    BOOL _hidesWhenInactive;
    float __progress;
    float __stripeOffset;
    unsigned int _i_barMode;
}

- (void)setI_barMode:(unsigned int)fp8;
- (unsigned int)i_barMode;
- (void)set_stripeOffset:(float)fp8;
- (float)_stripeOffset;
- (void)set_progress:(float)fp8;
- (float)_progress;
- (void)setHidesWhenInactive:(BOOL)fp8;
- (BOOL)hidesWhenInactive;
- (void)applyThemeSettings;
- (void)stop;
- (void)start;
- (void)drawRect:(struct CGRect)fp8;
- (void)drawProgress;
- (void)drawProgressStripesToFillWidth:(float)fp8;
- (id)progressColor;
- (void)drawTrack;
- (float)progress;
- (void)setProgress:(float)fp8;
- (void)willRedrawForAnimationStep:(unsigned int)fp8;
- (void)stopAnimating;
- (void)startAnimating;
- (unsigned int)progressBarMode;
- (void)setProgressBarMode:(unsigned int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

