/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface JMOutlineTableView : _AVAudioSessionCategoryPlayback
{
    BOOL _jm_isAdjustingFrame;
}

- (void)setJm_isAdjustingFrame:(BOOL)fp8;
- (BOOL)jm_isAdjustingFrame;
- (void)reloadRowsAtIndexPaths:(id)fp8 withRowAnimation:(int)fp12;
- (void)setBackgroundColor:(id)fp8;
- (void)layoutSubviews;
- (void)setContentOffset:(struct CGPoint)fp8;
- (void)setFrame:(struct CGRect)fp8;

@end

