/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray, NSObject<JMOutlineNodeProtocol>;

@interface JMOutlineNode : _AVAudioSessionCategoryPlayback
{
    BOOL _editable;
    NSObject<JMOutlineNodeProtocol> *delegate_;
    id onSelect_;
    unsigned int level_;
    int state_;
    JMOutlineNode *parentNode_;
    NSMutableArray *childNodes_;
}

+ (Class)cellClass;
+ (id)node;
- (void)setEditable:(BOOL)fp8;
- (BOOL)editable;
- (void)setChildNodes:(id)fp8;
- (id)childNodes;
- (void)setParentNode:(id)fp8;
- (id)parentNode;
- (void)setState:(int)fp8;
- (int)state;
- (void)setLevel:(unsigned int)fp8;
- (unsigned int)level;
- (void)setOnSelect:(id)fp(null);
- (id)onSelect;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)refresh;
- (void)hideNode;
- (void)expandNode;
- (void)hideChildren;
- (void)collapseNode;
- (id)allChildren;
- (void)addChildNode:(id)fp8;
- (BOOL)hidden;
- (BOOL)collapsed;
- (BOOL)selected;
- (id)init;
- (void)dealloc;

@end

