/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface JMPageExtractor : _AVAudioSessionCategoryPlayback
{
}

+ (void)extractContentWithXPathQuery:(id)fp8 fromURL:(id)fp12 onComplete:(id)fp(null) onError:(void)fp16;
+ (id)contentMatchingXPathQuery:(id)fp8 fromHTML:(id)fp12;
+ (id)innerHTMLContentMatchingXPathQuery:(id)fp8 fromHTML:(id)fp12;
+ (id)contentMatchingXPathQuery:(id)fp8 fromData:(id)fp12 contentKey:(id)fp16;

@end

