/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSTimer, UIColor, UILabel, UIView;

@interface JMRefreshHeaderView : _AVAudioSessionCategoryPlayback <UIScrollViewDelegate>
{
    BOOL _isLoading;
    id <JMRefreshHeaderDelegate> _controller;
    float _defaultScrollOffset;
    id _onTrigger;
    UILabel *_statusLabel;
    UIView *_containerView;
    NSTimer *_animationTimer;
    UIColor *_jm_foregroundColor;
    int _state;
    float _triggerRatio;
    unsigned int _animationStep;
}

+ (float)headerHeight;
+ (id)hookRefreshHeaderToController:(id)fp8 onTrigger:(id)fp(null);
- (void)setAnimationStep:(unsigned int)fp8;
- (unsigned int)animationStep;
- (void)setIsLoading:(BOOL)fp8;
- (BOOL)isLoading;
- (void)setTriggerRatio:(float)fp8;
- (float)triggerRatio;
- (void)setState:(int)fp8;
- (int)state;
- (void)setJm_foregroundColor:(id)fp8;
- (id)jm_foregroundColor;
- (void)setAnimationTimer:(id)fp8;
- (id)animationTimer;
- (void)setContainerView:(id)fp8;
- (id)containerView;
- (void)setStatusLabel:(id)fp8;
- (id)statusLabel;
- (void)setOnTrigger:(id)fp(null);
- (id)onTrigger;
- (void)setDefaultScrollOffset:(float)fp8;
- (float)defaultScrollOffset;
- (void)setController:(id)fp8;
- (id)controller;
- (void).cxx_destruct;
- (void)viewWillDisappear;
- (void)finishedLoading;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)setModeLoading;
- (void)setModePulling;
- (void)setModeIdle;
- (void)drawRect:(struct CGRect)fp8;
- (void)drawCircularLoadingIndicator;
- (void)drawAntennaWave:(unsigned int)fp8 flipped:(BOOL)fp12;
- (void)drawAlien;
- (void)setForegroundColor:(id)fp8;
- (void)setBackgroundColor:(id)fp8;
- (float)triggerOffset;
- (void)dealloc;

@end

