/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class HTMLNode, NSMutableArray, NSString;

@interface JMRParser : _AVAudioSessionCategoryPlayback
{
    NSString *_summaryContent;
    NSString *_htmlStr;
    HTMLNode *_body;
    NSMutableArray *_detachedNodes;
}

- (void)setDetachedNodes:(id)fp8;
- (id)detachedNodes;
- (void)setBody:(id)fp8;
- (id)body;
- (void)setHtmlStr:(id)fp8;
- (id)htmlStr;
- (id)summaryContent;
- (void).cxx_destruct;
- (void)removeCandidatesFromNodeArray:(id)fp8 regExPattern:(id)fp12 searchType:(int)fp16;
- (void)removeNodesWithTag:(id)fp8;
- (id)generateArticleHTMLWithNodes:(id)fp8;
- (id)grabArticleNodes;
- (void)prepDocument;
- (void)parseOnComplete:(id)fp(null);
- (id)initWithHTML:(id)fp8;

@end

