/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMSiteMediaHandler.h"

@interface JMSiteMediaTwitpicHandler : JMSiteMediaHandler
{
}

+ (void)deeplinkedImageURLForLinkURL:(id)fp8 onComplete:(id)fp(null) onFailure:(void)fp12;
+ (void)thumbnailURLForLinkURL:(id)fp8 onComplete:(id)fp(null) onFailure:(void)fp12;
+ (BOOL)hasDeeplinkedImageForURL:(id)fp8;
+ (id)hosts;

@end

