/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMSiteMediaOEmbedHandler.h"

@interface JMSiteMediaFlickrHandler : JMSiteMediaOEmbedHandler
{
}

+ (BOOL)hasDeeplinkedImageForURL:(id)fp8;
+ (id)oEmbedBaseUrl;
+ (id)hosts;

@end

