/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UIView;

@interface JMSlideableNavigationAnimatorView : _AVAudioSessionCategoryPlayback
{
    BOOL _animating;
    BOOL _isUpdatingLeftView;
    BOOL _isUpdatingRightView;
    id <JMSlideableNavigationAnimatorDelegate> _delegate;
    UIImageView *_leftView;
    UIImageView *_centerView;
    UIImageView *_rightView;
    UIView *_rightUnderlayView;
    UIView *_leftUnderlayView;
    UIImageView *_leftEdgeShadow;
    UIImageView *_rightEdgeShadow;
}

- (void)setIsUpdatingRightView:(BOOL)fp8;
- (BOOL)isUpdatingRightView;
- (void)setIsUpdatingLeftView:(BOOL)fp8;
- (BOOL)isUpdatingLeftView;
- (void)setRightEdgeShadow:(id)fp8;
- (id)rightEdgeShadow;
- (void)setLeftEdgeShadow:(id)fp8;
- (id)leftEdgeShadow;
- (void)setLeftUnderlayView:(id)fp8;
- (id)leftUnderlayView;
- (void)setRightUnderlayView:(id)fp8;
- (id)rightUnderlayView;
- (void)setRightView:(id)fp8;
- (id)rightView;
- (void)setCenterView:(id)fp8;
- (id)centerView;
- (void)setLeftView:(id)fp8;
- (id)leftView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAnimating:(BOOL)fp8;
- (BOOL)animating;
- (void).cxx_destruct;
- (void)willRemoveAnimatorOverlay;
- (void)didReleaseAtRatio:(float)fp8 targetRatio:(float)fp12 velocity:(float)fp16 direction:(int)fp20 onAnimationComplete:(id)fp(null);
- (void)didDragToRatio:(float)fp8 direction:(int)fp12 beyondBoundary:(BOOL)fp16;
- (void)prepareSlideableRepresentations;
- (void)updateRightView;
- (void)updateLeftView;
- (id)initWithDelegate:(id)fp8;

@end

