/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "JMSlideableNavigationAnimatorDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class JMAnimatedSlideIndicatorView, JMSlideableNavigationAnimatorView, NSMutableArray, UIScrollView;

@interface JMSlideableNavigationController : _AVAudioSessionCategoryPlayback <JMSlideableNavigationAnimatorDelegate, UIGestureRecognizerDelegate>
{
    BOOL _shouldActivateBeyondBoundaryTrigger;
    BOOL _shouldMaintainExistingNavigationStackAfterPush;
    BOOL _isDragging;
    float _panGestureStartX;
    JMSlideableNavigationAnimatorView *_animatorView;
    JMAnimatedSlideIndicatorView *_trainingView;
    NSMutableArray *_slidingNavigationStack;
    UIScrollView *_scrollViewAffectedByConcurrentPanGesture;
    struct CGPoint _initialScrollViewOffsetForConcurrentPanGesture;
}

+ (BOOL)allowSwipeNavigation;
- (void)setIsDragging:(BOOL)fp8;
- (BOOL)isDragging;
- (void)setInitialScrollViewOffsetForConcurrentPanGesture:(struct CGPoint)fp8;
- (struct CGPoint)initialScrollViewOffsetForConcurrentPanGesture;
- (void)setScrollViewAffectedByConcurrentPanGesture:(id)fp8;
- (id)scrollViewAffectedByConcurrentPanGesture;
- (void)setShouldMaintainExistingNavigationStackAfterPush:(BOOL)fp8;
- (BOOL)shouldMaintainExistingNavigationStackAfterPush;
- (void)setSlidingNavigationStack:(id)fp8;
- (id)slidingNavigationStack;
- (void)setTrainingView:(id)fp8;
- (id)trainingView;
- (void)setAnimatorView:(id)fp8;
- (id)animatorView;
- (void)setPanGestureStartX:(float)fp8;
- (float)panGestureStartX;
- (void)setShouldActivateBeyondBoundaryTrigger:(BOOL)fp8;
- (BOOL)shouldActivateBeyondBoundaryTrigger;
- (void).cxx_destruct;
- (void)viewDidAppear:(BOOL)fp8;
- (void)userDidNavigateBackWithoutSwiping;
- (void)dismissTrainingViewAnimated:(BOOL)fp8;
- (void)userDidTapTrainingView;
- (void)showTrainingScreenIfNecessary;
- (void)setTrainingComplete;
- (BOOL)trainingUserHasUtilizedSwipeBefore;
- (void)animatorView:(id)fp8 decorateLeftUnderlay:(id)fp12 forBoundaryOffset:(float)fp16;
- (void)animatorView:(id)fp8 decorateRightUnderlay:(id)fp12 forBoundaryOffset:(float)fp16;
- (id)imageRepresentingNextControllerForAnimatorView:(id)fp8;
- (id)imageRepresentingCurrentControllerForAnimatorView:(id)fp8;
- (id)imageRepresentingPreviousControllerForAnimatorView:(id)fp8;
- (void)didPress:(id)fp8;
- (void)didReleaseBeyondRightBoundaryTrigger;
- (void)didReleaseBeyondLeftBoundaryTrigger;
- (void)handleControllerSwitchDueToSwipeDirection:(int)fp8;
- (id)previousSlideableController;
- (id)nextSlideableController;
- (void)didPan:(id)fp8;
- (void)resetScrollOffsetForConcurrentPanGesture;
- (id)popViewControllerAnimated:(BOOL)fp8;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)showAnimatorOverlay;
- (void)removeAnimatorOverlay;
- (void)loadView;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (void)assignGestureRecognizers;
- (void)setViewControllers:(id)fp8 animated:(BOOL)fp12;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

