/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol JMSlideableNavigationAnimatorDelegate <NSObject>
- (id)view;
- (void)animatorView:(id)fp8 decorateLeftUnderlay:(id)fp12 forBoundaryOffset:(float)fp16;
- (void)animatorView:(id)fp8 decorateRightUnderlay:(id)fp12 forBoundaryOffset:(float)fp16;
- (id)imageRepresentingNextControllerForAnimatorView:(id)fp8;
- (id)imageRepresentingCurrentControllerForAnimatorView:(id)fp8;
- (id)imageRepresentingPreviousControllerForAnimatorView:(id)fp8;
@end

