/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMContentOptimizer.h"

@class UIWebView;

@interface JMSoundCloudContentOptimizer : JMContentOptimizer
{
    BOOL _hasWebViewUnloaded;
    UIWebView *_webView;
}

+ (BOOL)canHandleOptimizationForURL:(id)fp8;
- (void)setHasWebViewUnloaded:(BOOL)fp8;
- (BOOL)hasWebViewUnloaded;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void).cxx_destruct;
- (id)contentTypeIdentifier;
- (void)willUnloadView;
- (void)didRetrieveAuthenticatedSoundCloudStream:(id)fp8;
- (void)retrieveSoundCloudStream;
- (void)resolveTrackStreamURLOnComplete:(id)fp(null);
- (id)clientIdentifier;
- (void)loadView;

@end

