/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImage;

@interface JMSurfaceButton : _AVAudioSessionCategoryPlayback
{
    UIImage *_etchedImage;
    int _surfaceLevel;
}

- (void)setSurfaceLevel:(int)fp8;
- (int)surfaceLevel;
- (void)setEtchedImage:(id)fp8;
- (id)etchedImage;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (id)initWithFrame:(struct CGRect)fp8 skinImageNamed:(id)fp24 imageColor:(id)fp28 surfaceLevel:(int)fp32;

@end

