/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextViewDelegate-Protocol.h"

@class JMTextView, NSString, UIImageView, UILabel;

@interface JMTextViewController : _AVAudioSessionCategoryPlayback <UITextViewDelegate>
{
    BOOL singleLine_;
    id <JMTextViewDelegate> delegate_;
    NSString *propertyKey_;
    JMTextView *textView_;
    NSString *placeholderText_;
    UILabel *placeholderLabel_;
    NSString *defaultText_;
    int autoCorrectionType_;
    int keyboardType_;
    int returnKeyType_;
    UIImageView *_textViewBackgroundImageView;
    id _onComplete;
    id _onDismiss;
}

+ (id)controllerOnComplete:(id)fp(null) onDismiss:(void)fp8;
- (void)setOnDismiss:(id)fp(null);
- (id)onDismiss;
- (void)setOnComplete:(id)fp(null);
- (id)onComplete;
- (void)setTextViewBackgroundImageView:(id)fp8;
- (id)textViewBackgroundImageView;
- (void)setReturnKeyType:(int)fp8;
- (int)returnKeyType;
- (void)setSingleLine:(BOOL)fp8;
- (BOOL)singleLine;
- (void)setKeyboardType:(int)fp8;
- (int)keyboardType;
- (void)setAutoCorrectionType:(int)fp8;
- (int)autoCorrectionType;
- (void)setDefaultText:(id)fp8;
- (id)defaultText;
- (void)setPlaceholderLabel:(id)fp8;
- (id)placeholderLabel;
- (void)setPlaceholderText:(id)fp8;
- (id)placeholderText;
- (void)setTextView:(id)fp8;
- (id)textView;
- (void)setPropertyKey:(id)fp8;
- (id)propertyKey;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)autosave;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (BOOL)textViewShouldReturn:(id)fp8;
- (void)viewDidUnload;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)loadView;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (float)heightForTextViewInOrientation:(int)fp8;
- (void)cancel;
- (void)done;
- (void)dismiss;
- (void)finishWithValue:(id)fp8;
- (id)initWithDelegate:(id)fp8 propertyKey:(id)fp12;
- (void)releaseViews;
- (void)dealloc;

@end

