/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineCell.h"

#import "JMTextFieldEntryDelegate-Protocol.h"

@class JMTextFieldEntry;

@interface JMTextFieldEntryCell : JMOutlineCell <JMTextFieldEntryDelegate>
{
    JMTextFieldEntry *_entryView;
    id _onComplete;
    id _onEndEditing;
    id _onCancel;
}

+ (float)heightForNode:(id)fp8 tableView:(id)fp12;
- (void)setOnCancel:(id)fp(null);
- (id)onCancel;
- (void)setOnEndEditing:(id)fp(null);
- (id)onEndEditing;
- (void)setOnComplete:(id)fp(null);
- (id)onComplete;
- (void)setEntryView:(id)fp8;
- (id)entryView;
- (void).cxx_destruct;
- (void)textFieldEntryDidEndEditing:(id)fp8;
- (void)textFieldEntryDidCancel:(id)fp8;
- (void)textFieldEntry:(id)fp8 finishedWithString:(id)fp12;
- (void)updateWithNode:(id)fp8;
- (void)createSubviews;

@end

