/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIView;

@interface JMViewOverlay : _AVAudioSessionCategoryPlayback
{
    BOOL _allowTouchPassthrough;
    BOOL _redrawsOnTouch;
    BOOL _highlighted;
    BOOL _selected;
    BOOL _hidden;
    UIView *_parentView;
    id _drawBlock;
    id _onTap;
    id _onPress;
    unsigned int _autoresizingMask;
    struct CGRect _frame;
    struct CGRect _initialFrame;
    struct CGRect _initialParentBounds;
}

+ (id)overlayWithFrame:(struct CGRect)fp8 drawBlock:(id)fp(null);
+ (id)overlayWithFrame:(struct CGRect)fp8 drawBlock:(id)fp(null) onTap:(void)fp24;
+ (id)tinyBoldButtonWithIcon:(id)fp8 title:(id)fp12;
+ (id)tinyButtonWithIcon:(id)fp8 title:(id)fp12;
+ (id)tinyButtonWithIcon:(id)fp8 title:(id)fp12 color:(id)fp16;
+ (id)buttonWithIcon:(id)fp8;
+ (id)buttonWithTitle:(id)fp8;
+ (id)buttonWithIcon:(id)fp8 title:(id)fp12;
+ (id)buttonWithIcon:(id)fp8 title:(id)fp12 titleOffset:(float)fp16;
+ (id)buttonWithIcon:(id)fp8 iconDimension:(float)fp12 title:(id)fp16 titleOffset:(struct CGSize)fp20 standardColor:(id)fp28 titleFont:(id)fp32;
+ (id)buttonWithIcon:(id)fp8 highlightColor:(id)fp12;
- (void)setInitialParentBounds:(struct CGRect)fp8;
- (struct CGRect)initialParentBounds;
- (void)setInitialFrame:(struct CGRect)fp8;
- (struct CGRect)initialFrame;
- (void)setAutoresizingMask:(unsigned int)fp8;
- (unsigned int)autoresizingMask;
- (void)setOnPress:(id)fp(null);
- (id)onPress;
- (void)setOnTap:(id)fp(null);
- (id)onTap;
- (void)setDrawBlock:(id)fp(null);
- (id)drawBlock;
- (void)setFrame:(struct CGRect)fp8;
- (struct CGRect)frame;
- (void)setHidden:(BOOL)fp8;
- (BOOL)hidden;
- (void)setSelected:(BOOL)fp8;
- (BOOL)selected;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)highlighted;
- (void)setRedrawsOnTouch:(BOOL)fp8;
- (BOOL)redrawsOnTouch;
- (void)setAllowTouchPassthrough:(BOOL)fp8;
- (BOOL)allowTouchPassthrough;
- (void)setParentView:(id)fp8;
- (id)parentView;
- (void).cxx_destruct;
- (void)autoresize;
- (void)resetHighlightStates;
- (void)drawRect:(struct CGRect)fp8;
- (void)setNeedsDisplay;
- (struct CGRect)bounds;
- (void)removeFromParentView;
- (id)init;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setI_cachedPositionInAttributeString:(unsigned int)fp8;
- (unsigned int)i_cachedPositionInAttributeString;
- (void)setI_originRelativeToTextContainer:(struct CGPoint)fp8;
- (struct CGPoint)i_originRelativeToTextContainer;
- (struct CGRect)jm_globalFrame;
- (void)setHeight:(float)fp8;
- (float)height;
- (void)setWidth:(float)fp8;
- (float)width;
- (void)setBottom:(float)fp8;
- (float)bottom;
- (void)setRight:(float)fp8;
- (float)right;
- (void)setTop:(float)fp8;
- (float)top;
- (void)setLeft:(float)fp8;
- (float)left;
- (struct CGSize)size;
- (void)setSize:(struct CGSize)fp8;

@end

