/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIWebViewDelegate-Protocol.h"

@class MPMoviePlayerController, NSMutableArray, NSObject<JMYouTubeViewDelegate>, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIWebView;

@interface JMYouTubeView : _AVAudioSessionCategoryPlayback <UIWebViewDelegate>
{
    BOOL _i_cleaningUp;
    BOOL _i_playerIsLoaded;
    BOOL _i_allowAutoplay;
    NSObject<JMYouTubeViewDelegate> *_delegate;
    UIButton *_playButton;
    UIWebView *_webView;
    UIImageView *_placeholderImageView;
    UILabel *_messageLabel;
    NSMutableArray *_videoIdents;
    NSString *_previousUserAgent;
    MPMoviePlayerController *_web_moviePlayer;
    UIActivityIndicatorView *_activityIndicatorView;
    unsigned int _videoDurationSeconds;
}

+ (id)playButtonImageWithSize:(struct CGSize)fp8;
- (void)setVideoDurationSeconds:(unsigned int)fp8;
- (unsigned int)videoDurationSeconds;
- (void)setActivityIndicatorView:(id)fp8;
- (id)activityIndicatorView;
- (void)setI_allowAutoplay:(BOOL)fp8;
- (BOOL)i_allowAutoplay;
- (void)setWeb_moviePlayer:(id)fp8;
- (id)web_moviePlayer;
- (void)setI_playerIsLoaded:(BOOL)fp8;
- (BOOL)i_playerIsLoaded;
- (void)setI_cleaningUp:(BOOL)fp8;
- (BOOL)i_cleaningUp;
- (void)setPreviousUserAgent:(id)fp8;
- (id)previousUserAgent;
- (void)setVideoIdents:(id)fp8;
- (id)videoIdents;
- (void)setMessageLabel:(id)fp8;
- (id)messageLabel;
- (void)setPlaceholderImageView:(id)fp8;
- (id)placeholderImageView;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setPlayButton:(id)fp8;
- (id)playButton;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)clearYouTubeWebsitePlayerPreferenceCookies:(id)fp8;
- (void)playerDidFailWithReason:(id)fp8;
- (void)playerDidFinishPlaylistPlayback;
- (void)playerDidFinishPlayingVideo:(id)fp8;
- (void)playerDidPause;
- (void)playerDidPlayToDuration:(id)fp8;
- (void)playerDidStartPlayingVideoAtIndex:(id)fp8;
- (void)playerDidLoad;
- (double)startingPositionForVideoAtPlaylistIndex:(unsigned int)fp8;
- (BOOL)shouldAutoplay;
- (BOOL)shouldLoop;
- (unsigned int)startingPlaylistIndex;
- (id)playbackQuality;
- (id)playlistVideoIdents;
- (void)setPlaybackQualityWithIdentifier:(id)fp8;
- (void)resumePlayback;
- (void)pausePlayback;
- (void)userDidTapPlayButton;
- (void)fadeOutWebView;
- (void)fadeInWebView;
- (unsigned int)fadeOutDurationSeconds;
- (unsigned int)fadeInDurationSeconds;
- (void)removeYouTubeView;
- (void)i_cleanUp;
- (void)destroyHTML5PlayerOnComplete:(id)fp(null);
- (void)populateWebView;
- (void)loadYouTubeURL:(id)fp8 autoplay:(BOOL)fp12 playsInline:(BOOL)fp16;
- (void)configureForManualPlaybackForYouTubeURL:(id)fp8;
- (BOOL)isPlayingInFullscreen;
- (void)webPlayerDidBecomeActive:(id)fp8;
- (void)didReceiveMemoryWarning;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

