/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "KSWriter-Protocol.h"

@interface KSForwardingWriter : _AVAudioSessionCategoryPlayback <KSWriter>
{
    id <KSWriter> _writer;
}

- (void).cxx_destruct;
- (void)writeString:(id)fp8;
- (void)close;
- (void)dealloc;
- (id)init;
- (id)initWithOutputWriter:(id)fp8;

@end

