/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "KSXMLWriter.h"

@class NSMutableArray, NSMutableSet, NSString;

@interface KSHTMLWriter : KSXMLWriter
{
    NSString *_docType;
    BOOL _isXHTML;
    NSMutableSet *_IDs;
    NSMutableArray *_classNames;
}

+ (BOOL)isDocTypeXHTML:(id)fp8;
- (id)docType;
- (void).cxx_destruct;
- (void)closeEmptyElementTag;
- (void)startElement:(id)fp8 writeInline:(BOOL)fp12;
- (id)validateAttribute:(id)fp8 value:(id)fp12 ofElement:(id)fp16;
- (BOOL)validateElement:(id)fp8;
- (BOOL)canWriteElementInline:(id)fp8;
- (BOOL)elementCanBeEmpty:(id)fp8;
- (BOOL)topElementIsList;
- (void)startStyleElementWithType:(id)fp8;
- (void)writeStyleElementWithCSSString:(id)fp8;
- (void)writeParamElementWithName:(id)fp8 value:(id)fp12;
- (void)endJavascriptCDATA;
- (void)startJavascriptCDATA;
- (void)startJavascriptElementWithSrc:(id)fp8;
- (void)writeJavascript:(id)fp8 useCDATA:(BOOL)fp12;
- (void)writeJavascriptWithSrc:(id)fp8 charset:(id)fp12;
- (void)writeJavascriptWithSrc:(id)fp8 encoding:(unsigned int)fp12;
- (void)writeLinkToStylesheet:(id)fp8 title:(id)fp12 media:(id)fp16;
- (void)writeLinkWithHref:(id)fp8 type:(id)fp12 rel:(id)fp16 title:(id)fp20 media:(id)fp24;
- (void)writeImageWithSrc:(id)fp8 alt:(id)fp12 width:(id)fp16 height:(id)fp20;
- (void)startAnchorElementWithHref:(id)fp8 title:(id)fp12 target:(id)fp16 rel:(id)fp20;
- (void)writeLineBreak;
- (BOOL)isIDValid:(id)fp8;
- (void)startElement:(id)fp8 idName:(id)fp12 className:(id)fp16;
- (void)startElement:(id)fp8 className:(id)fp12;
- (void)writeHTMLFormat:(id)fp8;
- (void)writeHTMLString:(id)fp8;
- (BOOL)hasCurrentAttributes;
- (id)currentAttributes;
- (void)pushAttribute:(id)fp8 value:(id)fp12;
- (void)pushClassName:(id)fp8;
- (id)currentElementClassName;
- (BOOL)isXHTML;
- (void)setDocType:(id)fp8;
- (void)startDocumentWithDocType:(id)fp8 encoding:(unsigned int)fp12;
- (id)initWithOutputWriter:(id)fp8 docType:(id)fp12 encoding:(unsigned int)fp16;
- (id)initWithOutputWriter:(id)fp8;

@end

