/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class KSXMLWriter;

@interface KSXMLElementContentsProxy : _AVAudioSessionCategoryPlayback
{
    id _target;
    KSXMLWriter *_XMLWriter;
    unsigned int _elementsCount;
}

- (void).cxx_destruct;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (void)ks_prepareWithTarget:(id)fp8 XMLWriter:(id)fp12;

@end

