/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface LayoutView : _AVAudioSessionCategoryPlayback
{
    id <LayoutManager> layoutManager_;
}

- (void)setLayoutManager:(id)fp8;
- (id)layoutManager;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (BOOL)hasLayoutManager;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 layoutManager:(id)fp24;

@end

