/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMViewOverlay.h"

@class BaseStyledTextNode, CommentLink;

@interface LinkThumbsOverlay : JMViewOverlay
{
    BaseStyledTextNode *_commentNode;
    CommentLink *_highlightedCommentLink;
    struct CGRect _commentTextRect;
}

+ (float)heightForLinkThumbsOverlayForNode:(id)fp8 constrainedToWidth:(float)fp12 textWidth:(float)fp16;
+ (float)heightForInlineImage:(id)fp8 constrainedToWidth:(float)fp12 textWidth:(float)fp16;
+ (float)heightForTileDrawer:(id)fp8 constrainedToWidth:(float)fp12 textWidth:(float)fp16;
- (void)setHighlightedCommentLink:(id)fp8;
- (id)highlightedCommentLink;
- (void)setCommentNode:(id)fp8;
- (id)commentNode;
- (void)setCommentTextRect:(struct CGRect)fp8;
- (struct CGRect)commentTextRect;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (struct CGRect)rectForThumbDrawer;
- (void)drawInlineImage;
- (id)fetchInlineImageOnComplete:(id)fp(null);
- (void)drawTileForCommentLink:(id)fp8;
- (void)drawThumbnailForCommentLink:(id)fp8 inFrame:(struct CGRect)fp12;
- (struct CGRect)rectForTileCommentLink:(id)fp8;
- (void)openCommentLink:(id)fp8 forceBrowser:(BOOL)fp12;
- (void)closeInlineImage;
- (void)updateForNode:(id)fp8;
- (id)commentLinkAtTouchPoint:(struct CGPoint)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

