/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField, UIView;

@interface LoginPasswordViewController : _AVAudioSessionCategoryPlayback <UITextFieldDelegate>
{
    BOOL isEditing;
    int editingAccountIndex;
    id callBackTarget;
    NSString *callBackAction;
    int responseID;
    int accountTypeID;
    NSString *username;
    NSString *password;
    UITextField *usernameField;
    UITextField *passwordField;
    UIView *inputAccessoryView;
}

- (void)setPassword:(id)fp8;
- (id)password;
- (void)setUsername:(id)fp8;
- (id)username;
- (void).cxx_destruct;
- (void)dealloc;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)textFieldDidChange:(id)fp8;
- (void)textFieldDidEndEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (id)generateInputAccessoryView;
- (void)nextPrevChanged:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)setCallBackTarget:(id)fp8 withAction:(id)fp12 forAccountType:(int)fp16 forResponseID:(int)fp20;
- (void)save:(id)fp8;
- (void)cancel:(id)fp8;

@end

