/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDate, NSString, NSTimer, UIColor, UIFont, UILabel, UIView;

@interface MBProgressHUD : _AVAudioSessionCategoryPlayback
{
    int mode;
    int animationType;
    SEL methodForExecution;
    id targetForExecution;
    id objectForExecution;
    BOOL useAnimation;
    float yOffset;
    float xOffset;
    float width;
    float height;
    BOOL taskInProgress;
    float graceTime;
    float minShowTime;
    NSTimer *graceTimer;
    NSTimer *minShowTimer;
    NSDate *showStarted;
    UIView *indicator;
    UILabel *label;
    UILabel *detailsLabel;
    float progress;
    id <MBProgressHUDDelegate> delegate;
    NSString *labelText;
    NSString *detailsLabelText;
    float opacity;
    UIFont *labelFont;
    UIFont *detailsLabelFont;
    BOOL isFinished;
    BOOL removeFromSuperViewOnHide;
    UIView *customView;
    struct CGAffineTransform rotationTransform;
    UIColor *panelBackgroundColor_;
}

+ (BOOL)hideHUDForView:(id)fp8 animated:(BOOL)fp12;
+ (id)showHUDAddedTo:(id)fp8 animated:(BOOL)fp12;
- (void)setShowStarted:(id)fp8;
- (id)showStarted;
- (void)setCustomView:(id)fp8;
- (id)customView;
- (void)setRemoveFromSuperViewOnHide:(BOOL)fp8;
- (BOOL)removeFromSuperViewOnHide;
- (void)setTaskInProgress:(BOOL)fp8;
- (BOOL)taskInProgress;
- (void)setMinShowTimer:(id)fp8;
- (id)minShowTimer;
- (void)setGraceTimer:(id)fp8;
- (id)graceTimer;
- (void)setMinShowTime:(float)fp8;
- (float)minShowTime;
- (void)setGraceTime:(float)fp8;
- (float)graceTime;
- (void)setYOffset:(float)fp8;
- (float)yOffset;
- (void)setXOffset:(float)fp8;
- (float)xOffset;
- (void)setHeight:(float)fp8;
- (float)height;
- (void)setWidth:(float)fp8;
- (float)width;
- (void)setIndicator:(id)fp8;
- (id)indicator;
- (void)setDetailsLabelFont:(id)fp8;
- (id)detailsLabelFont;
- (void)setLabelFont:(id)fp8;
- (id)labelFont;
- (void)setOpacity:(float)fp8;
- (float)opacity;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAnimationType:(int)fp8;
- (int)animationType;
- (void)setPanelBackgroundColor:(id)fp8;
- (id)panelBackgroundColor;
- (void).cxx_destruct;
- (void)setTransformForCurrentOrientation:(BOOL)fp8;
- (void)deviceOrientationDidChange:(id)fp8;
- (void)fillRoundedRect:(struct CGRect)fp8 inContext:(struct CGContext *)fp24;
- (void)drawRect:(struct CGRect)fp8;
- (void)hideUsingAnimation:(BOOL)fp8;
- (void)showUsingAnimation:(BOOL)fp8;
- (void)cleanUp;
- (void)done;
- (void)animationFinished:(id)fp8 finished:(BOOL)fp12 context:(void *)fp16;
- (void)launchExecution;
- (void)showWhileExecuting:(SEL)fp8 onTarget:(id)fp12 withObject:(id)fp16 animated:(BOOL)fp20;
- (void)handleMinShowTimer:(id)fp8;
- (void)handleGraceTimer:(id)fp8;
- (void)hide:(BOOL)fp8;
- (void)show:(BOOL)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithView:(id)fp8;
- (id)initWithWindow:(id)fp8;
- (void)updateIndicators;
- (void)updateProgress;
- (void)updateDetailsLabelText:(id)fp8;
- (void)updateLabelText:(id)fp8;
- (float)progress;
- (void)setProgress:(float)fp8;
- (id)detailsLabelText;
- (void)setDetailsLabelText:(id)fp8;
- (id)labelText;
- (void)setLabelText:(id)fp8;
- (int)mode;
- (void)setMode:(int)fp8;

@end

