/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UINavigationControllerDelegate-Protocol.h"

@class ABNavigationController, NSUserDefaults, NavigationManager, RedditAPI, UISegmentedControl;

@interface MessagesViewController : _AVAudioSessionCategoryPlayback <UINavigationControllerDelegate>
{
    ABNavigationController *messagesNavigation;
    UISegmentedControl *segmentControl;
    RedditAPI *redAPI;
    NavigationManager *nc;
    NSUserDefaults *prefs;
    float measuredHeight_;
    BOOL needsHeightCorrection_;
}

- (void)setSegmentControl:(id)fp8;
- (id)segmentControl;
- (void)setMessagesNavigation:(id)fp8;
- (id)messagesNavigation;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidLoad;
- (void)drawIPADButtons;
- (void)dismissMessagesView:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)correctDimensions;
- (void)viewWillAppear:(BOOL)fp8;
- (void)reloadMessages:(id)fp8;
- (void)markAllAsRead:(id)fp8;
- (void)segmentChanged:(id)fp8;
- (void)navigationController:(id)fp8 didShowViewController:(id)fp12 animated:(BOOL)fp16;

@end

