/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMTabItem.h"

@class NSString;

@interface MessageBoxTabItem : JMTabItem
{
    NSString *_skinIconName;
}

- (void)setSkinIconName:(id)fp8;
- (id)skinIconName;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithTitle:(id)fp8 skinIconName:(id)fp12;

@end

