/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "SKProductsRequestDelegate-Protocol.h"

@class MKStoreObserver, NSMutableArray;

@interface MKStoreManager : _AVAudioSessionCategoryPlayback <SKProductsRequestDelegate>
{
    NSMutableArray *purchasableObjects;
    MKStoreObserver *storeObserver;
}

+ (void)needProAlert;
+ (void)setPriceInfoForProduct:(id)fp8;
+ (id)proUpgradePriceInfo;
+ (id)sharedManager;
+ (BOOL)featureBPurchased;
+ (BOOL)isProUpgraded;
+ (void)setDelegate:(id)fp8;
+ (id)delegate;
- (void)setStoreObserver:(id)fp8;
- (id)storeObserver;
- (void)setPurchasableObjects:(id)fp8;
- (id)purchasableObjects;
- (void).cxx_destruct;
- (void)provideContent:(id)fp8 shouldSerialize:(BOOL)fp12;
- (void)failedTransaction:(id)fp8;
- (void)buyProUpgrade;
- (BOOL)canCurrentDeviceUseFeature:(id)fp8;
- (void)buyFeature:(id)fp8;
- (void)restoreUpgrade;
- (void)buyFeatureB;
- (void)productsRequest:(id)fp8 didReceiveResponse:(id)fp12;
- (void)requestProductData;
- (id)init;

@end

