/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "SKPaymentTransactionObserver-Protocol.h"

@interface MKStoreObserver : _AVAudioSessionCategoryPlayback <SKPaymentTransactionObserver>
{
}

- (void)restoreTransaction:(id)fp8;
- (void)completeTransaction:(id)fp8;
- (void)failedTransaction:(id)fp8;
- (void)upgradeError;
- (void)paymentQueue:(id)fp8 updatedTransactions:(id)fp12;

@end

