/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString, UIImageView, UILabel;

@interface NavigationBackItemView : _AVAudioSessionCategoryPlayback
{
    BOOL _hidesBackButton;
    NSString *_title;
    UILabel *_label;
    UIImageView *_backImageView;
}

+ (id)imageForBackButton;
- (void)setBackImageView:(id)fp8;
- (id)backImageView;
- (void)setLabel:(id)fp8;
- (id)label;
- (void)setHidesBackButton:(BOOL)fp8;
- (BOOL)hidesBackButton;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (void)setHighlighted:(BOOL)fp8;
- (void)respondToStyleChangeNotification;
- (void)didReceiveLongTapGesture:(id)fp8;
- (id)initWithNavigationItem:(id)fp8;
- (void)dealloc;

@end

