/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NBaseStyledTextCell.h"

@class CommentHeaderBarOverlay, CommentSeparatorBar, ThreadLinesOverlay, VoteOverlay;

@interface NCommentCell : NBaseStyledTextCell
{
    CommentHeaderBarOverlay *_headerBar;
    ThreadLinesOverlay *_threadLinesOverlay;
    CommentSeparatorBar *_separatorBar;
    VoteOverlay *_voteOverlay;
}

+ (float)minimumHeightForCellTextForNode:(id)fp8 bounds:(struct CGRect)fp12;
+ (float)heightForCellHeaderForNode:(id)fp8 bounds:(struct CGRect)fp12;
+ (float)indentForCellTextForNode:(id)fp8 bounds:(struct CGRect)fp12;
- (void)setVoteOverlay:(id)fp8;
- (id)voteOverlay;
- (void)setSeparatorBar:(id)fp8;
- (id)separatorBar;
- (void)setThreadLinesOverlay:(id)fp8;
- (id)threadLinesOverlay;
- (void)setHeaderBar:(id)fp8;
- (id)headerBar;
- (void).cxx_destruct;
- (void)layoutCellOverlays;
- (void)updateSubviews;
- (void)createSubviews;
- (void)applyGestureRecognizers;
- (id)comment;

@end

