/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineCell.h"

@class InlineImageOverlay;

@interface NInlineImageCell : JMOutlineCell
{
    InlineImageOverlay *_imagePreviewOverlay;
}

+ (float)heightForNode:(id)fp8 tableView:(id)fp12;
- (void)setImagePreviewOverlay:(id)fp8;
- (id)imagePreviewOverlay;
- (void).cxx_destruct;
- (void)decorateCellBackground;
- (void)decorateCell;
- (void)updateSubviews;
- (void)createSubviews;

@end

