/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABToolbar.h"

@interface NoteEntryToolbar : ABToolbar
{
    id controlDelegate_;
}

- (void)setControlDelegate:(id)fp8;
- (id)controlDelegate;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)drawShadowInRect:(struct CGRect)fp8;
- (void)addPhotoOptions;
- (void)addTextMessage:(id)fp8;
- (void)addBarItem:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

