/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineCell.h"

@class JMViewOverlay, ModButtonOverlay, PostOptionsDrawerView, ThumbOverlay, VoteOverlay;

@interface NPostCell : JMOutlineCell
{
    PostOptionsDrawerView *_drawerView;
    JMViewOverlay *_commentButtonOverlay;
    JMViewOverlay *_nsfwOverlay;
    JMViewOverlay *_stickiedOverlay;
    ThumbOverlay *_thumbOverlay;
    VoteOverlay *_voteOverlay;
    JMViewOverlay *_titleOverlay;
    JMViewOverlay *_subdetailsOverlay;
    ModButtonOverlay *_modButtonOverlay;
    JMViewOverlay *_sectionDivider;
}

+ (id)imageForCommentBubble;
+ (id)bezierPathForBubbleIcon;
+ (float)heightForNode:(id)fp8 tableView:(id)fp12;
+ (float)minimumHeightForPost:(id)fp8;
+ (float)footerPadding;
+ (float)titleMarginForPost:(id)fp8;
+ (BOOL)useCompactLayout;
- (void)setSectionDivider:(id)fp8;
- (id)sectionDivider;
- (void)setModButtonOverlay:(id)fp8;
- (id)modButtonOverlay;
- (void)setSubdetailsOverlay:(id)fp8;
- (id)subdetailsOverlay;
- (void)setTitleOverlay:(id)fp8;
- (id)titleOverlay;
- (void)setVoteOverlay:(id)fp8;
- (id)voteOverlay;
- (void)setThumbOverlay:(id)fp8;
- (id)thumbOverlay;
- (void)setStickiedOverlay:(id)fp8;
- (id)stickiedOverlay;
- (void)setNsfwOverlay:(id)fp8;
- (id)nsfwOverlay;
- (void)setCommentButtonOverlay:(id)fp8;
- (id)commentButtonOverlay;
- (void)setDrawerView:(id)fp8;
- (id)drawerView;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)drawSubdetailsCompactHighlighted:(BOOL)fp8 selected:(BOOL)fp12 bounds:(struct CGRect)fp16;
- (void)layoutCellOverlays;
- (void)attachPostDrawerIfNecessary;
- (void)updateSubviews;
- (struct CGRect)rectForTitle;
- (void)createSubviews;
- (void)applyGestureRecognizers;
- (id)post;

@end

