/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NPostCell.h"

@interface NPostCell_iPhone : NPostCell
{
}

+ (float)minimumHeightForPost:(id)fp8;
+ (float)titleMarginForPost:(id)fp8;
+ (float)footerPadding;
- (void)decorateCellBackground;
- (void)layoutCellOverlays;
- (struct CGRect)rectForTitle;
- (void)createSubviews;

@end

