/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NBaseOptionCell.h"

@class JMViewOverlay;

@interface NSectionTitleCell : NBaseOptionCell
{
    JMViewOverlay *_collapseOverlay;
}

+ (float)heightForNode:(id)fp8 tableView:(id)fp12;
- (void)setCollapseOverlay:(id)fp8;
- (id)collapseOverlay;
- (void).cxx_destruct;
- (void)decorateCellBackground;
- (void)drawTitleBackground_iPhone;
- (void)updateWithNode:(id)fp8;
- (void)layoutCellOverlays;
- (void)createSubviews;

@end

