/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NBaseOptionCell.h"

@class JMViewOverlay;

@interface NSubredditCell : NBaseOptionCell
{
    JMViewOverlay *_thumbOverlay;
}

- (void)setThumbOverlay:(id)fp8;
- (id)thumbOverlay;
- (void).cxx_destruct;
- (void)imageReadyCallback:(id)fp8;
- (void)updateWithNode:(id)fp8;
- (void)layoutCellOverlays;
- (void)createSubviews;
- (void)applyGestureRecognizers;
- (id)subreddit;

@end

