/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface OARequestParameter : _AVAudioSessionCategoryPlayback
{
    NSString *name;
    NSString *value;
}

+ (id)requestParameterWithName:(id)fp8 value:(id)fp12;
- (void)setValue:(id)fp8;
- (id)value;
- (void)setName:(id)fp8;
- (id)name;
- (id)URLEncodedNameValuePair;
- (id)URLEncodedValue;
- (id)URLEncodedName;
- (void)dealloc;
- (id)initWithName:(id)fp8 value:(id)fp12;

@end

