/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface OAToken : _AVAudioSessionCategoryPlayback
{
    NSString *key;
    NSString *secret;
    NSString *sessionHandle;
}

- (void)setSessionHandle:(id)fp8;
- (id)sessionHandle;
- (void)setSecret:(id)fp8;
- (id)secret;
- (void)setKey:(id)fp8;
- (id)key;
- (int)storeInUserDefaultsWithServiceProviderName:(id)fp8 prefix:(id)fp12;
- (void)dealloc;
- (id)initWithUserDefaultsUsingServiceProviderName:(id)fp8 prefix:(id)fp12;
- (id)initWithHTTPResponseBody:(id)fp8;
- (id)initWithKey:(id)fp8 secret:(id)fp12;
- (id)init;

@end

