/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CommentEntryView.h"

#import "PhoneCommentEntryDrawerDelegate-Protocol.h"

@class ABButton, PhoneCommentEntryDrawer;

@interface PhoneCommentEntryView : CommentEntryView <PhoneCommentEntryDrawerDelegate>
{
    PhoneCommentEntryDrawer *drawer_;
    ABButton *sendButton_;
    ABButton *cancelButton_;
}

- (void)setCancelButton:(id)fp8;
- (id)cancelButton;
- (void)setSendButton:(id)fp8;
- (id)sendButton;
- (void)setDrawer:(id)fp8;
- (id)drawer;
- (void).cxx_destruct;
- (void)tabView:(id)fp8 didSelectTabAtIndex:(unsigned int)fp12;
- (void)drawerWillCollapse:(id)fp8;
- (void)drawerWillExpand:(id)fp8;
- (void)animateCommentContainerToOffset:(float)fp8;
- (void)layoutCommentComponents;
- (float)heightForTextView;
- (void)createSubviewsInFrame:(struct CGRect)fp8;

@end

