/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface PLCrashReportReportInfo : _AVAudioSessionCategoryPlayback
{
    NSString *_reportGUID;
}

- (id)reportGUID;
- (void)dealloc;
- (id)initWithReportGUID:(id)fp8;

@end

