/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface PLCrashReportProcessInfo : _AVAudioSessionCategoryPlayback
{
    NSString *_processName;
    unsigned int _processID;
    NSString *_processPath;
    NSString *_parentProcessName;
    unsigned int _parentProcessID;
    BOOL _native;
}

- (BOOL)native;
- (unsigned int)parentProcessID;
- (id)parentProcessName;
- (id)processPath;
- (unsigned int)processID;
- (id)processName;
- (void)dealloc;
- (id)initWithProcessName:(id)fp8 processID:(unsigned int)fp12 processPath:(id)fp16 parentProcessName:(id)fp20 parentProcessID:(unsigned int)fp24 native:(BOOL)fp28;

@end

