/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface PLCrashSignalHandler : _AVAudioSessionCategoryPlayback
{
    struct __darwin_sigaltstack _sigstk;
}

+ (id)sharedHandler;
- (BOOL)registerHandlerWithCallback:(void *)fp8 context:(void *)fp12 error:(id *)fp16;
- (BOOL)registerHandlerForSignal:(int)fp8 error:(id *)fp12;
- (id)init;
- (void)populateError:(id *)fp8 errorCode:(int)fp12 description:(id)fp16 cause:(id)fp20;
- (void)populateError:(id *)fp8 errnoVal:(int)fp12 description:(id)fp16;

@end

