/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface PLCrashReportStackFrameInfo : _AVAudioSessionCategoryPlayback
{
    unsigned long long _instructionPointer;
    unsigned long long _symbolStart;
    NSString *_symbolName;
}

- (id)symbolName;
- (unsigned long long)symbolStart;
- (unsigned long long)instructionPointer;
- (void)dealloc;
- (id)initWithInstructionPointer:(unsigned long long)fp8 symbolStart:(unsigned long long)fp16 symbolName:(id)fp24;

@end

