/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PocketAPIDelegate-Protocol.h"

@interface PocketAPIBlockDelegate : _AVAudioSessionCategoryPlayback <PocketAPIDelegate>
{
    id loginHandler;
    id saveHandler;
    id responseHandler;
}

+ (id)delegateWithResponseHandler:(id)fp(null);
+ (id)delegateWithSaveHandler:(id)fp(null);
+ (id)delegateWithLoginHandler:(id)fp(null);
- (void)setResponseHandler:(id)fp(null);
- (id)responseHandler;
- (void)setSaveHandler:(id)fp(null);
- (id)saveHandler;
- (void)setLoginHandler:(id)fp(null);
- (id)loginHandler;
- (void)dealloc;
- (void)pocketAPI:(id)fp8 receivedResponse:(id)fp12 forAPIMethod:(id)fp16 error:(id)fp20;
- (void)pocketAPI:(id)fp8 failedToSaveURL:(id)fp12 error:(id)fp16;
- (void)pocketAPI:(id)fp8 savedURL:(id)fp12;
- (void)pocketAPI:(id)fp8 hadLoginError:(id)fp12;
- (void)pocketAPILoggedIn:(id)fp8;

@end

