/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"
#import "PocketAPIDelegate-Protocol.h"

@class NSOperationQueue, NSString, PocketAPI;

@interface PocketAPILogin : _AVAudioSessionCategoryPlayback <NSCoding, PocketAPIDelegate>
{
    PocketAPI *API;
    NSString *uuid;
    NSString *requestToken;
    NSString *accessToken;
    NSOperationQueue *operationQueue;
    id <PocketAPIDelegate> delegate;
    BOOL didStart;
    BOOL didFinish;
    BOOL reverseAuth;
}

- (id)accessToken;
- (id)requestToken;
- (id)uuid;
- (id)API;
- (void)loginDidFinish:(BOOL)fp8;
- (void)loginDidStart;
- (void)pocketAPI:(id)fp8 hadLoginError:(id)fp12;
- (void)pocketAPILoggedIn:(id)fp8;
- (void)pocketAPI:(id)fp8 receivedRequestToken:(id)fp12;
- (void)convertRequestTokenToAccessToken;
- (void)fetchRequestToken;
- (id)redirectURL;
- (id)initWithAPI:(id)fp8 delegate:(id)fp12;
- (id)init;
- (void)dealloc;
- (void)openURL:(id)fp8;
- (void)_setReverseAuth:(BOOL)fp8;
- (void)_setRequestToken:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

