/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGalleryItem.h"

@class NSDictionary, NSString;

@interface PostGalleryItem : JMGalleryItem
{
    BOOL _saved;
    BOOL _upvoted;
    BOOL _downvoted;
    BOOL _hidden;
    BOOL _isLargeFile;
    BOOL _cancelledDueToProgressCheck;
    NSString *_url;
    int _score;
    int _numComments;
    NSDictionary *_postDictionary;
}

+ (id)linkedURLForPostDictionary:(id)fp8;
+ (BOOL)shouldExcludeBasedOnKeyword:(id)fp8;
- (void)setPostDictionary:(id)fp8;
- (id)postDictionary;
- (void)setNumComments:(int)fp8;
- (int)numComments;
- (void)setScore:(int)fp8;
- (int)score;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)setCancelledDueToProgressCheck:(BOOL)fp8;
- (BOOL)cancelledDueToProgressCheck;
- (void)setIsLargeFile:(BOOL)fp8;
- (BOOL)isLargeFile;
- (void)setHidden:(BOOL)fp8;
- (BOOL)hidden;
- (void)setDownvoted:(BOOL)fp8;
- (BOOL)downvoted;
- (void)setUpvoted:(BOOL)fp8;
- (BOOL)upvoted;
- (void)setSaved:(BOOL)fp8;
- (BOOL)saved;
- (void).cxx_destruct;
- (id)recommendedSubtitle;
- (id)initWithPostDictionary:(id)fp8 ignoreNSFWTag:(BOOL)fp12;

@end

