/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "JMSliderDelegate-Protocol.h"

@class JMSlider, UILabel, UIView;

@interface PostsFooterCoordinator : _AVAudioSessionCategoryPlayback <JMSliderDelegate>
{
    BOOL _isShowingLoadingIndicator;
    BOOL _dragTriggeredLoadMore;
    UIView *view_;
    id <PostsFooterDelegate> _delegate;
    JMSlider *_sliderView;
    UILabel *_pullLabel;
    float _lastDragOffset;
}

- (void)setDragTriggeredLoadMore:(BOOL)fp8;
- (BOOL)dragTriggeredLoadMore;
- (void)setLastDragOffset:(float)fp8;
- (float)lastDragOffset;
- (void)setIsShowingLoadingIndicator:(BOOL)fp8;
- (BOOL)isShowingLoadingIndicator;
- (void)setPullLabel:(id)fp8;
- (id)pullLabel;
- (void)setSliderView:(id)fp8;
- (id)sliderView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setView:(id)fp8;
- (void).cxx_destruct;
- (void)handleScrolling;
- (void)handleDragRelease;
- (void)setShowLoadingIndicator:(BOOL)fp8;
- (id)sliderTrackViewForSlider:(id)fp8;
- (id)sliderCenterViewForSlider:(id)fp8;
- (void)slider:(id)fp8 didSelect:(int)fp12;
- (void)slider:(id)fp8 didHighlight:(BOOL)fp12;
- (void)setSliderTrainingComplete;
- (BOOL)needsSliderTraining;
- (id)view;
- (void)loadView;
- (float)heightForFooter;
- (id)initWithDelegate:(id)fp8;

@end

