/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class Post, UIButton;

@interface PostModerationControlView : _AVAudioSessionCategoryPlayback
{
    id _onCancelTap;
    id _onModerationStateChange;
    id _onModerationWillShowTemplateSelectionScreen;
    id _onModerationMessageSentResponse;
    UIButton *_messageButton;
    UIButton *_removeButton;
    UIButton *_approveButton;
    Post *_post;
}

+ (id)resizableModButtonBackgroundWithColor:(id)fp8;
+ (id)modCancelButtonImage;
+ (id)roundedModButton;
- (void)setPost:(id)fp8;
- (id)post;
- (void)setApproveButton:(id)fp8;
- (id)approveButton;
- (void)setRemoveButton:(id)fp8;
- (id)removeButton;
- (void)setMessageButton:(id)fp8;
- (id)messageButton;
- (void)setOnModerationMessageSentResponse:(id)fp(null);
- (id)onModerationMessageSentResponse;
- (void)setOnModerationWillShowTemplateSelectionScreen:(id)fp(null);
- (id)onModerationWillShowTemplateSelectionScreen;
- (void)setOnModerationStateChange:(id)fp(null);
- (id)onModerationStateChange;
- (void)setOnCancelTap:(id)fp(null);
- (id)onCancelTap;
- (void).cxx_destruct;
- (void)updateWithPost:(id)fp8;
- (void)updateModTools;
- (void)updateRemoveButtonAppearance;
- (void)didTapCancelButton;
- (void)didTapMessageButton;
- (void)didTapRemoveButton;
- (void)i_removePostMarkAsSpam:(BOOL)fp8;
- (void)didTapApproveButton;
- (BOOL)removed;
- (BOOL)approved;
- (id)initWithFrame:(struct CGRect)fp8;

@end

