/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PostsOrderToolbarDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class JMTabView, NSString, PostsOrderToolbar, UISearchBar, UIView;

@interface PostsHeaderCoordinator : _AVAudioSessionCategoryPlayback <PostsOrderToolbarDelegate, UISearchBarDelegate>
{
    BOOL _searchRestrictToSubreddit;
    BOOL _showingSearch;
    BOOL _showsModOptions;
    UIView *view_;
    JMTabView *orderSelectTabView_;
    UIView *postSearchView_;
    id <PostsHeaderDelegate> _delegate;
    NSString *_sortOrder;
    NSString *_topTimespan;
    NSString *_searchSortOrder;
    NSString *_searchQuery;
    int _modFolderSelection;
    id _executeOnChange;
    PostsOrderToolbar *_headerBar;
    UISearchBar *_searchBar;
}

- (void)setShowsModOptions:(BOOL)fp8;
- (BOOL)showsModOptions;
- (void)setSearchBar:(id)fp8;
- (id)searchBar;
- (void)setHeaderBar:(id)fp8;
- (id)headerBar;
- (void)setExecuteOnChange:(id)fp(null);
- (id)executeOnChange;
- (void)setModFolderSelection:(int)fp8;
- (int)modFolderSelection;
- (void)setShowingSearch:(BOOL)fp8;
- (BOOL)showingSearch;
- (void)setSearchRestrictToSubreddit:(BOOL)fp8;
- (BOOL)searchRestrictToSubreddit;
- (void)setSearchQuery:(id)fp8;
- (id)searchQuery;
- (void)setSearchSortOrder:(id)fp8;
- (id)searchSortOrder;
- (void)setTopTimespan:(id)fp8;
- (id)topTimespan;
- (void)setSortOrder:(id)fp8;
- (id)sortOrder;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setPostSearchView:(id)fp8;
- (id)postSearchView;
- (void)setOrderSelectTabView:(id)fp8;
- (id)orderSelectTabView;
- (void)setView:(id)fp8;
- (void).cxx_destruct;
- (BOOL)postsOrderToolbarShouldShowModerationIcon:(id)fp8;
- (void)postsOrderToolbar:(id)fp8 didChangeScopeRestriction:(BOOL)fp12;
- (BOOL)postsOrderToolbarShouldShowScopeIcon:(id)fp8;
- (void)postsOrderToolbar:(id)fp8 didEnterSearchQuery:(id)fp12;
- (void)postsOrderToolbar:(id)fp8 didTapOrderButtonWithSearchActive:(BOOL)fp12;
- (void)postsOrderToolbarDidTapModerationButton:(id)fp8;
- (void)enableModFeatures;
- (BOOL)modFeaturesEnabled;
- (void)showSearchOptions;
- (void)showSortOrderOptions;
- (void)showModFolderOptions;
- (void)showTopTimespanSelector;
- (void)postsOrderToolbar:(id)fp8 didChangeSearchActive:(BOOL)fp12 animated:(BOOL)fp16;
- (void)postsOrderToolbar:(id)fp8 willChangeSearchActive:(BOOL)fp12 animated:(BOOL)fp16;
- (id)titleForPostsOrderToolbarButton;
- (void)showSelectionSheetWithTitle:(id)fp8 options:(id)fp12 onComplete:(id)fp(null);
- (void)searchBarSearchButtonClicked:(id)fp8;
- (void)searchBarCancelButtonClicked:(id)fp8;
- (void)searchBarTextDidEndEditing:(id)fp8;
- (void)searchBarTextDidBeginEditing:(id)fp8;
- (void)searchBar:(id)fp8 textDidChange:(id)fp12;
- (void)searchBarResultsListButtonClicked:(id)fp8;
- (void)setShowSearchScopeBar:(BOOL)fp8;
- (void)showSearch;
- (void)hideSearch;
- (void)handleScrolling;
- (id)searchView;
- (id)sortOrderSelectTabView;
- (void)changeModerationFolderTo:(int)fp8;
- (void)changeSearchSortOrderTo:(id)fp8;
- (void)changeTopTimespanTo:(id)fp8;
- (void)changeSortOrderTo:(id)fp8;
- (id)view;
- (void)layoutHeaderView;
- (void)loadView;
- (id)initWithDelegate:(id)fp8 onChange:(id)fp(null);

@end

