/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMTableNode.h"

@class NSString, UIImage;

@interface PostDetailNode : JMTableNode
{
    NSString *key_;
    NSString *title_;
    NSString *value_;
    NSString *placeholder_;
    UIImage *icon_;
    UIImage *disclosureIcon_;
}

+ (SEL)selectedAction;
+ (Class)cellClass;
- (void)setDisclosureIcon:(id)fp8;
- (id)disclosureIcon;
- (void)setIcon:(id)fp8;
- (id)icon;
- (void)setPlaceholder:(id)fp8;
- (id)placeholder;
- (void)setValue:(id)fp8;
- (id)value;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setKey:(id)fp8;
- (id)key;
- (void).cxx_destruct;

@end

