/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "VotableElement.h"

#import "NSCoding-Protocol.h"

@class NSAttributedString, NSString;

@interface Post : VotableElement <NSCoding>
{
    BOOL visited_;
    BOOL _stickied;
    BOOL _nsfw;
    BOOL _saved;
    BOOL _hidden;
    BOOL _selfPost;
    BOOL _reported;
    int score_;
    NSString *_title;
    NSString *_selftext;
    NSString *_selftextHtml;
    NSString *_url;
    NSString *_domain;
    NSString *_rawThumbnail;
    int _numComments;
    unsigned int _numberOfImagesInCommentThread;
    NSAttributedString *_cachedStyledTitle;
    NSString *_contextCommentIdent;
}

+ (id)postSkeletonFromRedditUrl:(id)fp8;
+ (id)postFromDictionary:(id)fp8;
+ (id)fetchPostsForPath:(id)fp8 params:(id)fp12 onComplete:(id)fp(null);
- (void)setContextCommentIdent:(id)fp8;
- (id)contextCommentIdent;
- (void)setCachedStyledTitle:(id)fp8;
- (id)cachedStyledTitle;
- (void)setNumberOfImagesInCommentThread:(unsigned int)fp8;
- (unsigned int)numberOfImagesInCommentThread;
- (void)setNumComments:(int)fp8;
- (int)numComments;
- (void)setReported:(BOOL)fp8;
- (BOOL)reported;
- (void)setSelfPost:(BOOL)fp8;
- (BOOL)selfPost;
- (void)setHidden:(BOOL)fp8;
- (BOOL)hidden;
- (void)setSaved:(BOOL)fp8;
- (BOOL)saved;
- (void)setNsfw:(BOOL)fp8;
- (BOOL)nsfw;
- (void)setStickied:(BOOL)fp8;
- (BOOL)stickied;
- (void)setRawThumbnail:(id)fp8;
- (id)rawThumbnail;
- (void)setDomain:(id)fp8;
- (id)domain;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)setSelftextHtml:(id)fp8;
- (id)selftextHtml;
- (void)setSelftext:(id)fp8;
- (id)selftext;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setVisited:(BOOL)fp8;
- (void)setScore:(int)fp8;
- (int)score;
- (void).cxx_destruct;
- (id)linkTypeIconName;
- (BOOL)needsNSFWWarning;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (int)linkType;
- (BOOL)visited;
- (BOOL)isInVisitedList;
- (void)markVisited;
- (id)tinyDomain;
- (id)thumbnail;
- (void)updateVisitedStatus;
- (void)report;
- (void)toggleHide;
- (void)toggleSaved;
- (void)drawTimeAgoInRect:(struct CGRect)fp8 context:(struct CGContext *)fp24;
- (void)drawCommentCountInRect:(struct CGRect)fp8 context:(struct CGContext *)fp24;
- (void)drawCompactSubdetailsInRect:(struct CGRect)fp8 context:(struct CGContext *)fp24;
- (void)drawTitleCenteredVerticallyInRect:(struct CGRect)fp8 context:(struct CGContext *)fp24;
- (float)titleHeightConstrainedToWidth:(float)fp8;
- (float)_heightForTitleConstrainedToWidth:(float)fp8;
- (void)preprocessStyles;
- (void)flushCachedStyles;
- (id)styledTitleWithDetails;
- (id)styledTitle;
- (void)setHeightCache:(id)fp8;
- (id)heightCache;
- (id)styledTitleWithDetails_iPad;
- (void)drawSubdetailsInRect_iPad:(struct CGRect)fp8 context:(struct CGContext *)fp24;
- (void)drawSubdetailsInRect_iPhone:(struct CGRect)fp8 context:(struct CGContext *)fp24;

@end

