/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSObject<PostsOrderToolbarDelegate>, UIButton, UIImageView, UITextField;

@interface PostsOrderToolbar : _AVAudioSessionCategoryPlayback <UITextFieldDelegate>
{
    BOOL _i_searchActive;
    BOOL _i_scopeRestricted;
    NSObject<PostsOrderToolbarDelegate> *_delegate;
    UIImageView *_backgroundImageView;
    UITextField *_searchTextField;
    UIButton *_sortButton;
    UIButton *_searchIconButton;
    UIButton *_scopeButton;
    UIButton *_modButton;
}

+ (id)imageForModIndicatorButton;
+ (id)imageForSortButtonBackgroundHighlighted:(BOOL)fp8;
+ (id)imageForSearchField;
+ (id)imageForBarBackground;
+ (id)imageForScopeButtonHighlighted:(BOOL)fp8;
- (void)setI_scopeRestricted:(BOOL)fp8;
- (BOOL)i_scopeRestricted;
- (void)setI_searchActive:(BOOL)fp8;
- (BOOL)i_searchActive;
- (void)setModButton:(id)fp8;
- (id)modButton;
- (void)setScopeButton:(id)fp8;
- (id)scopeButton;
- (void)setSearchIconButton:(id)fp8;
- (id)searchIconButton;
- (void)setSortButton:(id)fp8;
- (id)sortButton;
- (void)setSearchTextField:(id)fp8;
- (id)searchTextField;
- (void)setBackgroundImageView:(id)fp8;
- (id)backgroundImageView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)focusOnSearchField;
- (void)cancelActiveSearch;
- (void)updateSearchButtonIcon;
- (void)setSearchActive:(BOOL)fp8 animated:(BOOL)fp12;
- (void)modButtonTapped;
- (void)sortButtonTapped;
- (void)searchIconTapped;
- (void)enableScopeByDefault;
- (void)scopeButtonTapped;
- (void)respondToStyleChangeNotification;
- (void)setButtonTitle:(id)fp8 animated:(BOOL)fp12;
- (BOOL)showsModerationIndicator;
- (BOOL)shouldShowScope;
- (id)initWithFrame:(struct CGRect)fp8 delegate:(id)fp24;
- (void)dealloc;

@end

