/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableData, NSString;

@interface QSHttpClient : _AVAudioSessionCategoryPlayback
{
    NSString *_strUrl;
    NSString *_strHttpMethod;
    int _intTimeoutInterval;
    int _intHttpStatusCode;
    NSMutableData *_objResponseData;
    int _intRequestDataSize;
    int _intResponseDataSize;
    int _intTag;
    int _intArbitraryIdentifier;
    id <QSHttpClientDelegate> _objDelegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setArbitraryIdentifier:(int)fp8;
- (int)arbitraryIdentifier;
- (void)setTag:(int)fp8;
- (int)tag;
- (void)set_objResponseData:(id)fp8;
- (id)responseData;
- (void)set_intHttpStatusCode:(int)fp8;
- (int)httpStatusCode;
- (void)setTimeoutInterval:(int)fp8;
- (int)timeoutInterval;
- (void)setHttpMethod:(id)fp8;
- (id)httpMethod;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)dealloc;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didSendBodyData:(int)fp12 totalBytesWritten:(int)fp16 totalBytesExpectedToWrite:(int)fp20;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (id)getResponseAsRawData;
- (id)getResponseAsString;
- (void)sendWithData:(id)fp8 StreamFlag:(_Bool)fp12;
- (void)sendFile:(id)fp8;
- (void)sendString:(id)fp8;
- (void)cleanupFromPreviousRequests;
- (id)initWithUrl:(id)fp8 HttpMethod:(id)fp12;

@end

