/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSUserDefaults, NavigationManager, UIImageView, UITextField;

@interface ScreenLockViewController : _AVAudioSessionCategoryPlayback <UITextFieldDelegate>
{
    UITextField *lockTextField;
    NSUserDefaults *prefs;
    NavigationManager *nc;
    UIImageView *_lockImageView;
}

- (void)setLockImageView:(id)fp8;
- (id)lockImageView;
- (void)setLockTextField:(id)fp8;
- (id)lockTextField;
- (void).cxx_destruct;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;

@end

