/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "OptionNode.h"

@interface SectionTitleNode : OptionNode
{
    BOOL _collapsable;
}

+ (Class)cellClass;
+ (id)nodeForTitle:(id)fp8;
- (void)setCollapsable:(BOOL)fp8;
- (BOOL)collapsable;

@end

