/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineNode.h"

@class UIColor;

@interface SectionSpacerNode : JMOutlineNode
{
    UIColor *_backgroundColor;
}

+ (Class)cellClass;
+ (id)spacerNode;
- (void)setBackgroundColor:(id)fp8;
- (id)backgroundColor;
- (void).cxx_destruct;

@end

