/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDate, TemplatePrefs, UserSubredditPreferences;

@interface SessionManager : _AVAudioSessionCategoryPlayback
{
    UserSubredditPreferences *_subredditPrefs;
    NSDate *_sessionStart;
    TemplatePrefs *_templatePrefs;
}

+ (id)manager;
- (void)setTemplatePrefs:(id)fp8;
- (id)templatePrefs;
- (void)setSessionStart:(id)fp8;
- (id)sessionStart;
- (void)setSubredditPrefs:(id)fp8;
- (id)subredditPrefs;
- (void).cxx_destruct;
- (id)sharedTemplatePrefs;
- (void)resetGroups;
- (void)startSession;
- (void)switchUserSubredditPreferencesToAuthenticatedUser;
- (id)init;

@end

