/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSMutableArray, SHKItem;

@interface SHKActionSheet : _AVAudioSessionCategoryPlayback <UIActionSheetDelegate>
{
    NSMutableArray *_sharers;
    SHKItem *_item;
    id <SHKShareItemDelegate> _shareDelegate;
}

+ (id)actionSheetForItem:(id)fp8;
- (void)setShareDelegate:(id)fp8;
- (id)shareDelegate;
- (void)setItem:(id)fp8;
- (id)item;
- (void)setSharers:(id)fp8;
- (id)sharers;
- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;
- (void)dealloc;

@end

