/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIActivityIndicatorView, UILabel, UIProgressView;

@interface SHKActivityIndicator : _AVAudioSessionCategoryPlayback
{
    UILabel *_centerMessageLabel;
    UILabel *_subMessageLabel;
    UIActivityIndicatorView *_spinner;
    UIProgressView *_progress;
}

+ (id)currentIndicator;
- (void)setProgress:(id)fp8;
- (id)progress;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setSubMessageLabel:(id)fp8;
- (id)subMessageLabel;
- (void)setCenterMessageLabel:(id)fp8;
- (id)centerMessageLabel;
- (void)setProperRotation:(BOOL)fp8;
- (void)setProperRotation;
- (void)hideProgress;
- (void)showProgress;
- (void)hideSpinner;
- (void)showSpinner;
- (void)setSubMessage:(id)fp8;
- (void)setCenterMessage:(id)fp8;
- (void)displayCompleted:(id)fp8;
- (void)displayActivity:(id)fp8;
- (void)hidden;
- (void)persist;
- (void)hide;
- (void)hideAfterDelay;
- (void)show;
- (void)dealloc;

@end

