/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKSharer.h"

@interface SHKEvernote : SHKSharer
{
}

+ (void)logout;
+ (BOOL)canShare;
+ (BOOL)requiresAuthentication;
+ (BOOL)canShareFile:(id)fp8;
+ (BOOL)canShareText;
+ (BOOL)canShareImage;
+ (BOOL)canShareURL;
+ (id)sharerTitle;
+ (void)fillEvernoteSessionWithAppConfig;
- (id)enMediaTagWithResource:(id)fp8 width:(float)fp12 height:(float)fp16;
- (BOOL)send;
- (void)shareFormValidate:(id)fp8;
- (id)shareFormFieldsForType:(int)fp8;
- (void)promptAuthorization;
- (BOOL)isAuthorized;
- (id)init;

@end

