/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKFormFieldCell.h"

@class UISwitch;

@interface SHKFormFieldCellSwitch : SHKFormFieldCell
{
    UISwitch *mySwitch;
}

- (void)setMySwitch:(id)fp8;
- (id)mySwitch;
- (void)switchChange:(id)fp8;
- (void)setupWithSettings:(id)fp8;
- (void)setupLayout;
- (void)dealloc;

@end

