/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKSharer.h"

@class NSMutableDictionary;

@interface SHKGoogleReader : SHKSharer
{
    NSMutableDictionary *session;
}

+ (id)authorizationFormFields;
+ (id)authorizationFormCaption;
+ (BOOL)canShareURL;
+ (id)sharerTitle;
- (void)setSession:(id)fp8;
- (id)session;
- (void)shareFormSave:(id)fp8;
- (void)sendFinished:(id)fp8;
- (void)sendWithToken:(id)fp8;
- (void)tokenFinished:(id)fp8;
- (BOOL)send;
- (void)signRequest:(id)fp8;
- (id)shareFormFieldsForType:(int)fp8;
- (void)authFinished:(id)fp8;
- (void)getSession:(id)fp8 password:(id)fp12;
- (void)authorizationFormValidate:(id)fp8;
- (void)dealloc;

@end

