/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, NSURL, SHKFile, UIImage;

@interface SHKItem : _AVAudioSessionCategoryPlayback <NSCoding>
{
    BOOL _isMailHTML;
    BOOL _mailShareWithAppSignature;
    int _shareType;
    NSString *_title;
    NSString *_text;
    NSArray *_tags;
    NSURL *_URL;
    int _URLContentType;
    UIImage *_image;
    SHKFile *_file;
    int _printOutputType;
    NSArray *_mailToRecipients;
    float _mailJPGQuality;
    NSString *_facebookURLSharePictureURI;
    NSString *_facebookURLShareDescription;
    NSArray *_textMessageToRecipients;
    NSMutableDictionary *_custom;
    struct CGRect _popOverSourceRect;
}

+ (id)file:(id)fp8 filename:(id)fp12 mimeType:(id)fp16 title:(id)fp20;
+ (id)fileData:(id)fp8 filename:(id)fp12 title:(id)fp16;
+ (id)filePath:(id)fp8 title:(id)fp12;
+ (id)text:(id)fp8;
+ (id)image:(id)fp8 title:(id)fp12;
+ (id)image:(id)fp8;
+ (id)URL:(id)fp8 title:(id)fp12 contentType:(int)fp16;
+ (id)URL:(id)fp8 title:(id)fp12;
+ (id)URL:(id)fp8;
- (void)setCustom:(id)fp8;
- (id)custom;
- (void)setPopOverSourceRect:(struct CGRect)fp8;
- (struct CGRect)popOverSourceRect;
- (void)setTextMessageToRecipients:(id)fp8;
- (id)textMessageToRecipients;
- (void)setFacebookURLShareDescription:(id)fp8;
- (id)facebookURLShareDescription;
- (void)setFacebookURLSharePictureURI:(id)fp8;
- (id)facebookURLSharePictureURI;
- (void)setMailShareWithAppSignature:(BOOL)fp8;
- (BOOL)mailShareWithAppSignature;
- (void)setMailJPGQuality:(float)fp8;
- (float)mailJPGQuality;
- (void)setIsMailHTML:(BOOL)fp8;
- (BOOL)isMailHTML;
- (void)setMailToRecipients:(id)fp8;
- (id)mailToRecipients;
- (void)setPrintOutputType:(int)fp8;
- (int)printOutputType;
- (void)setFile:(id)fp8;
- (id)file;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setURLContentType:(int)fp8;
- (int)URLContentType;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)setTags:(id)fp8;
- (id)tags;
- (void)setText:(id)fp8;
- (id)text;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setShareType:(int)fp8;
- (int)shareType;
- (id)shareTypeToString:(int)fp8;
- (id)description;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (BOOL)customBoolForSwitchKey:(id)fp8;
- (id)customValueForKey:(id)fp8;
- (void)setCustomValue:(id)fp8 forKey:(id)fp12;
- (void)convertImageShareToFileShareOfType:(int)fp8 quality:(float)fp12;
- (void)setExtensionPropertiesDefaultValues;
- (id)init;
- (void)dealloc;

@end

