/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKSharer.h"

@class NSDictionary, NSString, NSURL, OAConsumer, OAToken;

@interface SHKOAuthSharer : SHKSharer
{
    NSString *consumerKey;
    NSString *secretKey;
    NSURL *authorizeCallbackURL;
    NSURL *authorizeURL;
    NSURL *accessURL;
    NSURL *requestURL;
    OAConsumer *consumer;
    OAToken *requestToken;
    OAToken *accessToken;
    id <OASignatureProviding> signatureProvider;
    NSDictionary *authorizeResponseQueryVars;
}

+ (void)logout;
+ (void)deleteStoredAccessToken;
- (void)setAuthorizeResponseQueryVars:(id)fp8;
- (id)authorizeResponseQueryVars;
- (void)setSignatureProvider:(id)fp8;
- (id)signatureProvider;
- (void)setAccessToken:(id)fp8;
- (id)accessToken;
- (void)setRequestToken:(id)fp8;
- (id)requestToken;
- (void)setConsumer:(id)fp8;
- (id)consumer;
- (void)setAccessURL:(id)fp8;
- (id)accessURL;
- (void)setRequestURL:(id)fp8;
- (id)requestURL;
- (void)setAuthorizeURL:(id)fp8;
- (id)authorizeURL;
- (void)setAuthorizeCallbackURL:(id)fp8;
- (id)authorizeCallbackURL;
- (void)setSecretKey:(id)fp8;
- (id)secretKey;
- (void)setConsumerKey:(id)fp8;
- (id)consumerKey;
- (void)refreshToken;
- (BOOL)restoreAccessToken;
- (void)storeAccessToken;
- (void)tokenAccessTicket:(id)fp8 didFailWithError:(id)fp12;
- (void)tokenAccessTicket:(id)fp8 didFinishWithData:(id)fp12;
- (void)tokenAccessModifyRequest:(id)fp8;
- (void)tokenAccess:(BOOL)fp8;
- (void)tokenAccess;
- (void)tokenAuthorizeCancelledView:(id)fp8;
- (void)tokenAuthorizeView:(id)fp8 didFinishWithSuccess:(BOOL)fp12 queryParams:(id)fp16 error:(id)fp20;
- (void)tokenAuthorize;
- (void)tokenRequestTicket:(id)fp8 didFailWithError:(id)fp12;
- (void)tokenRequestTicket:(id)fp8 didFinishWithData:(id)fp12;
- (void)tokenRequestModifyRequest:(id)fp8;
- (void)tokenRequest;
- (void)promptAuthorization;
- (BOOL)isAuthorized;
- (void)dealloc;

@end

