/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDictionary, NSHTTPURLResponse, NSMutableData, NSString, NSURL, NSURLConnection;

@interface SHKRequest : _AVAudioSessionCategoryPlayback
{
    NSURL *url;
    NSString *params;
    NSString *method;
    NSDictionary *headerFields;
    id delegate;
    SEL isFinishedSelector;
    NSURLConnection *connection;
    NSHTTPURLResponse *response;
    NSDictionary *headers;
    NSMutableData *data;
    NSString *result;
    BOOL success;
}

- (void)setSuccess:(BOOL)fp8;
- (BOOL)success;
- (void)setConnection:(id)fp8;
- (id)connection;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setHeaders:(id)fp8;
- (id)headers;
- (void)setResult:(id)fp8;
- (void)setData:(id)fp8;
- (id)data;
- (void)setIsFinishedSelector:(SEL)fp8;
- (SEL)isFinishedSelector;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setHeaderFields:(id)fp8;
- (id)headerFields;
- (void)setMethod:(id)fp8;
- (id)method;
- (void)setParams:(id)fp8;
- (id)params;
- (void)setUrl:(id)fp8;
- (id)url;
- (id)description;
- (id)getResult;
- (void)finish;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)start;
- (id)initWithURL:(id)fp8 params:(id)fp12 delegate:(id)fp16 isFinishedSelector:(SEL)fp20 method:(id)fp24 autostart:(BOOL)fp28;
- (void)dealloc;

@end

