/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView;

@interface SplashView : _AVAudioSessionCategoryPlayback
{
    UIImageView *splashImageView_;
}

+ (void)hide;
+ (void)bringSplashToFront;
+ (void)show;
+ (id)viewToAttach;
- (void)setSplashImageView:(id)fp8;
- (id)splashImageView;
- (void).cxx_destruct;
- (void)startHiding;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

