/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface SSKeychain : _AVAudioSessionCategoryPlayback
{
}

+ (id)_errorWithCode:(long)fp8;
+ (id)_queryForService:(id)fp8 account:(id)fp12;
+ (void)setAccessibilityType:(void *)fp8;
+ (void *)accessibilityType;
+ (BOOL)setPasswordData:(id)fp8 forService:(id)fp12 account:(id)fp16 error:(id *)fp20;
+ (BOOL)setPasswordData:(id)fp8 forService:(id)fp12 account:(id)fp16;
+ (BOOL)setPassword:(id)fp8 forService:(id)fp12 account:(id)fp16 error:(id *)fp20;
+ (BOOL)setPassword:(id)fp8 forService:(id)fp12 account:(id)fp16;
+ (BOOL)deletePasswordForService:(id)fp8 account:(id)fp12 error:(id *)fp16;
+ (BOOL)deletePasswordForService:(id)fp8 account:(id)fp12;
+ (id)passwordDataForService:(id)fp8 account:(id)fp12 error:(id *)fp16;
+ (id)passwordDataForService:(id)fp8 account:(id)fp12;
+ (id)passwordForService:(id)fp8 account:(id)fp12 error:(id *)fp16;
+ (id)passwordForService:(id)fp8 account:(id)fp12;
+ (id)accountsForService:(id)fp8 error:(id *)fp12;
+ (id)accountsForService:(id)fp8;
+ (id)allAccounts:(id *)fp8;
+ (id)allAccounts;

@end

