/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "OptionNode.h"

@class Subreddit;

@interface SubredditNode : OptionNode
{
    BOOL _hiddenThumbnail;
    Subreddit *_subreddit;
}

+ (Class)cellClass;
+ (id)nodeForSubreddit:(id)fp8;
- (void)setHiddenThumbnail:(BOOL)fp8;
- (BOOL)hiddenThumbnail;
- (void)setSubreddit:(id)fp8;
- (id)subreddit;
- (void).cxx_destruct;
- (id)initWithSubreddit:(id)fp8;

@end

