/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMGalleryViewController.h"

@class AFJSONRequestOperation, NSString, PostInteractionToolbar;

@interface SubredditGalleryViewController : JMGalleryViewController
{
    BOOL _loadingPosts;
    BOOL _shouldUseSecondLastPostIdWhenLoading;
    NSString *_galleryTitle;
    NSString *_subredditUrl;
    NSString *_additionalParams;
    NSString *_lastPostId;
    NSString *_secondLastPostId;
    AFJSONRequestOperation *_loadPostsOperation;
    PostInteractionToolbar *_postInteractionToolbar;
}

- (void)setShouldUseSecondLastPostIdWhenLoading:(BOOL)fp8;
- (BOOL)shouldUseSecondLastPostIdWhenLoading;
- (void)setLoadingPosts:(BOOL)fp8;
- (BOOL)loadingPosts;
- (void)setPostInteractionToolbar:(id)fp8;
- (id)postInteractionToolbar;
- (void)setLoadPostsOperation:(id)fp8;
- (id)loadPostsOperation;
- (void)setSecondLastPostId:(id)fp8;
- (id)secondLastPostId;
- (void)setLastPostId:(id)fp8;
- (id)lastPostId;
- (void)setAdditionalParams:(id)fp8;
- (id)additionalParams;
- (void)setSubredditUrl:(id)fp8;
- (id)subredditUrl;
- (void)setGalleryTitle:(id)fp8;
- (id)galleryTitle;
- (void).cxx_destruct;
- (void)showMomentaryHudMessage:(id)fp8 minDisplayTime:(double)fp12;
- (id)generateRequestForNextPageOfResults;
- (id)generateRelativeRedditUrlForNextPage;
- (id)titleForGridToolbar;
- (void)showSharingOptionsForPost:(id)fp8;
- (void)showCommentsForPost:(id)fp8;
- (void)apiSavePost:(id)fp8;
- (void)apiHidePost:(id)fp8;
- (void)apiDownvotePost:(id)fp8;
- (void)apiUpvotePost:(id)fp8;
- (void)didLongPressEndOnGalleryItem:(id)fp8;
- (void)didLongPressBeginOnGalleryItem:(id)fp8;
- (void)didThreeFingerTapOnGalleryItem:(id)fp8;
- (void)didTwoFingerTapOnGalleryItem:(id)fp8;
- (id)interactionToolbarView;
- (void)toggleDownvoteItem:(id)fp8;
- (void)toggleUpvoteItem:(id)fp8;
- (void)toggleHideItem:(id)fp8;
- (void)toggleSaveItem:(id)fp8;
- (void)fetchPosts;
- (void)appendGalleryItemsFromJSON:(id)fp8;
- (BOOL)postItemAlreadyExistsInGallery:(id)fp8;
- (void)scheduleAdditionOfGalleryItemsWhenScrollingIsIdle:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)didHitLastPage;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)dismiss;
- (void)resetNetworkConnections;
- (id)initWithSubredditUrl:(id)fp8 additionalParams:(id)fp12 title:(id)fp16;

@end

