/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TException.h"

@interface TApplicationException : TException
{
    int mType;
}

+ (id)exceptionWithType:(int)fp8 reason:(id)fp12;
+ (id)read:(id)fp8;
- (void)write:(id)fp8;
- (id)initWithType:(int)fp8 reason:(id)fp12;

@end

