/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface TemplateToken : _AVAudioSessionCategoryPlayback
{
    NSString *_title;
    NSString *_tokenIdent;
    id _tokenReplacer;
}

- (void)setTokenReplacer:(id)fp(null);
- (id)tokenReplacer;
- (void)setTokenIdent:(id)fp8;
- (id)tokenIdent;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)replacerString;
- (void)applyTokenToMutableString:(id)fp8;
- (id)escapedToken;
- (id)initWithTokenIdent:(id)fp8 title:(id)fp12 tokenReplacer:(id)fp(null);

@end

