/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface TemplateGroup : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *_title;
    NSString *_ident;
    NSMutableArray *_templates;
}

+ (id)groupWithTitle:(id)fp8;
- (void)setTemplates:(id)fp8;
- (id)templates;
- (void)setIdent:(id)fp8;
- (id)ident;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)stockTemplates;
- (id)userCreatedTemplates;
- (void)i_removeTemplate:(id)fp8;
- (void)i_addTemplate:(id)fp8;
- (void)i_insertTemplate:(id)fp8 atIndex:(unsigned int)fp12;
- (BOOL)containsTemplate:(id)fp8;
- (id)itemMatchingTemplate:(id)fp8;
- (void)addRemovalSampleTemplates;
- (void)addApprovalSampleTemplates;
- (void)appendSampleWithTitle:(id)fp8 body:(id)fp12 isComment:(BOOL)fp16;

@end

