/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMTextViewController.h"

#import "JMTextViewDelegate-Protocol.h"

@class NSArray, NSString, Template, TemplateEditToolsView, UITextField;

@interface TemplateDetailViewController : JMTextViewController <JMTextViewDelegate>
{
    BOOL _useSendAsDoneButtonTitle;
    BOOL _hidesNavbarTextField;
    id _onTemplateEditComplete;
    NSString *_defaultTemplateTitle;
    Template *_tPlate;
    int _mode;
    NSArray *_tokens;
    TemplateEditToolsView *_toolsView;
    int _sendPreference;
    UITextField *_templateTitleTextField;
}

- (void)setTemplateTitleTextField:(id)fp8;
- (id)templateTitleTextField;
- (void)setSendPreference:(int)fp8;
- (int)sendPreference;
- (void)setToolsView:(id)fp8;
- (id)toolsView;
- (void)setTokens:(id)fp8;
- (id)tokens;
- (void)setMode:(int)fp8;
- (int)mode;
- (void)setTPlate:(id)fp8;
- (id)tPlate;
- (void)setDefaultTemplateTitle:(id)fp8;
- (id)defaultTemplateTitle;
- (void)setHidesNavbarTextField:(BOOL)fp8;
- (BOOL)hidesNavbarTextField;
- (void)setUseSendAsDoneButtonTitle:(BOOL)fp8;
- (BOOL)useSendAsDoneButtonTitle;
- (void)setOnTemplateEditComplete:(id)fp(null);
- (id)onTemplateEditComplete;
- (void).cxx_destruct;
- (void)cancel;
- (void)textViewDidChange:(id)fp8;
- (void)textViewDidEnterValue:(id)fp8 propertyKey:(id)fp12;
- (float)heightForTextViewInOrientation:(int)fp8;
- (void)addGreetingAndSignoff;
- (void)removeGreetingAndSignoff;
- (id)standardSignoff;
- (id)standardGreeting;
- (id)deflatedBodyFromTextView;
- (void)insertToken:(id)fp8;
- (void)updateNavigationButtons;
- (void)didToggleCommentSwitchToPreference:(int)fp8;
- (void)didTapInsert;
- (void)viewWillLayoutSubviews;
- (BOOL)showsToolsOnTheSide;
- (void)viewDidAppear:(BOOL)fp8;
- (void)loadView;
- (id)applyTokensToString:(id)fp8;
- (id)initWithTemplate:(id)fp8 mode:(int)fp12 tokens:(id)fp16;

@end

