/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABOutlineViewController.h"

@class TemplateGroup, TemplatePrefs;

@interface TemplatesViewController : ABOutlineViewController
{
    TemplatePrefs *_tPrefs;
    TemplateGroup *_group;
    id _onDismiss;
}

- (void)setOnDismiss:(id)fp(null);
- (id)onDismiss;
- (void)setGroup:(id)fp8;
- (id)group;
- (void)setTPrefs:(id)fp8;
- (id)tPrefs;
- (void).cxx_destruct;
- (id)tokenReplacerModeratorUsername;
- (id)tokenReplacerLinkToWiki;
- (id)tokenReplacerLinkToSidebar;
- (id)tokenReplacerLinkToSubreddit;
- (id)tokenReplacerLinkToPost;
- (id)tokenReplacerPosterUsername;
- (void)tableView:(id)fp8 moveRowAtIndexPath:(id)fp12 toIndexPath:(id)fp16;
- (id)tableView:(id)fp8 targetIndexPathForMoveFromRowAtIndexPath:(id)fp12 toProposedIndexPath:(id)fp16;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (BOOL)tableView:(id)fp8 canMoveRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 shouldIndentWhileEditingRowAtIndexPath:(id)fp12;
- (void)disableEditMode;
- (void)enableEditMode;
- (void)animateNodeChanges;
- (void)didTapAddTemplateButton;
- (void)showTemplateGroupSelection;
- (void)updateViewWithCurrentGroupSelection;
- (void)viewDidLoad;
- (void)generateNodes;
- (id)generateTemplateNodeForTemplate:(id)fp8;
- (void)didSelectTemplate:(id)fp8;
- (id)tokensWhenEditing;
- (void)dismissMe;
- (void)reloadTemplatePreferences;
- (void)commonInitializerSetup;
- (id)initWithDefaultGroupIdent:(id)fp8;
- (id)init;

@end

