/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SyncHandler.h"

@interface TemplatesSyncHandler : SyncHandler
{
}

- (void)finishedProcessingRemoteMerge;
- (id)mergeChangeFromLocalObject:(id)fp8 remoteObject:(id)fp12;
- (id)mergedTemplateGroupWithLeftGroup:(id)fp8 rightGroup:(id)fp12;
- (BOOL)requiresSyncing:(id)fp8 remoteObject:(id)fp12;
- (void)finishedSendingToCloudAfterUserDefaultsChange;
- (BOOL)shouldSendToCloudOnUserDefaultsChange;
- (id)keyToMonitor;

@end

