/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView;

@interface TemplateSendModeSwitchView : _AVAudioSessionCategoryPlayback
{
    BOOL _i_switchOn;
    UIImageView *_trackView;
    UIImageView *_leftIconView;
    UIImageView *_rightIconView;
    id _onSendSwitchChange;
}

+ (id)imageForTrackViewActiveColor:(id)fp8 switchOn:(BOOL)fp12;
- (void)setI_switchOn:(BOOL)fp8;
- (BOOL)i_switchOn;
- (void)setOnSendSwitchChange:(id)fp(null);
- (id)onSendSwitchChange;
- (void)setRightIconView:(id)fp8;
- (id)rightIconView;
- (void)setLeftIconView:(id)fp8;
- (id)leftIconView;
- (void)setTrackView:(id)fp8;
- (id)trackView;
- (void).cxx_destruct;
- (void)didSwipeLeft:(id)fp8;
- (void)didSwipeRight:(id)fp8;
- (void)didToggle;
- (void)setSwitchOn:(BOOL)fp8 animated:(BOOL)fp12 notifyDelegate:(BOOL)fp16;
- (void)setDefaultSendSwitchPreference:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

