/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "OptionNode.h"

@class Template;

@interface TemplateNode : OptionNode
{
    Template *_tPlate;
}

+ (Class)cellClass;
- (void)setTPlate:(id)fp8;
- (id)tPlate;
- (void).cxx_destruct;
- (id)initWithTemplate:(id)fp8;

@end

