/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface Template : _AVAudioSessionCategoryPlayback <NSCoding>
{
    BOOL _removed;
    BOOL _stockTemplate;
    NSString *_body;
    NSString *_title;
    int _sendPreference;
}

+ (id)templateWithTitle:(id)fp8 body:(id)fp12;
- (void)setStockTemplate:(BOOL)fp8;
- (BOOL)stockTemplate;
- (void)setRemoved:(BOOL)fp8;
- (BOOL)removed;
- (void)setSendPreference:(int)fp8;
- (int)sendPreference;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setBody:(id)fp8;
- (id)body;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;

@end

