/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NBaseOptionCell.h"

@class JMViewOverlay;

@interface TemplateCell : NBaseOptionCell
{
    JMViewOverlay *_headerOverlay;
}

+ (float)heightForNode:(id)fp8 tableView:(id)fp12;
+ (struct CGSize)textPadding;
- (void)setHeaderOverlay:(id)fp8;
- (id)headerOverlay;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (void)decorateCellBackground;
- (void)createSubviews;
- (void)layoutCellOverlays;
- (id)tPlate;

@end

