/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMViewOverlay.h"

@interface ThreadLinesOverlay : JMViewOverlay
{
    unsigned int _level;
}

- (void)setLevel:(unsigned int)fp8;
- (unsigned int)level;
- (void)drawRect:(struct CGRect)fp8;
- (void)updateWithLevel:(unsigned int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

