/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "TTransport-Protocol.h"

@class ENAFURLConnectionOperation, NSData, NSMutableData, NSMutableURLRequest, NSOperationQueue, NSString, NSURL;

@interface THTTPClient : _AVAudioSessionCategoryPlayback <TTransport>
{
    NSURL *mURL;
    NSMutableURLRequest *mRequest;
    NSMutableData *mRequestData;
    NSData *mResponseData;
    int mResponseDataOffset;
    NSString *mUserAgent;
    int mTimeout;
    id _uploadBlock;
    id _downloadBlock;
    NSOperationQueue *_operationQueue;
    ENAFURLConnectionOperation *_httpOperation;
}

+ (id)createClientVersionString;
- (void)setHttpOperation:(id)fp8;
- (id)httpOperation;
- (void)setOperationQueue:(id)fp8;
- (id)operationQueue;
- (void)setDownloadBlock:(id)fp(null);
- (id)downloadBlock;
- (void)setUploadBlock:(id)fp(null);
- (id)uploadBlock;
- (void).cxx_destruct;
- (void)setDownloadProgressBlock:(id)fp(null);
- (void)setUploadProgressBlock:(id)fp(null);
- (void)cancel;
- (void)flush;
- (void)write:(const char *)fp8 offset:(unsigned int)fp12 length:(unsigned int)fp16;
- (int)readAll:(char *)fp8 offset:(int)fp12 length:(int)fp16;
- (void)dealloc;
- (void)setURL:(id)fp8;
- (id)initWithURL:(id)fp8 userAgent:(id)fp12 timeout:(int)fp16;
- (id)initWithURL:(id)fp8;
- (void)setupRequest;

@end

