/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMViewOverlay.h"

@class NSString, UIImage;

@interface ThumbOverlay : JMViewOverlay
{
    BOOL _showRightArrow;
    BOOL _allowLocalImageReplacement;
    BOOL _showRetinaVersion;
    NSString *_url;
    NSString *_fallbackUrl;
    UIImage *_lastImage;
}

- (void)setLastImage:(id)fp8;
- (id)lastImage;
- (void)setShowRetinaVersion:(BOOL)fp8;
- (BOOL)showRetinaVersion;
- (void)setFallbackUrl:(id)fp8;
- (id)fallbackUrl;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)setAllowLocalImageReplacement:(BOOL)fp8;
- (BOOL)allowLocalImageReplacement;
- (void)setShowRightArrow:(BOOL)fp8;
- (BOOL)showRightArrow;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (void)updateWithPost:(id)fp8;
- (void)updateWithUrl:(id)fp8 fallbackUrl:(id)fp12 showRetinaVersion:(BOOL)fp16;

@end

