/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "TTransport-Protocol.h"

@class NSMutableData;

@interface TMemoryBuffer : _AVAudioSessionCategoryPlayback <TTransport>
{
    NSMutableData *mBuffer;
    unsigned int mOffset;
}

- (void).cxx_destruct;
- (void)setDownloadProgressBlock:(id)fp(null);
- (void)setUploadProgressBlock:(id)fp(null);
- (void)cancel;
- (void)dealloc;
- (id)getBuffer;
- (void)flush;
- (void)write:(const char *)fp8 offset:(unsigned int)fp12 length:(unsigned int)fp16;
- (int)readAll:(char *)fp8 offset:(int)fp12 length:(int)fp16;
- (id)initWithData:(id)fp8;
- (id)init;

@end

