/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABToolbar.h"

@interface TransparentToolbar : ABToolbar
{
}

- (void)setFrame:(struct CGRect)fp8;
- (void)handleTintSwitch;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)init;
- (void)applyTranslucentBackground;
- (void)drawRect:(struct CGRect)fp8;

@end

