/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSDate, NSMutableArray, NSString, SubredditFolder;

@interface UserSubredditPreferences : _AVAudioSessionCategoryPlayback <NSCoding>
{
    BOOL _i_shouldSyncToCloud;
    NSMutableArray *_subredditFolders;
    NSString *_username;
    NSDate *_lastModifiedDate;
    NSDate *_lastSyncedDate;
    NSMutableArray *_changeLog;
    SubredditFolder *_i_manuallySubscribedFolder;
    SubredditFolder *_i_manuallyUnsubscribedFolder;
    SubredditFolder *_i_myRedditsSectionFolder;
    SubredditFolder *_i_discoverSectionFolder;
    UserSubredditPreferences *_i_sharedSubredditPreferences;
}

+ (id)defaultSubredditsFolder;
+ (id)subredditPreferencesForAuthenticatedUser;
+ (id)rawDefaultsDataForSubredditPreferences:(id)fp8;
+ (id)subredditPreferencesFromRawDefaultsData:(id)fp8;
+ (id)prefKey;
- (void)setI_sharedSubredditPreferences:(id)fp8;
- (id)i_sharedSubredditPreferences;
- (void)setI_discoverSectionFolder:(id)fp8;
- (id)i_discoverSectionFolder;
- (void)setI_myRedditsSectionFolder:(id)fp8;
- (id)i_myRedditsSectionFolder;
- (void)setI_shouldSyncToCloud:(BOOL)fp8;
- (BOOL)i_shouldSyncToCloud;
- (void)setI_manuallyUnsubscribedFolder:(id)fp8;
- (id)i_manuallyUnsubscribedFolder;
- (void)setI_manuallySubscribedFolder:(id)fp8;
- (id)i_manuallySubscribedFolder;
- (void)setChangeLog:(id)fp8;
- (id)changeLog;
- (void)setLastSyncedDate:(id)fp8;
- (id)lastSyncedDate;
- (void)setLastModifiedDate:(id)fp8;
- (id)lastModifiedDate;
- (void)setUsername:(id)fp8;
- (id)username;
- (void)setSubredditFolders:(id)fp8;
- (id)subredditFolders;
- (void).cxx_destruct;
- (void)checkSyncThreshold;
- (void)didSyncToCloud;
- (BOOL)shouldSyncToCloud;
- (void)recommendSyncToCloud;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)removeSubredditFolder:(id)fp8;
- (void)renameSubredditFolder:(id)fp8 toTitle:(id)fp12;
- (id)createSubredditFolderWithTitle:(id)fp8;
- (void)addSubredditFolder:(id)fp8 atIndex:(unsigned int)fp12;
- (void)syncServerRetrievedSubredditsToSubscribed:(id)fp8;
- (id)folderContainingSubreddit:(id)fp8;
- (id)foldersContainingSubreddit:(id)fp8;
- (void)sortAllFolders;
- (void)removeSubredditFromAllFolders:(id)fp8;
- (void)removeSubreddit:(id)fp8 fromFolder:(id)fp12;
- (void)addSubreddit:(id)fp8 toFolder:(id)fp12;
- (void)addSubreddit:(id)fp8 toFolder:(id)fp12 atIndex:(unsigned int)fp16;
- (id)folderForCasualReddits;
- (id)folderForSubscribedReddits;
- (void)recordChange:(int)fp8 subreddit:(id)fp12 folder:(id)fp16;
- (void)recordReorderOfSubreddit:(id)fp8 folder:(id)fp12 rowIndex:(unsigned int)fp16;
- (void)appendToChangeLog:(id)fp8;
- (void)save;
- (unsigned int)totalSubredditCount;
- (id)folderMatchingIdent:(id)fp8;
- (id)folderForDiscoverSection;
- (id)folderForMyRedditsSection;
- (void)importLegacyCasualSubreddits;

@end

